using System.Collections.Generic;
using System.Diagnostics;
using InnoWerks.Processors;

#pragma warning disable CA1043

namespace InnoWerks.Disassemblers
{
    [DebuggerDisplay("{OpCode.ToString()} {AddressingMode.ToString()}")]
    public class InstructionDecoding
    {
        public InstructionDecoding(
            OpCode opCode,
            string instruction,
            AddressingMode addressingMode,
            CpuClass minCpuClass
        )
        {
            OpCode = opCode;
            Instruction = instruction;
            AddressingMode = addressingMode;
            MinCpuClass = minCpuClass;
        }

        public OpCode OpCode { get; init; }

        public string Instruction { get; init; }

        public AddressingMode AddressingMode { get; init; }

        public CpuClass MinCpuClass { get; init; }
    }

    public class Instructions
    {
        private static readonly List<InstructionDecoding> decoding =
        [
            /* $00 */ new(OpCode.BRK, "BRK", AddressingMode.Stack, CpuClass.WDC6502),
            /* $01 */ new(OpCode.ORA, "ORA", AddressingMode.XIndexedIndirect, CpuClass.WDC6502),
            /* $02 */ new(OpCode.Unknown, "???", AddressingMode.Unknown, CpuClass.None),
            /* $03 */ new(OpCode.Unknown, "???", AddressingMode.Unknown, CpuClass.None),
            /* $04 */ new(OpCode.TSB, "TSB", AddressingMode.ZeroPage, CpuClass.WDC65C02),
            /* $05 */ new(OpCode.ORA, "ORA", AddressingMode.ZeroPage, CpuClass.WDC6502),
            /* $06 */ new(OpCode.ASL, "ASL", AddressingMode.ZeroPage, CpuClass.WDC6502),
            /* $07 */ new(OpCode.RMB0, "RMB0", AddressingMode.ZeroPage, CpuClass.WDC65C02),
            /* $08 */ new(OpCode.PHP, "PHP", AddressingMode.Stack, CpuClass.WDC6502),
            /* $09 */ new(OpCode.ORA, "ORA", AddressingMode.Immediate, CpuClass.WDC6502),
            /* $0A */ new(OpCode.ASL_A, "ASL A", AddressingMode.Accumulator, CpuClass.WDC6502),
            /* $0B */ new(OpCode.Unknown, "???", AddressingMode.Unknown, CpuClass.None),
            /* $0C */ new(OpCode.TSB, "TSB", AddressingMode.Absolute, CpuClass.WDC65C02),
            /* $0D */ new(OpCode.ORA, "ORA", AddressingMode.Absolute, CpuClass.WDC6502),
            /* $0E */ new(OpCode.ASL, "ASL", AddressingMode.Absolute, CpuClass.WDC6502),
            /* $0F */ new(OpCode.BBR0, "BBR0", AddressingMode.Relative, CpuClass.WDC65C02),
            /* $10 */ new(OpCode.BPL, "BPL", AddressingMode.Relative, CpuClass.WDC6502),
            /* $11 */ new(OpCode.ORA, "ORA", AddressingMode.IndirectYIndexed, CpuClass.WDC6502),
            /* $12 */ new(OpCode.ORA, "ORA", AddressingMode.ZeroPageIndirect, CpuClass.WDC65C02),
            /* $13 */ new(OpCode.Unknown, "???", AddressingMode.Unknown, CpuClass.None),
            /* $14 */ new(OpCode.TRB, "TRB", AddressingMode.ZeroPage, CpuClass.WDC65C02),
            /* $15 */ new(OpCode.ORA, "ORA", AddressingMode.ZeroPageXIndexed, CpuClass.WDC6502),
            /* $16 */ new(OpCode.ASL, "ASL", AddressingMode.ZeroPageXIndexed, CpuClass.WDC6502),
            /* $17 */ new(OpCode.RMB1, "RMB1", AddressingMode.ZeroPage, CpuClass.WDC65C02),
            /* $18 */ new(OpCode.CLC, "CLC", AddressingMode.Implicit, CpuClass.WDC6502),
            /* $19 */ new(OpCode.ORA, "ORA", AddressingMode.AbsoluteYIndexed, CpuClass.WDC6502),
            /* $1A */ new(OpCode.INA, "INC A", AddressingMode.Accumulator, CpuClass.WDC65C02),
            /* $1B */ new(OpCode.Unknown, "???", AddressingMode.Unknown, CpuClass.None),
            /* $1C */ new(OpCode.TRB, "TRB", AddressingMode.Absolute, CpuClass.WDC65C02),
            /* $1D */ new(OpCode.ORA, "ORA", AddressingMode.AbsoluteXIndexed, CpuClass.WDC6502),
            /* $1E */ new(OpCode.ASL, "ASL", AddressingMode.AbsoluteXIndexed, CpuClass.WDC6502),
            /* $1F */ new(OpCode.BBR1, "BBR1", AddressingMode.Relative, CpuClass.WDC65C02),
            /* $20 */ new(OpCode.JSR, "JSR", AddressingMode.Absolute, CpuClass.WDC6502),
            /* $21 */ new(OpCode.AND, "AND", AddressingMode.XIndexedIndirect, CpuClass.WDC6502),
            /* $22 */ new(OpCode.Unknown, "???", AddressingMode.Unknown, CpuClass.None),
            /* $23 */ new(OpCode.Unknown, "???", AddressingMode.Unknown, CpuClass.None),
            /* $24 */ new(OpCode.BIT, "BIT", AddressingMode.ZeroPage, CpuClass.WDC6502),
            /* $25 */ new(OpCode.AND, "AND", AddressingMode.ZeroPage, CpuClass.WDC6502),
            /* $26 */ new(OpCode.ROL, "ROL", AddressingMode.ZeroPage, CpuClass.WDC6502),
            /* $27 */ new(OpCode.RMB2, "RMB2", AddressingMode.ZeroPage, CpuClass.WDC65C02),
            /* $28 */ new(OpCode.PLP, "PLP", AddressingMode.Stack, CpuClass.WDC6502),
            /* $29 */ new(OpCode.AND, "AND", AddressingMode.Immediate, CpuClass.WDC6502),
            /* $2A */ new(OpCode.ROL_A, "ROL A", AddressingMode.Accumulator, CpuClass.WDC6502),
            /* $2B */ new(OpCode.Unknown, "???", AddressingMode.Unknown, CpuClass.None),
            /* $2C */ new(OpCode.BIT, "BIT", AddressingMode.Absolute, CpuClass.WDC6502),
            /* $2D */ new(OpCode.AND, "AND", AddressingMode.Absolute, CpuClass.WDC6502),
            /* $2E */ new(OpCode.ROL, "ROL", AddressingMode.Absolute, CpuClass.WDC6502),
            /* $2F */ new(OpCode.BBR2, "BBR2", AddressingMode.Relative, CpuClass.WDC65C02),
            /* $30 */ new(OpCode.BMI, "BMI", AddressingMode.Relative, CpuClass.WDC6502),
            /* $31 */ new(OpCode.AND, "AND", AddressingMode.IndirectYIndexed, CpuClass.WDC6502),
            /* $32 */ new(OpCode.AND, "AND", AddressingMode.ZeroPageIndirect, CpuClass.WDC65C02),
            /* $33 */ new(OpCode.Unknown, "???", AddressingMode.Unknown, CpuClass.None),
            /* $34 */ new(OpCode.BIT, "BIT", AddressingMode.ZeroPageXIndexed, CpuClass.WDC65C02),
            /* $35 */ new(OpCode.AND, "AND", AddressingMode.ZeroPageXIndexed, CpuClass.WDC6502),
            /* $36 */ new(OpCode.ROL, "ROL", AddressingMode.ZeroPageXIndexed, CpuClass.WDC6502),
            /* $37 */ new(OpCode.RMB3, "RMB3", AddressingMode.ZeroPage, CpuClass.WDC65C02),
            /* $38 */ new(OpCode.SEC, "SEC", AddressingMode.Implicit, CpuClass.WDC6502),
            /* $39 */ new(OpCode.AND, "AND", AddressingMode.AbsoluteYIndexed, CpuClass.WDC6502),
            /* $3A */ new(OpCode.DEA, "DEC A", AddressingMode.Accumulator, CpuClass.WDC65C02),
            /* $3B */ new(OpCode.Unknown, "???", AddressingMode.Unknown, CpuClass.None),
            /* $3C */ new(OpCode.BIT, "BIT", AddressingMode.AbsoluteXIndexed, CpuClass.WDC65C02),
            /* $3D */ new(OpCode.AND, "AND", AddressingMode.AbsoluteXIndexed, CpuClass.WDC6502),
            /* $3E */ new(OpCode.ROL, "ROL", AddressingMode.AbsoluteXIndexed, CpuClass.WDC6502),
            /* $3F */ new(OpCode.BBR3, "BBR3", AddressingMode.Relative, CpuClass.WDC65C02),
            /* $40 */ new(OpCode.RTI, "RTI", AddressingMode.Stack, CpuClass.WDC6502),
            /* $41 */ new(OpCode.EOR, "EOR", AddressingMode.XIndexedIndirect, CpuClass.WDC6502),
            /* $42 */ new(OpCode.Unknown, "???", AddressingMode.Unknown, CpuClass.None),
            /* $43 */ new(OpCode.Unknown, "???", AddressingMode.Unknown, CpuClass.None),
            /* $44 */ new(OpCode.Unknown, "???", AddressingMode.Unknown, CpuClass.None),
            /* $45 */ new(OpCode.EOR, "EOR", AddressingMode.ZeroPage, CpuClass.WDC6502),
            /* $46 */ new(OpCode.LSR, "LSR", AddressingMode.ZeroPage, CpuClass.WDC6502),
            /* $47 */ new(OpCode.RMB4, "RMB4", AddressingMode.ZeroPage, CpuClass.WDC65C02),
            /* $48 */ new(OpCode.PHA, "PHA", AddressingMode.Stack, CpuClass.WDC6502),
            /* $49 */ new(OpCode.EOR, "EOR", AddressingMode.Immediate, CpuClass.WDC6502),
            /* $4A */ new(OpCode.LSR_A, "LSR A", AddressingMode.Accumulator, CpuClass.WDC6502),
            /* $4B */ new(OpCode.Unknown, "???", AddressingMode.Unknown, CpuClass.None),
            /* $4C */ new(OpCode.JMP, "JMP", AddressingMode.Absolute, CpuClass.WDC6502),
            /* $4D */ new(OpCode.EOR, "EOR", AddressingMode.Absolute, CpuClass.WDC6502),
            /* $4E */ new(OpCode.LSR, "LSR", AddressingMode.Absolute, CpuClass.WDC6502),
            /* $4F */ new(OpCode.BBR4, "BBR4", AddressingMode.Relative, CpuClass.WDC65C02),
            /* $50 */ new(OpCode.BVC, "BVC", AddressingMode.Relative, CpuClass.WDC6502),
            /* $51 */ new(OpCode.EOR, "EOR", AddressingMode.IndirectYIndexed, CpuClass.WDC6502),
            /* $52 */ new(OpCode.EOR, "EOR", AddressingMode.ZeroPageIndirect, CpuClass.WDC65C02),
            /* $53 */ new(OpCode.Unknown, "???", AddressingMode.Unknown, CpuClass.None),
            /* $54 */ new(OpCode.Unknown, "???", AddressingMode.Unknown, CpuClass.None),
            /* $55 */ new(OpCode.EOR, "EOR", AddressingMode.ZeroPageXIndexed, CpuClass.WDC6502),
            /* $56 */ new(OpCode.LSR, "LSR", AddressingMode.ZeroPageXIndexed, CpuClass.WDC6502),
            /* $57 */ new(OpCode.RMB5, "RMB5", AddressingMode.ZeroPage, CpuClass.WDC65C02),
            /* $58 */ new(OpCode.CLI, "CLI", AddressingMode.Implicit, CpuClass.WDC6502),
            /* $59 */ new(OpCode.EOR, "EOR", AddressingMode.AbsoluteYIndexed, CpuClass.WDC6502),
            /* $5A */ new(OpCode.PHY, "PHY", AddressingMode.Stack, CpuClass.WDC65C02),
            /* $5B */ new(OpCode.Unknown, "???", AddressingMode.Unknown, CpuClass.None),
            /* $5C */ new(OpCode.Unknown, "???", AddressingMode.Unknown, CpuClass.None),
            /* $5D */ new(OpCode.EOR, "EOR", AddressingMode.AbsoluteXIndexed, CpuClass.WDC6502),
            /* $5E */ new(OpCode.LSR, "LSR", AddressingMode.AbsoluteXIndexed, CpuClass.WDC6502),
            /* $5F */ new(OpCode.BBR5, "BBR5", AddressingMode.Relative, CpuClass.WDC65C02),
            /* $60 */ new(OpCode.RTS, "RTS", AddressingMode.Stack, CpuClass.WDC6502),
            /* $61 */ new(OpCode.ADC, "ADC", AddressingMode.XIndexedIndirect, CpuClass.WDC6502),
            /* $62 */ new(OpCode.Unknown, "???", AddressingMode.Unknown, CpuClass.None),
            /* $63 */ new(OpCode.Unknown, "???", AddressingMode.Unknown, CpuClass.None),
            /* $64 */ new(OpCode.STZ, "STZ", AddressingMode.ZeroPage, CpuClass.WDC65C02),
            /* $65 */ new(OpCode.ADC, "ADC", AddressingMode.ZeroPage, CpuClass.WDC6502),
            /* $66 */ new(OpCode.ROR, "ROR", AddressingMode.ZeroPage, CpuClass.WDC6502),
            /* $67 */ new(OpCode.RMB6, "RMB6", AddressingMode.ZeroPage, CpuClass.WDC65C02),
            /* $68 */ new(OpCode.PLA, "PLA", AddressingMode.Stack, CpuClass.WDC6502),
            /* $69 */ new(OpCode.ADC, "ADC", AddressingMode.Immediate, CpuClass.WDC6502),
            /* $6A */ new(OpCode.ROR_A, "ROR A", AddressingMode.Accumulator, CpuClass.WDC6502),
            /* $6B */ new(OpCode.Unknown, "???", AddressingMode.Unknown, CpuClass.None),
            /* $6C */ new(OpCode.JMP, "JMP", AddressingMode.AbsoluteIndirect, CpuClass.WDC6502),
            /* $6D */ new(OpCode.ADC, "ADC", AddressingMode.Absolute, CpuClass.WDC6502),
            /* $6E */ new(OpCode.ROR, "ROR", AddressingMode.Absolute, CpuClass.WDC6502),
            /* $6F */ new(OpCode.BBR6, "BBR6", AddressingMode.Relative, CpuClass.WDC65C02),
            /* $70 */ new(OpCode.BVS, "BVS", AddressingMode.Relative, CpuClass.WDC6502),
            /* $71 */ new(OpCode.ADC, "ADC", AddressingMode.IndirectYIndexed, CpuClass.WDC6502),
            /* $72 */ new(OpCode.ADC, "ADC", AddressingMode.ZeroPageIndirect, CpuClass.WDC65C02),
            /* $73 */ new(OpCode.Unknown, "???", AddressingMode.Unknown, CpuClass.None),
            /* $74 */ new(OpCode.STZ, "STZ", AddressingMode.ZeroPageXIndexed, CpuClass.WDC65C02),
            /* $75 */ new(OpCode.ADC, "ADC", AddressingMode.ZeroPageXIndexed, CpuClass.WDC6502),
            /* $76 */ new(OpCode.ROR, "ROR", AddressingMode.ZeroPageXIndexed, CpuClass.WDC6502),
            /* $77 */ new(OpCode.RMB7, "RMB7", AddressingMode.ZeroPage, CpuClass.WDC65C02),
            /* $78 */ new(OpCode.SEI, "SEI", AddressingMode.Implicit, CpuClass.WDC6502),
            /* $79 */ new(OpCode.ADC, "ADC", AddressingMode.AbsoluteYIndexed, CpuClass.WDC6502),
            /* $7A */ new(OpCode.PLY, "PLY", AddressingMode.Stack, CpuClass.WDC65C02),
            /* $7B */ new(OpCode.Unknown, "???", AddressingMode.Unknown, CpuClass.None),
            /* $7C */ new(OpCode.JMP, "JMP", AddressingMode.AbsoluteIndexedIndirect, CpuClass.WDC65C02),
            /* $7D */ new(OpCode.ADC, "ADC", AddressingMode.AbsoluteXIndexed, CpuClass.WDC6502),
            /* $7E */ new(OpCode.ROR, "ROR", AddressingMode.AbsoluteXIndexed, CpuClass.WDC6502),
            /* $7F */ new(OpCode.BBR7, "BBR7", AddressingMode.Relative, CpuClass.WDC65C02),
            /* $80 */ new(OpCode.BRA, "BRA", AddressingMode.Relative, CpuClass.WDC65C02),
            /* $81 */ new(OpCode.STA, "STA", AddressingMode.XIndexedIndirect, CpuClass.WDC6502),
            /* $82 */ new(OpCode.Unknown, "???", AddressingMode.Unknown, CpuClass.None),
            /* $83 */ new(OpCode.Unknown, "???", AddressingMode.Unknown, CpuClass.None),
            /* $84 */ new(OpCode.STY, "STY", AddressingMode.ZeroPage, CpuClass.WDC6502),
            /* $85 */ new(OpCode.STA, "STA", AddressingMode.ZeroPage, CpuClass.WDC6502),
            /* $86 */ new(OpCode.STX, "STX", AddressingMode.ZeroPage, CpuClass.WDC6502),
            /* $87 */ new(OpCode.SMB0, "SMB0", AddressingMode.ZeroPage, CpuClass.WDC65C02),
            /* $88 */ new(OpCode.DEY, "DEY", AddressingMode.Implicit, CpuClass.WDC6502),
            /* $89 */ new(OpCode.BIT, "BIT", AddressingMode.Immediate, CpuClass.WDC65C02),
            /* $8A */ new(OpCode.TXA, "TXA", AddressingMode.Implicit, CpuClass.WDC6502),
            /* $8B */ new(OpCode.Unknown, "???", AddressingMode.Unknown, CpuClass.None),
            /* $8C */ new(OpCode.STY, "STY", AddressingMode.Absolute, CpuClass.WDC6502),
            /* $8D */ new(OpCode.STA, "STA", AddressingMode.Absolute, CpuClass.WDC6502),
            /* $8E */ new(OpCode.STX, "STX", AddressingMode.Absolute, CpuClass.WDC6502),
            /* $8F */ new(OpCode.BBS0, "BBS0", AddressingMode.Relative, CpuClass.WDC65C02),
            /* $90 */ new(OpCode.BCC, "BCC", AddressingMode.Relative, CpuClass.WDC6502),
            /* $91 */ new(OpCode.STA, "STA", AddressingMode.IndirectYIndexed, CpuClass.WDC6502),
            /* $92 */ new(OpCode.STA, "STA", AddressingMode.ZeroPageIndirect, CpuClass.WDC65C02),
            /* $93 */ new(OpCode.Unknown, "???", AddressingMode.Unknown, CpuClass.None),
            /* $94 */ new(OpCode.STY, "STY", AddressingMode.ZeroPageXIndexed, CpuClass.WDC6502),
            /* $95 */ new(OpCode.STA, "STA", AddressingMode.ZeroPageXIndexed, CpuClass.WDC6502),
            /* $96 */ new(OpCode.STX, "STX", AddressingMode.ZeroPageYIndexed, CpuClass.WDC6502),
            /* $97 */ new(OpCode.SMB1, "SMB1", AddressingMode.ZeroPage, CpuClass.WDC65C02),
            /* $98 */ new(OpCode.TYA, "TYA", AddressingMode.Implicit, CpuClass.WDC6502),
            /* $99 */ new(OpCode.STA, "STA", AddressingMode.AbsoluteYIndexed, CpuClass.WDC6502),
            /* $9A */ new(OpCode.TXS, "TXS", AddressingMode.Implicit, CpuClass.WDC6502),
            /* $9B */ new(OpCode.Unknown, "???", AddressingMode.Unknown, CpuClass.None),
            /* $9C */ new(OpCode.STZ, "STZ", AddressingMode.Absolute, CpuClass.WDC65C02),
            /* $9D */ new(OpCode.STA, "STA", AddressingMode.AbsoluteXIndexed, CpuClass.WDC6502),
            /* $9E */ new(OpCode.STZ, "STZ", AddressingMode.AbsoluteXIndexed, CpuClass.WDC65C02),
            /* $9F */ new(OpCode.BBS1, "BBS1", AddressingMode.Relative, CpuClass.WDC65C02),
            /* $A0 */ new(OpCode.LDY, "LDY", AddressingMode.Immediate, CpuClass.WDC6502),
            /* $A1 */ new(OpCode.LDA, "LDA", AddressingMode.XIndexedIndirect, CpuClass.WDC6502),
            /* $A2 */ new(OpCode.LDX, "LDX", AddressingMode.Immediate, CpuClass.WDC6502),
            /* $A3 */ new(OpCode.Unknown, "???", AddressingMode.Unknown, CpuClass.None),
            /* $A4 */ new(OpCode.LDY, "LDY", AddressingMode.ZeroPage, CpuClass.WDC6502),
            /* $A5 */ new(OpCode.LDA, "LDA", AddressingMode.ZeroPage, CpuClass.WDC6502),
            /* $A6 */ new(OpCode.LDX, "LDX", AddressingMode.ZeroPage, CpuClass.WDC6502),
            /* $A7 */ new(OpCode.SMB2, "SMB2", AddressingMode.ZeroPage, CpuClass.WDC65C02),
            /* $A8 */ new(OpCode.TAY, "TAY", AddressingMode.Implicit, CpuClass.WDC6502),
            /* $A9 */ new(OpCode.LDA, "LDA", AddressingMode.Immediate, CpuClass.WDC6502),
            /* $AA */ new(OpCode.TAX, "TAX", AddressingMode.Implicit, CpuClass.WDC6502),
            /* $AB */ new(OpCode.Unknown, "???", AddressingMode.Unknown, CpuClass.None),
            /* $AC */ new(OpCode.LDY, "LDY", AddressingMode.Absolute, CpuClass.WDC6502),
            /* $AD */ new(OpCode.LDA, "LDA", AddressingMode.Absolute, CpuClass.WDC6502),
            /* $AE */ new(OpCode.LDX, "LDX", AddressingMode.Absolute, CpuClass.WDC6502),
            /* $AF */ new(OpCode.BBS2, "BBS2", AddressingMode.Relative, CpuClass.WDC65C02),
            /* $B0 */ new(OpCode.BCS, "BCS", AddressingMode.Relative, CpuClass.WDC6502),
            /* $B1 */ new(OpCode.LDA, "LDA", AddressingMode.IndirectYIndexed, CpuClass.WDC6502),
            /* $B2 */ new(OpCode.LDA, "LDA", AddressingMode.ZeroPageIndirect, CpuClass.WDC65C02),
            /* $B3 */ new(OpCode.Unknown, "???", AddressingMode.Unknown, CpuClass.None),
            /* $B4 */ new(OpCode.LDY, "LDY", AddressingMode.ZeroPageXIndexed, CpuClass.WDC6502),
            /* $B5 */ new(OpCode.LDA, "LDA", AddressingMode.ZeroPageXIndexed, CpuClass.WDC6502),
            /* $B6 */ new(OpCode.LDX, "LDX", AddressingMode.ZeroPageYIndexed, CpuClass.WDC6502),
            /* $B7 */ new(OpCode.SMB3, "SMB3", AddressingMode.ZeroPage, CpuClass.WDC65C02),
            /* $B8 */ new(OpCode.CLV, "CLV", AddressingMode.Implicit, CpuClass.WDC6502),
            /* $B9 */ new(OpCode.LDA, "LDA", AddressingMode.AbsoluteYIndexed, CpuClass.WDC6502),
            /* $BA */ new(OpCode.TSX, "TSX", AddressingMode.Implicit, CpuClass.WDC6502),
            /* $BB */ new(OpCode.Unknown, "???", AddressingMode.Unknown, CpuClass.None),
            /* $BC */ new(OpCode.LDY, "LDY", AddressingMode.AbsoluteXIndexed, CpuClass.WDC6502),
            /* $BD */ new(OpCode.LDA, "LDA", AddressingMode.AbsoluteXIndexed, CpuClass.WDC6502),
            /* $BE */ new(OpCode.LDX, "LDX", AddressingMode.AbsoluteYIndexed, CpuClass.WDC6502),
            /* $BF */ new(OpCode.BBS3, "BBS3", AddressingMode.Relative, CpuClass.WDC65C02),
            /* $C0 */ new(OpCode.CPY, "CPY", AddressingMode.Immediate, CpuClass.WDC6502),
            /* $C1 */ new(OpCode.CMP, "CMP", AddressingMode.XIndexedIndirect, CpuClass.WDC6502),
            /* $C2 */ new(OpCode.Unknown, "???", AddressingMode.Unknown, CpuClass.None),
            /* $C3 */ new(OpCode.Unknown, "???", AddressingMode.Unknown, CpuClass.None),
            /* $C4 */ new(OpCode.CPY, "CPY", AddressingMode.ZeroPage, CpuClass.WDC6502),
            /* $C5 */ new(OpCode.CMP, "CMP", AddressingMode.ZeroPage, CpuClass.WDC6502),
            /* $C6 */ new(OpCode.DEC, "DEC", AddressingMode.ZeroPage, CpuClass.WDC6502),
            /* $C7 */ new(OpCode.SMB4, "SMB4", AddressingMode.ZeroPage, CpuClass.WDC65C02),
            /* $C8 */ new(OpCode.INY, "INY", AddressingMode.Implicit, CpuClass.WDC6502),
            /* $C9 */ new(OpCode.CMP, "CMP", AddressingMode.Immediate, CpuClass.WDC6502),
            /* $CA */ new(OpCode.DEX, "DEX", AddressingMode.Implicit, CpuClass.WDC6502),
            /* $CB */ new(OpCode.WAI, "WAI", AddressingMode.Implicit, CpuClass.WDC65C02),
            /* $CC */ new(OpCode.CPY, "CPY", AddressingMode.Absolute, CpuClass.WDC6502),
            /* $CD */ new(OpCode.CMP, "CMP", AddressingMode.Absolute, CpuClass.WDC6502),
            /* $CE */ new(OpCode.DEC, "DEC", AddressingMode.Absolute, CpuClass.WDC6502),
            /* $CF */ new(OpCode.BBS4, "BBS4", AddressingMode.Relative, CpuClass.WDC65C02),
            /* $D0 */ new(OpCode.BNE, "BNE", AddressingMode.Relative, CpuClass.WDC6502),
            /* $D1 */ new(OpCode.CMP, "CMP", AddressingMode.IndirectYIndexed, CpuClass.WDC6502),
            /* $D2 */ new(OpCode.CMP, "CMP", AddressingMode.ZeroPageIndirect, CpuClass.WDC65C02),
            /* $D3 */ new(OpCode.Unknown, "???", AddressingMode.Unknown, CpuClass.None),
            /* $D4 */ new(OpCode.Unknown, "???", AddressingMode.Unknown, CpuClass.None),
            /* $D5 */ new(OpCode.CMP, "CMP", AddressingMode.ZeroPageXIndexed, CpuClass.WDC6502),
            /* $D6 */ new(OpCode.DEC, "DEC", AddressingMode.ZeroPageXIndexed, CpuClass.WDC6502),
            /* $D7 */ new(OpCode.SMB5, "SMB5", AddressingMode.ZeroPage, CpuClass.WDC65C02),
            /* $D8 */ new(OpCode.CLD, "CLD", AddressingMode.Implicit, CpuClass.WDC6502),
            /* $D9 */ new(OpCode.CMP, "CMP", AddressingMode.AbsoluteYIndexed, CpuClass.WDC6502),
            /* $DA */ new(OpCode.PHX, "PHX", AddressingMode.Stack, CpuClass.WDC65C02),
            /* $DB */ new(OpCode.STP, "STP", AddressingMode.Implicit, CpuClass.WDC65C02),
            /* $DC */ new(OpCode.Unknown, "???", AddressingMode.Unknown, CpuClass.None),
            /* $DD */ new(OpCode.CMP, "CMP", AddressingMode.AbsoluteXIndexed, CpuClass.WDC6502),
            /* $DE */ new(OpCode.DEC, "DEC", AddressingMode.AbsoluteXIndexed, CpuClass.WDC6502),
            /* $DF */ new(OpCode.BBS5, "BBS5", AddressingMode.Relative, CpuClass.WDC65C02),
            /* $E0 */ new(OpCode.CPX, "CPX", AddressingMode.Immediate, CpuClass.WDC6502),
            /* $E1 */ new(OpCode.SBC, "SBC", AddressingMode.XIndexedIndirect, CpuClass.WDC6502),
            /* $E2 */ new(OpCode.Unknown, "???", AddressingMode.Unknown, CpuClass.None),
            /* $E3 */ new(OpCode.Unknown, "???", AddressingMode.Unknown, CpuClass.None),
            /* $E4 */ new(OpCode.CPX, "CPX", AddressingMode.ZeroPage, CpuClass.WDC6502),
            /* $E5 */ new(OpCode.SBC, "SBC", AddressingMode.ZeroPage, CpuClass.WDC6502),
            /* $E6 */ new(OpCode.INC, "INC", AddressingMode.ZeroPage, CpuClass.WDC6502),
            /* $E7 */ new(OpCode.SMB6, "SMB6", AddressingMode.ZeroPage, CpuClass.WDC65C02),
            /* $E8 */ new(OpCode.INX, "INX", AddressingMode.Implicit, CpuClass.WDC6502),
            /* $E9 */ new(OpCode.SBC, "SBC", AddressingMode.Immediate, CpuClass.WDC6502),
            /* $EA */ new(OpCode.NOP, "NOP", AddressingMode.Implicit, CpuClass.WDC6502),
            /* $EB */ new(OpCode.Unknown, "???", AddressingMode.Unknown, CpuClass.None),
            /* $EC */ new(OpCode.CPX, "CPX", AddressingMode.Absolute, CpuClass.WDC6502),
            /* $ED */ new(OpCode.SBC, "SBC", AddressingMode.Absolute, CpuClass.WDC6502),
            /* $EE */ new(OpCode.INC, "INC", AddressingMode.Absolute, CpuClass.WDC6502),
            /* $EF */ new(OpCode.BBS6, "BBS6", AddressingMode.Relative, CpuClass.WDC6502),
            /* $F0 */ new(OpCode.BEQ, "BEQ", AddressingMode.Relative, CpuClass.WDC6502),
            /* $F1 */ new(OpCode.SBC, "SBC", AddressingMode.IndirectYIndexed, CpuClass.WDC6502),
            /* $F2 */ new(OpCode.SBC, "SBC", AddressingMode.ZeroPageIndirect, CpuClass.WDC65C02),
            /* $F3 */ new(OpCode.Unknown, "???", AddressingMode.Unknown, CpuClass.None),
            /* $F4 */ new(OpCode.Unknown, "???", AddressingMode.Unknown, CpuClass.None),
            /* $F5 */ new(OpCode.SBC, "SBC", AddressingMode.ZeroPageXIndexed, CpuClass.WDC6502),
            /* $F6 */ new(OpCode.INC, "INC", AddressingMode.ZeroPageXIndexed, CpuClass.WDC6502),
            /* $F7 */ new(OpCode.SMB7, "SMB7", AddressingMode.ZeroPage, CpuClass.WDC65C02),
            /* $F8 */ new(OpCode.SED, "SED", AddressingMode.Implicit, CpuClass.WDC6502),
            /* $F9 */ new(OpCode.SBC, "SBC", AddressingMode.AbsoluteYIndexed, CpuClass.WDC6502),
            /* $FA */ new(OpCode.PLX, "PLX", AddressingMode.Stack, CpuClass.WDC65C02),
            /* $FB */ new(OpCode.Unknown, "???", AddressingMode.Unknown, CpuClass.None),
            /* $FC */ new(OpCode.Unknown, "???", AddressingMode.Unknown, CpuClass.None),
            /* $FD */ new(OpCode.SBC, "SBC", AddressingMode.AbsoluteXIndexed, CpuClass.WDC6502),
            /* $FE */ new(OpCode.INC, "INC", AddressingMode.AbsoluteXIndexed, CpuClass.WDC6502),
            /* $FF */ new(OpCode.BBS7, "BBS7", AddressingMode.Relative, CpuClass.WDC65C02),
        ];

        public InstructionDecoding this[ushort index] => decoding[index];
    }
}
