using System;
using System.Collections.Generic;
using InnoWerks.Processors;

namespace InnoWerks.Simulators
{
    //
    // See https://www.masswerk.at/nowgobang/2021/6502-illegal-opcodes for the DecodeUndefined sizes
    //
    public static class CpuInstructions
    {
        public static Dictionary<byte, OpCodeDefinition> GetInstructionSet(CpuClass cpuClass)
        {
            switch (cpuClass)
            {
                case CpuClass.Undefined:
                    throw new ArgumentOutOfRangeException(nameof(cpuClass), cpuClass, "CpuClass.Undefined is obviously not supported.");

                case CpuClass.WDC6502:
                    return OpCode6502;

                case CpuClass.WDC65C02:
                    return OpCode65C02;

                default:
                    throw new ArgumentOutOfRangeException(nameof(cpuClass), cpuClass, "CpuClass is not currently supported");
            }
        }

        public static readonly Dictionary<byte, OpCodeDefinition> OpCode65C02 = new()
        {
            { 0x00, new OpCodeDefinition(OpCode.BRK, (cpu, addr, value) => cpu.BRK(addr, value), (cpu) => cpu.DecodeStack(), AddressingMode.Stack) },
            { 0x01, new OpCodeDefinition(OpCode.ORA, (cpu, addr, value) => cpu.ORA(addr, value), (cpu) => cpu.DecodeXIndexedIndirect(), AddressingMode.XIndexedIndirect) },
            { 0x02, new OpCodeDefinition(OpCode.Unknown, (cpu, addr, value) => cpu.IllegalInstruction(addr, value), (cpu) => cpu.DecodeUndefined(2, 2), AddressingMode.Unknown) },
            { 0x03, new OpCodeDefinition(OpCode.Unknown, (cpu, addr, value) => cpu.IllegalInstruction(addr, value), (cpu) => cpu.DecodeUndefined(1, 1), AddressingMode.Unknown) },
            { 0x04, new OpCodeDefinition(OpCode.TSB, (cpu, addr, value) => cpu.TSB(addr, value), (cpu) => cpu.DecodeZeroPage(), AddressingMode.ZeroPage) },
            { 0x05, new OpCodeDefinition(OpCode.ORA, (cpu, addr, value) => cpu.ORA(addr, value), (cpu) => cpu.DecodeZeroPage(), AddressingMode.ZeroPage) },
            { 0x06, new OpCodeDefinition(OpCode.ASL, (cpu, addr, value) => cpu.ASL(addr, value), (cpu) => cpu.DecodeZeroPage(), AddressingMode.ZeroPage) },
            { 0x07, new OpCodeDefinition(OpCode.RMB0, (cpu, addr, value) => cpu.RMB(addr, value, bit: 0), (cpu) => cpu.DecodeZeroPage(), AddressingMode.ZeroPage) },
            { 0x08, new OpCodeDefinition(OpCode.PHP, (cpu, addr, value) => cpu.PHP(addr, value), (cpu) => cpu.DecodeStack(), AddressingMode.Stack) },
            { 0x09, new OpCodeDefinition(OpCode.ORA, (cpu, addr, value) => cpu.ORA(addr, value), (cpu) => cpu.DecodeImmediate(), AddressingMode.Immediate) },
            { 0x0a, new OpCodeDefinition(OpCode.ASL_A, (cpu, addr, value) => cpu.ASL_A(addr, value), (cpu) => cpu.DecodeAccumulator(), AddressingMode.Accumulator) },
            { 0x0b, new OpCodeDefinition(OpCode.Unknown, (cpu, addr, value) => cpu.IllegalInstruction(addr, value), (cpu) => cpu.DecodeUndefined(1, 1), AddressingMode.Unknown) },
            { 0x0c, new OpCodeDefinition(OpCode.TSB, (cpu, addr, value) => cpu.TSB(addr, value), (cpu) => cpu.DecodeAbsolute(), AddressingMode.Absolute) },
            { 0x0d, new OpCodeDefinition(OpCode.ORA, (cpu, addr, value) => cpu.ORA(addr, value), (cpu) => cpu.DecodeAbsolute(), AddressingMode.Absolute) },
            { 0x0e, new OpCodeDefinition(OpCode.ASL, (cpu, addr, value) => cpu.ASL(addr, value), (cpu) => cpu.DecodeAbsolute(), AddressingMode.Absolute) },
            { 0x0f, new OpCodeDefinition(OpCode.BBR0, (cpu, addr, value) => cpu.BBR(addr, value, bit: 0), (cpu) => cpu.DecodeZeroPage(), AddressingMode.Relative) },

            { 0x10, new OpCodeDefinition(OpCode.BPL, (cpu, addr, value) => cpu.BPL(addr, value), (cpu) => cpu.DecodeRelative(), AddressingMode.Relative) },
            { 0x11, new OpCodeDefinition(OpCode.ORA, (cpu, addr, value) => cpu.ORA(addr, value), (cpu) => cpu.DecodeIndirectYIndexed(), AddressingMode.IndirectYIndexed) },
            { 0x12, new OpCodeDefinition(OpCode.ORA, (cpu, addr, value) => cpu.ORA(addr, value), (cpu) => cpu.DecodeZeroPageIndirect(), AddressingMode.ZeroPageIndirect) },
            { 0x13, new OpCodeDefinition(OpCode.Unknown, (cpu, addr, value) => cpu.IllegalInstruction(addr, value), (cpu) => cpu.DecodeUndefined(1, 1), AddressingMode.Unknown) },
            { 0x14, new OpCodeDefinition(OpCode.TRB, (cpu, addr, value) => cpu.TRB(addr, value), (cpu) => cpu.DecodeZeroPage(), AddressingMode.ZeroPage) },
            { 0x15, new OpCodeDefinition(OpCode.ORA, (cpu, addr, value) => cpu.ORA(addr, value), (cpu) => cpu.DecodeZeroPageXIndexed(), AddressingMode.ZeroPageXIndexed) },
            { 0x16, new OpCodeDefinition(OpCode.ASL, (cpu, addr, value) => cpu.ASL(addr, value), (cpu) => cpu.DecodeZeroPageXIndexed(), AddressingMode.ZeroPageXIndexed) },
            { 0x17, new OpCodeDefinition(OpCode.RMB1, (cpu, addr, value) => cpu.RMB(addr, value, bit: 1), (cpu) => cpu.DecodeZeroPage(), AddressingMode.ZeroPage) },
            { 0x18, new OpCodeDefinition(OpCode.CLC, (cpu, addr, value) => cpu.CLC(addr, value), (cpu) => cpu.DecodeImplicit(), AddressingMode.Implicit) },
            { 0x19, new OpCodeDefinition(OpCode.ORA, (cpu, addr, value) => cpu.ORA(addr, value), (cpu) => cpu.DecodeAbsoluteYIndexed(), AddressingMode.AbsoluteYIndexed) },
            { 0x1a, new OpCodeDefinition(OpCode.INA, (cpu, addr, value) => cpu.INA(addr, value), (cpu) => cpu.DecodeAccumulator(), AddressingMode.Accumulator) },
            { 0x1b, new OpCodeDefinition(OpCode.Unknown, (cpu, addr, value) => cpu.IllegalInstruction(addr, value), (cpu) => cpu.DecodeUndefined(1, 1), AddressingMode.Unknown) },
            { 0x1c, new OpCodeDefinition(OpCode.TRB, (cpu, addr, value) => cpu.TRB(addr, value), (cpu) => cpu.DecodeAbsolute(), AddressingMode.Absolute) },
            { 0x1d, new OpCodeDefinition(OpCode.ORA, (cpu, addr, value) => cpu.ORA(addr, value), (cpu) => cpu.DecodeAbsoluteXIndexed(), AddressingMode.AbsoluteXIndexed) },
            { 0x1e, new OpCodeDefinition(OpCode.ASL, (cpu, addr, value) => cpu.ASL(addr, value), (cpu) => cpu.DecodeAbsoluteXIndexed(), AddressingMode.AbsoluteXIndexed) },
            { 0x1f, new OpCodeDefinition(OpCode.BBR1, (cpu, addr, value) => cpu.BBR(addr, value, bit: 1), (cpu) => cpu.DecodeZeroPage(), AddressingMode.Relative) },

            { 0x20, new OpCodeDefinition(OpCode.JSR, (cpu, addr, value) => cpu.JSR(addr, value), (cpu) => cpu.DecodeAbsolute(), AddressingMode.Absolute) },
            { 0x21, new OpCodeDefinition(OpCode.AND, (cpu, addr, value) => cpu.AND(addr, value), (cpu) => cpu.DecodeXIndexedIndirect(), AddressingMode.XIndexedIndirect) },
            { 0x22, new OpCodeDefinition(OpCode.Unknown, (cpu, addr, value) => cpu.IllegalInstruction(addr, value), (cpu) => cpu.DecodeUndefined(2, 2), AddressingMode.Unknown) },
            { 0x23, new OpCodeDefinition(OpCode.Unknown, (cpu, addr, value) => cpu.IllegalInstruction(addr, value), (cpu) => cpu.DecodeUndefined(1, 1), AddressingMode.Unknown) },
            { 0x24, new OpCodeDefinition(OpCode.BIT, (cpu, addr, value) => cpu.BIT(addr, value, immediateMode: false), (cpu) => cpu.DecodeZeroPage(), AddressingMode.ZeroPage) },
            { 0x25, new OpCodeDefinition(OpCode.AND, (cpu, addr, value) => cpu.AND(addr, value), (cpu) => cpu.DecodeZeroPage(), AddressingMode.ZeroPage) },
            { 0x26, new OpCodeDefinition(OpCode.ROL, (cpu, addr, value) => cpu.ROL(addr, value), (cpu) => cpu.DecodeZeroPage(), AddressingMode.ZeroPage) },
            { 0x27, new OpCodeDefinition(OpCode.RMB2, (cpu, addr, value) => cpu.RMB(addr, value, bit: 2), (cpu) => cpu.DecodeZeroPage(), AddressingMode.ZeroPage) },
            { 0x28, new OpCodeDefinition(OpCode.PLP, (cpu, addr, value) => cpu.PLP(addr, value), (cpu) => cpu.DecodeStack(), AddressingMode.Stack) },
            { 0x29, new OpCodeDefinition(OpCode.AND, (cpu, addr, value) => cpu.AND(addr, value), (cpu) => cpu.DecodeImmediate(), AddressingMode.Immediate) },
            { 0x2a, new OpCodeDefinition(OpCode.ROL_A, (cpu, addr, value) => cpu.ROL_A(addr, value), (cpu) => cpu.DecodeAccumulator(), AddressingMode.Accumulator) },
            { 0x2b, new OpCodeDefinition(OpCode.Unknown, (cpu, addr, value) => cpu.IllegalInstruction(addr, value), (cpu) => cpu.DecodeUndefined(1, 1), AddressingMode.Unknown) },
            { 0x2c, new OpCodeDefinition(OpCode.BIT, (cpu, addr, value) => cpu.BIT(addr, value, immediateMode: false), (cpu) => cpu.DecodeAbsolute(), AddressingMode.Absolute) },
            { 0x2d, new OpCodeDefinition(OpCode.AND, (cpu, addr, value) => cpu.AND(addr, value), (cpu) => cpu.DecodeAbsolute(), AddressingMode.Absolute) },
            { 0x2e, new OpCodeDefinition(OpCode.ROL, (cpu, addr, value) => cpu.ROL(addr, value), (cpu) => cpu.DecodeAbsolute(), AddressingMode.Absolute) },
            { 0x2f, new OpCodeDefinition(OpCode.BBR2, (cpu, addr, value) => cpu.BBR(addr, value, bit: 2), (cpu) => cpu.DecodeZeroPage(), AddressingMode.Relative) },

            { 0x30, new OpCodeDefinition(OpCode.BMI, (cpu, addr, value) => cpu.BMI(addr, value), (cpu) => cpu.DecodeRelative(), AddressingMode.Relative) },
            { 0x31, new OpCodeDefinition(OpCode.AND, (cpu, addr, value) => cpu.AND(addr, value), (cpu) => cpu.DecodeIndirectYIndexed(), AddressingMode.IndirectYIndexed) },
            { 0x32, new OpCodeDefinition(OpCode.AND, (cpu, addr, value) => cpu.AND(addr, value), (cpu) => cpu.DecodeZeroPageIndirect(), AddressingMode.ZeroPageIndirect) },
            { 0x33, new OpCodeDefinition(OpCode.Unknown, (cpu, addr, value) => cpu.IllegalInstruction(addr, value), (cpu) => cpu.DecodeUndefined(1, 1), AddressingMode.Unknown) },
            { 0x34, new OpCodeDefinition(OpCode.BIT, (cpu, addr, value) => cpu.BIT(addr, value, immediateMode: false), (cpu) => cpu.DecodeZeroPageXIndexed(), AddressingMode.ZeroPageXIndexed) },
            { 0x35, new OpCodeDefinition(OpCode.AND, (cpu, addr, value) => cpu.AND(addr, value), (cpu) => cpu.DecodeZeroPageXIndexed(), AddressingMode.ZeroPageXIndexed) },
            { 0x36, new OpCodeDefinition(OpCode.ROL, (cpu, addr, value) => cpu.ROL(addr, value), (cpu) => cpu.DecodeZeroPageXIndexed(), AddressingMode.ZeroPageXIndexed) },
            { 0x37, new OpCodeDefinition(OpCode.RMB3, (cpu, addr, value) => cpu.RMB(addr, value, bit: 3), (cpu) => cpu.DecodeZeroPage(), AddressingMode.ZeroPage) },
            { 0x38, new OpCodeDefinition(OpCode.SEC, (cpu, addr, value) => cpu.SEC(addr, value), (cpu) => cpu.DecodeImplicit(), AddressingMode.Implicit) },
            { 0x39, new OpCodeDefinition(OpCode.AND, (cpu, addr, value) => cpu.AND(addr, value), (cpu) => cpu.DecodeAbsoluteYIndexed(), AddressingMode.AbsoluteYIndexed) },
            { 0x3a, new OpCodeDefinition(OpCode.DEA, (cpu, addr, value) => cpu.DEA(addr, value), (cpu) => cpu.DecodeAccumulator(), AddressingMode.Accumulator) },
            { 0x3b, new OpCodeDefinition(OpCode.Unknown, (cpu, addr, value) => cpu.IllegalInstruction(addr, value), (cpu) => cpu.DecodeUndefined(1, 1), AddressingMode.Unknown) },
            { 0x3c, new OpCodeDefinition(OpCode.BIT, (cpu, addr, value) => cpu.BIT(addr, value, immediateMode: false), (cpu) => cpu.DecodeAbsoluteXIndexed(), AddressingMode.AbsoluteXIndexed) },
            { 0x3d, new OpCodeDefinition(OpCode.AND, (cpu, addr, value) => cpu.AND(addr, value), (cpu) => cpu.DecodeAbsoluteXIndexed(), AddressingMode.AbsoluteXIndexed) },
            { 0x3e, new OpCodeDefinition(OpCode.ROL, (cpu, addr, value) => cpu.ROL(addr, value), (cpu) => cpu.DecodeAbsoluteXIndexed(), AddressingMode.AbsoluteXIndexed) },
            { 0x3f, new OpCodeDefinition(OpCode.BBR3, (cpu, addr, value) => cpu.BBR(addr, value, bit: 3), (cpu) => cpu.DecodeZeroPage(), AddressingMode.Relative) },

            { 0x40, new OpCodeDefinition(OpCode.RTI, (cpu, addr, value) => cpu.RTI(addr, value), (cpu) => cpu.DecodeStack(), AddressingMode.Stack) },
            { 0x41, new OpCodeDefinition(OpCode.EOR, (cpu, addr, value) => cpu.EOR(addr, value), (cpu) => cpu.DecodeXIndexedIndirect(), AddressingMode.XIndexedIndirect) },
            { 0x42, new OpCodeDefinition(OpCode.Unknown, (cpu, addr, value) => cpu.IllegalInstruction(addr, value), (cpu) => cpu.DecodeUndefined(2, 2), AddressingMode.Unknown) },
            { 0x43, new OpCodeDefinition(OpCode.Unknown, (cpu, addr, value) => cpu.IllegalInstruction(addr, value), (cpu) => cpu.DecodeUndefined(1, 1), AddressingMode.Unknown) },
            { 0x44, new OpCodeDefinition(OpCode.Unknown, (cpu, addr, value) => cpu.IllegalInstruction(addr, value), (cpu) => cpu.DecodeUndefined(2, 3), AddressingMode.Unknown) },
            { 0x45, new OpCodeDefinition(OpCode.EOR, (cpu, addr, value) => cpu.EOR(addr, value), (cpu) => cpu.DecodeZeroPage(), AddressingMode.ZeroPage) },
            { 0x46, new OpCodeDefinition(OpCode.LSR, (cpu, addr, value) => cpu.LSR(addr, value), (cpu) => cpu.DecodeZeroPage(), AddressingMode.ZeroPage) },
            { 0x47, new OpCodeDefinition(OpCode.RMB4, (cpu, addr, value) => cpu.RMB(addr, value, bit: 4), (cpu) => cpu.DecodeZeroPage(), AddressingMode.ZeroPage) },
            { 0x48, new OpCodeDefinition(OpCode.PHA, (cpu, addr, value) => cpu.PHA(addr, value), (cpu) => cpu.DecodeStack(), AddressingMode.Stack) },
            { 0x49, new OpCodeDefinition(OpCode.EOR, (cpu, addr, value) => cpu.EOR(addr, value), (cpu) => cpu.DecodeImmediate(), AddressingMode.Immediate) },
            { 0x4a, new OpCodeDefinition(OpCode.LSR_A, (cpu, addr, value) => cpu.LSR_A(addr, value), (cpu) => cpu.DecodeAccumulator(), AddressingMode.Accumulator) },
            { 0x4b, new OpCodeDefinition(OpCode.Unknown, (cpu, addr, value) => cpu.IllegalInstruction(addr, value), (cpu) => cpu.DecodeUndefined(1, 1), AddressingMode.Unknown) },
            { 0x4c, new OpCodeDefinition(OpCode.JMP, (cpu, addr, value) => cpu.JMP(addr, value), (cpu) => cpu.DecodeAbsolute(), AddressingMode.Absolute) },
            { 0x4d, new OpCodeDefinition(OpCode.EOR, (cpu, addr, value) => cpu.EOR(addr, value), (cpu) => cpu.DecodeAbsolute(), AddressingMode.Absolute) },
            { 0x4e, new OpCodeDefinition(OpCode.LSR, (cpu, addr, value) => cpu.LSR(addr, value), (cpu) => cpu.DecodeAbsolute(), AddressingMode.Absolute) },
            { 0x4f, new OpCodeDefinition(OpCode.BBR4, (cpu, addr, value) => cpu.BBR(addr, value, bit: 4), (cpu) => cpu.DecodeZeroPage(), AddressingMode.Relative) },

            { 0x50, new OpCodeDefinition(OpCode.BVC, (cpu, addr, value) => cpu.BVC(addr, value), (cpu) => cpu.DecodeRelative(), AddressingMode.Relative) },
            { 0x51, new OpCodeDefinition(OpCode.EOR, (cpu, addr, value) => cpu.EOR(addr, value), (cpu) => cpu.DecodeIndirectYIndexed(), AddressingMode.IndirectYIndexed) },
            { 0x52, new OpCodeDefinition(OpCode.EOR, (cpu, addr, value) => cpu.EOR(addr, value), (cpu) => cpu.DecodeZeroPageIndirect(), AddressingMode.ZeroPageIndirect) },
            { 0x53, new OpCodeDefinition(OpCode.Unknown, (cpu, addr, value) => cpu.IllegalInstruction(addr, value), (cpu) => cpu.DecodeUndefined(1, 1), AddressingMode.Unknown) },
            { 0x54, new OpCodeDefinition(OpCode.Unknown, (cpu, addr, value) => cpu.IllegalInstruction(addr, value), (cpu) => cpu.DecodeUndefined(2, 4), AddressingMode.Unknown) },
            { 0x55, new OpCodeDefinition(OpCode.EOR, (cpu, addr, value) => cpu.EOR(addr, value), (cpu) => cpu.DecodeZeroPageXIndexed(), AddressingMode.ZeroPageXIndexed) },
            { 0x56, new OpCodeDefinition(OpCode.LSR, (cpu, addr, value) => cpu.LSR(addr, value), (cpu) => cpu.DecodeZeroPageXIndexed(), AddressingMode.ZeroPageXIndexed) },
            { 0x57, new OpCodeDefinition(OpCode.RMB5, (cpu, addr, value) => cpu.RMB(addr, value, bit: 5), (cpu) => cpu.DecodeZeroPage(), AddressingMode.ZeroPage) },
            { 0x58, new OpCodeDefinition(OpCode.CLI, (cpu, addr, value) => cpu.CLI(addr, value), (cpu) => cpu.DecodeImplicit(), AddressingMode.Implicit) },
            { 0x59, new OpCodeDefinition(OpCode.EOR, (cpu, addr, value) => cpu.EOR(addr, value), (cpu) => cpu.DecodeAbsoluteYIndexed(), AddressingMode.AbsoluteYIndexed) },
            { 0x5a, new OpCodeDefinition(OpCode.PHY, (cpu, addr, value) => cpu.PHY(addr, value), (cpu) => cpu.DecodeStack(), AddressingMode.Stack) },
            { 0x5b, new OpCodeDefinition(OpCode.Unknown, (cpu, addr, value) => cpu.IllegalInstruction(addr, value), (cpu) => cpu.DecodeUndefined(1, 1), AddressingMode.Unknown) },
            { 0x5c, new OpCodeDefinition(OpCode.Unknown, (cpu, addr, value) => cpu.IllegalInstruction(addr, value), (cpu) => cpu.DecodeUndefined(3, 8), AddressingMode.Unknown) },
            { 0x5d, new OpCodeDefinition(OpCode.EOR, (cpu, addr, value) => cpu.EOR(addr, value), (cpu) => cpu.DecodeAbsoluteXIndexed(), AddressingMode.AbsoluteXIndexed) },
            { 0x5e, new OpCodeDefinition(OpCode.LSR, (cpu, addr, value) => cpu.LSR(addr, value), (cpu) => cpu.DecodeAbsoluteXIndexed(), AddressingMode.AbsoluteXIndexed) },
            { 0x5f, new OpCodeDefinition(OpCode.BBR5, (cpu, addr, value) => cpu.BBR(addr, value, bit: 5), (cpu) => cpu.DecodeZeroPage(), AddressingMode.Relative) },

            { 0x60, new OpCodeDefinition(OpCode.RTS, (cpu, addr, value) => cpu.RTS(addr, value), (cpu) => cpu.DecodeStack(), AddressingMode.Stack) },
            { 0x61, new OpCodeDefinition(OpCode.ADC, (cpu, addr, value) => cpu.ADC_CMOS(addr, value), (cpu) => cpu.DecodeXIndexedIndirect(), AddressingMode.XIndexedIndirect) },
            { 0x62, new OpCodeDefinition(OpCode.Unknown, (cpu, addr, value) => cpu.IllegalInstruction(addr, value), (cpu) => cpu.DecodeUndefined(2, 2), AddressingMode.Unknown) },
            { 0x63, new OpCodeDefinition(OpCode.Unknown, (cpu, addr, value) => cpu.IllegalInstruction(addr, value), (cpu) => cpu.DecodeUndefined(1, 1), AddressingMode.Unknown) },
            { 0x64, new OpCodeDefinition(OpCode.STZ, (cpu, addr, value) => cpu.STZ(addr, value), (cpu) => cpu.DecodeZeroPage(), AddressingMode.ZeroPage) },
            { 0x65, new OpCodeDefinition(OpCode.ADC, (cpu, addr, value) => cpu.ADC_CMOS(addr, value), (cpu) => cpu.DecodeZeroPage(), AddressingMode.ZeroPage) },
            { 0x66, new OpCodeDefinition(OpCode.ROR, (cpu, addr, value) => cpu.ROR(addr, value), (cpu) => cpu.DecodeZeroPage(), AddressingMode.ZeroPage) },
            { 0x67, new OpCodeDefinition(OpCode.RMB6, (cpu, addr, value) => cpu.RMB(addr, value, bit: 6), (cpu) => cpu.DecodeZeroPage(), AddressingMode.ZeroPage) },
            { 0x68, new OpCodeDefinition(OpCode.PLA, (cpu, addr, value) => cpu.PLA(addr, value), (cpu) => cpu.DecodeStack(), AddressingMode.Stack) },
            { 0x69, new OpCodeDefinition(OpCode.ADC, (cpu, addr, value) => cpu.ADC_CMOS(addr, value), (cpu) => cpu.DecodeImmediate(), AddressingMode.Immediate) },
            { 0x6a, new OpCodeDefinition(OpCode.ROR_A, (cpu, addr, value) => cpu.ROR_A(addr, value), (cpu) => cpu.DecodeAccumulator(), AddressingMode.Accumulator) },
            { 0x6b, new OpCodeDefinition(OpCode.Unknown, (cpu, addr, value) => cpu.IllegalInstruction(addr, value), (cpu) => cpu.DecodeUndefined(1, 1), AddressingMode.Unknown) },
            { 0x6c, new OpCodeDefinition(OpCode.JMP, (cpu, addr, value) => cpu.JMP(addr, value), (cpu) => cpu.DecodeAbsoluteIndirect(), AddressingMode.AbsoluteIndirect) },
            { 0x6d, new OpCodeDefinition(OpCode.ADC, (cpu, addr, value) => cpu.ADC_CMOS(addr, value), (cpu) => cpu.DecodeAbsolute(), AddressingMode.Absolute) },
            { 0x6e, new OpCodeDefinition(OpCode.ROR, (cpu, addr, value) => cpu.ROR(addr, value), (cpu) => cpu.DecodeAbsolute(), AddressingMode.Absolute) },
            { 0x6f, new OpCodeDefinition(OpCode.BBR6, (cpu, addr, value) => cpu.BBR(addr, value, bit: 6), (cpu) => cpu.DecodeZeroPage(), AddressingMode.Relative) },

            { 0x70, new OpCodeDefinition(OpCode.BVS, (cpu, addr, value) => cpu.BVS(addr, value), (cpu) => cpu.DecodeRelative(), AddressingMode.Relative) },
            { 0x71, new OpCodeDefinition(OpCode.ADC, (cpu, addr, value) => cpu.ADC_CMOS(addr, value), (cpu) => cpu.DecodeIndirectYIndexed(), AddressingMode.IndirectYIndexed) },
            { 0x72, new OpCodeDefinition(OpCode.ADC, (cpu, addr, value) => cpu.ADC_CMOS(addr, value), (cpu) => cpu.DecodeZeroPageIndirect(), AddressingMode.ZeroPageIndirect) },
            { 0x73, new OpCodeDefinition(OpCode.Unknown, (cpu, addr, value) => cpu.IllegalInstruction(addr, value), (cpu) => cpu.DecodeUndefined(1, 1), AddressingMode.Unknown) },
            { 0x74, new OpCodeDefinition(OpCode.STZ, (cpu, addr, value) => cpu.STZ(addr, value), (cpu) => cpu.DecodeZeroPageXIndexed(), AddressingMode.ZeroPageXIndexed) },
            { 0x75, new OpCodeDefinition(OpCode.ADC, (cpu, addr, value) => cpu.ADC_CMOS(addr, value), (cpu) => cpu.DecodeZeroPageXIndexed(), AddressingMode.ZeroPageXIndexed) },
            { 0x76, new OpCodeDefinition(OpCode.ROR, (cpu, addr, value) => cpu.ROR(addr, value), (cpu) => cpu.DecodeZeroPageXIndexed(), AddressingMode.ZeroPageXIndexed) },
            { 0x77, new OpCodeDefinition(OpCode.RMB7, (cpu, addr, value) => cpu.RMB(addr, value, bit: 7), (cpu) => cpu.DecodeZeroPage(), AddressingMode.ZeroPage) },
            { 0x78, new OpCodeDefinition(OpCode.SEI, (cpu, addr, value) => cpu.SEI(addr, value), (cpu) => cpu.DecodeImplicit(), AddressingMode.Implicit) },
            { 0x79, new OpCodeDefinition(OpCode.ADC, (cpu, addr, value) => cpu.ADC_CMOS(addr, value), (cpu) => cpu.DecodeAbsoluteYIndexed(), AddressingMode.AbsoluteYIndexed) },
            { 0x7a, new OpCodeDefinition(OpCode.PLY, (cpu, addr, value) => cpu.PLY(addr, value), (cpu) => cpu.DecodeStack(), AddressingMode.Stack) },
            { 0x7b, new OpCodeDefinition(OpCode.Unknown, (cpu, addr, value) => cpu.IllegalInstruction(addr, value), (cpu) => cpu.DecodeUndefined(1, 1), AddressingMode.Unknown) },
            { 0x7c, new OpCodeDefinition(OpCode.JMP, (cpu, addr, value) => cpu.JMP(addr, value), (cpu) => cpu.DecodeAbsoluteIndexedIndirect(), AddressingMode.AbsoluteIndexedIndirect) },
            { 0x7d, new OpCodeDefinition(OpCode.ADC, (cpu, addr, value) => cpu.ADC_CMOS(addr, value), (cpu) => cpu.DecodeAbsoluteXIndexed(), AddressingMode.AbsoluteXIndexed) },
            { 0x7e, new OpCodeDefinition(OpCode.ROR, (cpu, addr, value) => cpu.ROR(addr, value), (cpu) => cpu.DecodeAbsoluteXIndexed(), AddressingMode.AbsoluteXIndexed) },
            { 0x7f, new OpCodeDefinition(OpCode.BBR7, (cpu, addr, value) => cpu.BBR(addr, value, bit: 7), (cpu) => cpu.DecodeZeroPage(), AddressingMode.Relative) },

            { 0x80, new OpCodeDefinition(OpCode.BRA, (cpu, addr, value) => cpu.BRA(addr, value), (cpu) => cpu.DecodeRelative(), AddressingMode.Relative) },
            { 0x81, new OpCodeDefinition(OpCode.STA, (cpu, addr, value) => cpu.STA(addr, value), (cpu) => cpu.DecodeXIndexedIndirect(), AddressingMode.XIndexedIndirect) },
            { 0x82, new OpCodeDefinition(OpCode.Unknown, (cpu, addr, value) => cpu.IllegalInstruction(addr, value), (cpu) => cpu.DecodeUndefined(2, 2), AddressingMode.Unknown) },
            { 0x83, new OpCodeDefinition(OpCode.Unknown, (cpu, addr, value) => cpu.IllegalInstruction(addr, value), (cpu) => cpu.DecodeUndefined(1, 1), AddressingMode.Unknown) },
            { 0x84, new OpCodeDefinition(OpCode.STY, (cpu, addr, value) => cpu.STY(addr, value), (cpu) => cpu.DecodeZeroPage(), AddressingMode.ZeroPage) },
            { 0x85, new OpCodeDefinition(OpCode.STA, (cpu, addr, value) => cpu.STA(addr, value), (cpu) => cpu.DecodeZeroPage(), AddressingMode.ZeroPage) },
            { 0x86, new OpCodeDefinition(OpCode.STX, (cpu, addr, value) => cpu.STX(addr, value), (cpu) => cpu.DecodeZeroPage(), AddressingMode.ZeroPage) },
            { 0x87, new OpCodeDefinition(OpCode.SMB0, (cpu, addr, value) => cpu.SMB(addr, value, bit: 0), (cpu) => cpu.DecodeZeroPage(), AddressingMode.ZeroPage) },
            { 0x88, new OpCodeDefinition(OpCode.DEY, (cpu, addr, value) => cpu.DEY(addr, value), (cpu) => cpu.DecodeImplicit(), AddressingMode.Implicit) },
            { 0x89, new OpCodeDefinition(OpCode.BIT, (cpu, addr, value) => cpu.BIT(addr, value, immediateMode: true), (cpu) => cpu.DecodeImmediate(), AddressingMode.Immediate) },
            { 0x8a, new OpCodeDefinition(OpCode.TXA, (cpu, addr, value) => cpu.TXA(addr, value), (cpu) => cpu.DecodeImplicit(), AddressingMode.Implicit) },
            { 0x8b, new OpCodeDefinition(OpCode.Unknown, (cpu, addr, value) => cpu.IllegalInstruction(addr, value), (cpu) => cpu.DecodeUndefined(1, 1), AddressingMode.Unknown) },
            { 0x8c, new OpCodeDefinition(OpCode.STY, (cpu, addr, value) => cpu.STY(addr, value), (cpu) => cpu.DecodeAbsolute(), AddressingMode.Absolute) },
            { 0x8d, new OpCodeDefinition(OpCode.STA, (cpu, addr, value) => cpu.STA(addr, value), (cpu) => cpu.DecodeAbsolute(), AddressingMode.Absolute) },
            { 0x8e, new OpCodeDefinition(OpCode.STX, (cpu, addr, value) => cpu.STX(addr, value), (cpu) => cpu.DecodeAbsolute(), AddressingMode.Absolute) },
            { 0x8f, new OpCodeDefinition(OpCode.BBS0, (cpu, addr, value) => cpu.BBS(addr, value, bit: 0), (cpu) => cpu.DecodeZeroPage(), AddressingMode.Relative) },

            { 0x90, new OpCodeDefinition(OpCode.BCC, (cpu, addr, value) => cpu.BCC(addr, value), (cpu) => cpu.DecodeRelative(), AddressingMode.Relative) },
            { 0x91, new OpCodeDefinition(OpCode.STA, (cpu, addr, value) => cpu.STA(addr, value), (cpu) => cpu.DecodeIndirectYIndexed(), AddressingMode.IndirectYIndexed) },
            { 0x92, new OpCodeDefinition(OpCode.STA, (cpu, addr, value) => cpu.STA(addr, value), (cpu) => cpu.DecodeZeroPageIndirect(), AddressingMode.ZeroPageIndirect) },
            { 0x93, new OpCodeDefinition(OpCode.Unknown, (cpu, addr, value) => cpu.IllegalInstruction(addr, value), (cpu) => cpu.DecodeUndefined(1, 1), AddressingMode.Unknown) },
            { 0x94, new OpCodeDefinition(OpCode.STY, (cpu, addr, value) => cpu.STY(addr, value), (cpu) => cpu.DecodeZeroPageXIndexed(), AddressingMode.ZeroPageXIndexed) },
            { 0x95, new OpCodeDefinition(OpCode.STA, (cpu, addr, value) => cpu.STA(addr, value), (cpu) => cpu.DecodeZeroPageXIndexed(), AddressingMode.ZeroPageXIndexed) },
            { 0x96, new OpCodeDefinition(OpCode.STX, (cpu, addr, value) => cpu.STX(addr, value), (cpu) => cpu.DecodeZeroPageYIndexed(), AddressingMode.ZeroPageYIndexed) },
            { 0x97, new OpCodeDefinition(OpCode.SMB1, (cpu, addr, value) => cpu.SMB(addr, value, bit: 1), (cpu) => cpu.DecodeZeroPage(), AddressingMode.ZeroPage) },
            { 0x98, new OpCodeDefinition(OpCode.TYA, (cpu, addr, value) => cpu.TYA(addr, value), (cpu) => cpu.DecodeImplicit(), AddressingMode.Implicit) },
            { 0x99, new OpCodeDefinition(OpCode.STA, (cpu, addr, value) => cpu.STA(addr, value), (cpu) => cpu.DecodeAbsoluteYIndexed(), AddressingMode.AbsoluteYIndexed) },
            { 0x9a, new OpCodeDefinition(OpCode.TXS, (cpu, addr, value) => cpu.TXS(addr, value), (cpu) => cpu.DecodeImplicit(), AddressingMode.Implicit) },
            { 0x9b, new OpCodeDefinition(OpCode.Unknown, (cpu, addr, value) => cpu.IllegalInstruction(addr, value), (cpu) => cpu.DecodeUndefined(1, 1), AddressingMode.Unknown) },
            { 0x9c, new OpCodeDefinition(OpCode.STZ, (cpu, addr, value) => cpu.STZ(addr, value), (cpu) => cpu.DecodeAbsolute(), AddressingMode.Absolute) },
            { 0x9d, new OpCodeDefinition(OpCode.STA, (cpu, addr, value) => cpu.STA(addr, value), (cpu) => cpu.DecodeAbsoluteXIndexed(), AddressingMode.AbsoluteXIndexed) },
            { 0x9e, new OpCodeDefinition(OpCode.STZ, (cpu, addr, value) => cpu.STZ(addr, value), (cpu) => cpu.DecodeAbsoluteXIndexed(), AddressingMode.AbsoluteXIndexed) },
            { 0x9f, new OpCodeDefinition(OpCode.BBS1, (cpu, addr, value) => cpu.BBS(addr, value, bit: 1), (cpu) => cpu.DecodeZeroPage(), AddressingMode.Relative) },

            { 0xa0, new OpCodeDefinition(OpCode.LDY, (cpu, addr, value) => cpu.LDY(addr, value), (cpu) => cpu.DecodeImmediate(), AddressingMode.Immediate) },
            { 0xa1, new OpCodeDefinition(OpCode.LDA, (cpu, addr, value) => cpu.LDA(addr, value), (cpu) => cpu.DecodeXIndexedIndirect(), AddressingMode.XIndexedIndirect) },
            { 0xa2, new OpCodeDefinition(OpCode.LDX, (cpu, addr, value) => cpu.LDX(addr, value), (cpu) => cpu.DecodeImmediate(), AddressingMode.Immediate) },
            { 0xa3, new OpCodeDefinition(OpCode.Unknown, (cpu, addr, value) => cpu.IllegalInstruction(addr, value), (cpu) => cpu.DecodeUndefined(1, 1), AddressingMode.Unknown) },
            { 0xa4, new OpCodeDefinition(OpCode.LDY, (cpu, addr, value) => cpu.LDY(addr, value), (cpu) => cpu.DecodeZeroPage(), AddressingMode.ZeroPage) },
            { 0xa5, new OpCodeDefinition(OpCode.LDA, (cpu, addr, value) => cpu.LDA(addr, value), (cpu) => cpu.DecodeZeroPage(), AddressingMode.ZeroPage) },
            { 0xa6, new OpCodeDefinition(OpCode.LDX, (cpu, addr, value) => cpu.LDX(addr, value), (cpu) => cpu.DecodeZeroPage(), AddressingMode.ZeroPage) },
            { 0xa7, new OpCodeDefinition(OpCode.SMB2, (cpu, addr, value) => cpu.SMB(addr, value, bit: 2), (cpu) => cpu.DecodeZeroPage(), AddressingMode.ZeroPage) },
            { 0xa8, new OpCodeDefinition(OpCode.TAY, (cpu, addr, value) => cpu.TAY(addr, value), (cpu) => cpu.DecodeImplicit(), AddressingMode.Implicit) },
            { 0xa9, new OpCodeDefinition(OpCode.LDA, (cpu, addr, value) => cpu.LDA(addr, value), (cpu) => cpu.DecodeImmediate(), AddressingMode.Immediate) },
            { 0xaa, new OpCodeDefinition(OpCode.TAX, (cpu, addr, value) => cpu.TAX(addr, value), (cpu) => cpu.DecodeImplicit(), AddressingMode.Implicit) },
            { 0xab, new OpCodeDefinition(OpCode.Unknown, (cpu, addr, value) => cpu.IllegalInstruction(addr, value), (cpu) => cpu.DecodeUndefined(1, 1), AddressingMode.Unknown) },
            { 0xac, new OpCodeDefinition(OpCode.LDY, (cpu, addr, value) => cpu.LDY(addr, value), (cpu) => cpu.DecodeAbsolute(), AddressingMode.Absolute) },
            { 0xad, new OpCodeDefinition(OpCode.LDA, (cpu, addr, value) => cpu.LDA(addr, value), (cpu) => cpu.DecodeAbsolute(), AddressingMode.Absolute) },
            { 0xae, new OpCodeDefinition(OpCode.LDX, (cpu, addr, value) => cpu.LDX(addr, value), (cpu) => cpu.DecodeAbsolute(), AddressingMode.Absolute) },
            { 0xaf, new OpCodeDefinition(OpCode.BBS2, (cpu, addr, value) => cpu.BBS(addr, value, bit: 2), (cpu) => cpu.DecodeZeroPage(), AddressingMode.Relative) },

            { 0xb0, new OpCodeDefinition(OpCode.BCS, (cpu, addr, value) => cpu.BCS(addr, value), (cpu) => cpu.DecodeRelative(), AddressingMode.Relative) },
            { 0xb1, new OpCodeDefinition(OpCode.LDA, (cpu, addr, value) => cpu.LDA(addr, value), (cpu) => cpu.DecodeIndirectYIndexed(), AddressingMode.IndirectYIndexed) },
            { 0xb2, new OpCodeDefinition(OpCode.LDA, (cpu, addr, value) => cpu.LDA(addr, value), (cpu) => cpu.DecodeZeroPageIndirect(), AddressingMode.ZeroPageIndirect) },
            { 0xb3, new OpCodeDefinition(OpCode.Unknown, (cpu, addr, value) => cpu.IllegalInstruction(addr, value), (cpu) => cpu.DecodeUndefined(1, 1), AddressingMode.Unknown) },
            { 0xb4, new OpCodeDefinition(OpCode.LDY, (cpu, addr, value) => cpu.LDY(addr, value), (cpu) => cpu.DecodeZeroPageXIndexed(), AddressingMode.ZeroPageXIndexed) },
            { 0xb5, new OpCodeDefinition(OpCode.LDA, (cpu, addr, value) => cpu.LDA(addr, value), (cpu) => cpu.DecodeZeroPageXIndexed(), AddressingMode.ZeroPageXIndexed) },
            { 0xb6, new OpCodeDefinition(OpCode.LDX, (cpu, addr, value) => cpu.LDX(addr, value), (cpu) => cpu.DecodeZeroPageYIndexed(), AddressingMode.ZeroPageYIndexed) },
            { 0xb7, new OpCodeDefinition(OpCode.SMB3, (cpu, addr, value) => cpu.SMB(addr, value, bit: 3), (cpu) => cpu.DecodeZeroPage(), AddressingMode.ZeroPage) },
            { 0xb8, new OpCodeDefinition(OpCode.CLV, (cpu, addr, value) => cpu.CLV(addr, value), (cpu) => cpu.DecodeImplicit(), AddressingMode.Implicit) },
            { 0xb9, new OpCodeDefinition(OpCode.LDA, (cpu, addr, value) => cpu.LDA(addr, value), (cpu) => cpu.DecodeAbsoluteYIndexed(), AddressingMode.AbsoluteYIndexed) },
            { 0xba, new OpCodeDefinition(OpCode.TSX, (cpu, addr, value) => cpu.TSX(addr, value), (cpu) => cpu.DecodeImplicit(), AddressingMode.Implicit) },
            { 0xbb, new OpCodeDefinition(OpCode.Unknown, (cpu, addr, value) => cpu.IllegalInstruction(addr, value), (cpu) => cpu.DecodeUndefined(1, 1), AddressingMode.Unknown) },
            { 0xbc, new OpCodeDefinition(OpCode.LDY, (cpu, addr, value) => cpu.LDY(addr, value), (cpu) => cpu.DecodeAbsoluteXIndexed(), AddressingMode.AbsoluteXIndexed) },
            { 0xbd, new OpCodeDefinition(OpCode.LDA, (cpu, addr, value) => cpu.LDA(addr, value), (cpu) => cpu.DecodeAbsoluteXIndexed(), AddressingMode.AbsoluteXIndexed) },
            { 0xbe, new OpCodeDefinition(OpCode.LDX, (cpu, addr, value) => cpu.LDX(addr, value), (cpu) => cpu.DecodeAbsoluteYIndexed(), AddressingMode.AbsoluteYIndexed) },
            { 0xbf, new OpCodeDefinition(OpCode.BBS3, (cpu, addr, value) => cpu.BBS(addr, value, bit: 3), (cpu) => cpu.DecodeZeroPage(), AddressingMode.Relative) },

            { 0xc0, new OpCodeDefinition(OpCode.CPY, (cpu, addr, value) => cpu.CPY(addr, value), (cpu) => cpu.DecodeImmediate(), AddressingMode.Immediate) },
            { 0xc1, new OpCodeDefinition(OpCode.CMP, (cpu, addr, value) => cpu.CMP(addr, value), (cpu) => cpu.DecodeXIndexedIndirect(), AddressingMode.XIndexedIndirect) },
            { 0xc2, new OpCodeDefinition(OpCode.Unknown, (cpu, addr, value) => cpu.IllegalInstruction(addr, value), (cpu) => cpu.DecodeUndefined(2, 2), AddressingMode.Unknown) },
            { 0xc3, new OpCodeDefinition(OpCode.Unknown, (cpu, addr, value) => cpu.IllegalInstruction(addr, value), (cpu) => cpu.DecodeUndefined(1, 1), AddressingMode.Unknown) },
            { 0xc4, new OpCodeDefinition(OpCode.CPY, (cpu, addr, value) => cpu.CPY(addr, value), (cpu) => cpu.DecodeZeroPage(), AddressingMode.ZeroPage) },
            { 0xc5, new OpCodeDefinition(OpCode.CMP, (cpu, addr, value) => cpu.CMP(addr, value), (cpu) => cpu.DecodeZeroPage(), AddressingMode.ZeroPage) },
            { 0xc6, new OpCodeDefinition(OpCode.DEC, (cpu, addr, value) => cpu.DEC(addr, value), (cpu) => cpu.DecodeZeroPage(), AddressingMode.ZeroPage) },
            { 0xc7, new OpCodeDefinition(OpCode.SMB4, (cpu, addr, value) => cpu.SMB(addr, value, bit: 4), (cpu) => cpu.DecodeZeroPage(), AddressingMode.ZeroPage) },
            { 0xc8, new OpCodeDefinition(OpCode.INY, (cpu, addr, value) => cpu.INY(addr, value), (cpu) => cpu.DecodeImplicit(), AddressingMode.Implicit) },
            { 0xc9, new OpCodeDefinition(OpCode.CMP, (cpu, addr, value) => cpu.CMP(addr, value), (cpu) => cpu.DecodeImmediate(), AddressingMode.Immediate) },
            { 0xca, new OpCodeDefinition(OpCode.DEX, (cpu, addr, value) => cpu.DEX(addr, value), (cpu) => cpu.DecodeImplicit(), AddressingMode.Implicit) },
            { 0xcb, new OpCodeDefinition(OpCode.WAI, (cpu, addr, value) => cpu.WAI(addr, value), (cpu) => cpu.DecodeImplicit(), AddressingMode.Implicit) },
            { 0xcc, new OpCodeDefinition(OpCode.CPY, (cpu, addr, value) => cpu.CPY(addr, value), (cpu) => cpu.DecodeAbsolute(), AddressingMode.Absolute) },
            { 0xcd, new OpCodeDefinition(OpCode.CMP, (cpu, addr, value) => cpu.CMP(addr, value), (cpu) => cpu.DecodeAbsolute(), AddressingMode.Absolute) },
            { 0xce, new OpCodeDefinition(OpCode.DEC, (cpu, addr, value) => cpu.DEC(addr, value), (cpu) => cpu.DecodeAbsolute(), AddressingMode.Absolute) },
            { 0xcf, new OpCodeDefinition(OpCode.BBS4, (cpu, addr, value) => cpu.BBS(addr, value, bit: 4), (cpu) => cpu.DecodeZeroPage(), AddressingMode.Relative) },

            { 0xd0, new OpCodeDefinition(OpCode.BNE, (cpu, addr, value) => cpu.BNE(addr, value), (cpu) => cpu.DecodeRelative(), AddressingMode.Relative) },
            { 0xd1, new OpCodeDefinition(OpCode.CMP, (cpu, addr, value) => cpu.CMP(addr, value), (cpu) => cpu.DecodeIndirectYIndexed(), AddressingMode.IndirectYIndexed) },
            { 0xd2, new OpCodeDefinition(OpCode.CMP, (cpu, addr, value) => cpu.CMP(addr, value), (cpu) => cpu.DecodeZeroPageIndirect(), AddressingMode.ZeroPageIndirect) },
            { 0xd3, new OpCodeDefinition(OpCode.Unknown, (cpu, addr, value) => cpu.IllegalInstruction(addr, value), (cpu) => cpu.DecodeUndefined(1, 1), AddressingMode.Unknown) },
            { 0xd4, new OpCodeDefinition(OpCode.Unknown, (cpu, addr, value) => cpu.IllegalInstruction(addr, value), (cpu) => cpu.DecodeUndefined(2,4 ), AddressingMode.Unknown) },
            { 0xd5, new OpCodeDefinition(OpCode.CMP, (cpu, addr, value) => cpu.CMP(addr, value), (cpu) => cpu.DecodeZeroPageXIndexed(), AddressingMode.ZeroPageXIndexed) },
            { 0xd6, new OpCodeDefinition(OpCode.DEC, (cpu, addr, value) => cpu.DEC(addr, value), (cpu) => cpu.DecodeZeroPageXIndexed(), AddressingMode.ZeroPageXIndexed) },
            { 0xd7, new OpCodeDefinition(OpCode.SMB5, (cpu, addr, value) => cpu.SMB(addr, value, bit: 5), (cpu) => cpu.DecodeZeroPage(), AddressingMode.ZeroPage) },
            { 0xd8, new OpCodeDefinition(OpCode.CLD, (cpu, addr, value) => cpu.CLD(addr, value), (cpu) => cpu.DecodeImplicit(), AddressingMode.Implicit) },
            { 0xd9, new OpCodeDefinition(OpCode.CMP, (cpu, addr, value) => cpu.CMP(addr, value), (cpu) => cpu.DecodeAbsoluteYIndexed(), AddressingMode.AbsoluteYIndexed) },
            { 0xda, new OpCodeDefinition(OpCode.PHX, (cpu, addr, value) => cpu.PHX(addr, value), (cpu) => cpu.DecodeStack(), AddressingMode.Stack) },
            { 0xdb, new OpCodeDefinition(OpCode.STP, (cpu, addr, value) => cpu.STP(addr, value), (cpu) => cpu.DecodeImplicit(), AddressingMode.Implicit) },
            { 0xdc, new OpCodeDefinition(OpCode.Unknown, (cpu, addr, value) => cpu.IllegalInstruction(addr, value), (cpu) => cpu.DecodeUndefined(3, 4), AddressingMode.Unknown) },
            { 0xdd, new OpCodeDefinition(OpCode.CMP, (cpu, addr, value) => cpu.CMP(addr, value), (cpu) => cpu.DecodeAbsoluteXIndexed(), AddressingMode.AbsoluteXIndexed) },
            { 0xde, new OpCodeDefinition(OpCode.DEC, (cpu, addr, value) => cpu.DEC(addr, value), (cpu) => cpu.DecodeAbsoluteXIndexed(), AddressingMode.AbsoluteXIndexed) },
            { 0xdf, new OpCodeDefinition(OpCode.BBS5, (cpu, addr, value) => cpu.BBS(addr, value, bit: 5), (cpu) => cpu.DecodeZeroPage(), AddressingMode.Relative) },

            { 0xe0, new OpCodeDefinition(OpCode.CPX, (cpu, addr, value) => cpu.CPX(addr, value), (cpu) => cpu.DecodeImmediate(), AddressingMode.Immediate) },
            { 0xe1, new OpCodeDefinition(OpCode.SBC, (cpu, addr, value) => cpu.SBC_CMOS(addr, value), (cpu) => cpu.DecodeXIndexedIndirect(), AddressingMode.XIndexedIndirect) },
            { 0xe2, new OpCodeDefinition(OpCode.Unknown, (cpu, addr, value) => cpu.IllegalInstruction(addr, value), (cpu) => cpu.DecodeUndefined(2, 2), AddressingMode.Unknown) },
            { 0xe3, new OpCodeDefinition(OpCode.Unknown, (cpu, addr, value) => cpu.IllegalInstruction(addr, value), (cpu) => cpu.DecodeUndefined(1, 1), AddressingMode.Unknown) },
            { 0xe4, new OpCodeDefinition(OpCode.CPX, (cpu, addr, value) => cpu.CPX(addr, value), (cpu) => cpu.DecodeZeroPage(), AddressingMode.ZeroPage) },
            { 0xe5, new OpCodeDefinition(OpCode.SBC, (cpu, addr, value) => cpu.SBC_CMOS(addr, value), (cpu) => cpu.DecodeZeroPage(), AddressingMode.ZeroPage) },
            { 0xe6, new OpCodeDefinition(OpCode.INC, (cpu, addr, value) => cpu.INC(addr, value), (cpu) => cpu.DecodeZeroPage(), AddressingMode.ZeroPage) },
            { 0xe7, new OpCodeDefinition(OpCode.SMB6, (cpu, addr, value) => cpu.SMB(addr, value, bit: 6), (cpu) => cpu.DecodeZeroPage(), AddressingMode.ZeroPage) },
            { 0xe8, new OpCodeDefinition(OpCode.INX, (cpu, addr, value) => cpu.INX(addr, value), (cpu) => cpu.DecodeImplicit(), AddressingMode.Implicit) },
            { 0xe9, new OpCodeDefinition(OpCode.SBC, (cpu, addr, value) => cpu.SBC_CMOS(addr, value), (cpu) => cpu.DecodeImmediate(), AddressingMode.Immediate) },
            { 0xea, new OpCodeDefinition(OpCode.NOP, (cpu, addr, value) => cpu.NOP(addr, value), (cpu) => cpu.DecodeImplicit(), AddressingMode.Implicit) },
            { 0xeb, new OpCodeDefinition(OpCode.Unknown, (cpu, addr, value) => cpu.IllegalInstruction(addr, value), (cpu) => cpu.DecodeUndefined(1, 1), AddressingMode.Unknown) },
            { 0xec, new OpCodeDefinition(OpCode.CPX, (cpu, addr, value) => cpu.CPX(addr, value), (cpu) => cpu.DecodeAbsolute(), AddressingMode.Absolute) },
            { 0xed, new OpCodeDefinition(OpCode.SBC, (cpu, addr, value) => cpu.SBC_CMOS(addr, value), (cpu) => cpu.DecodeAbsolute(), AddressingMode.Absolute) },
            { 0xee, new OpCodeDefinition(OpCode.INC, (cpu, addr, value) => cpu.INC(addr, value), (cpu) => cpu.DecodeAbsolute(), AddressingMode.Absolute) },
            { 0xef, new OpCodeDefinition(OpCode.BBS6, (cpu, addr, value) => cpu.BBS(addr, value, bit: 6), (cpu) => cpu.DecodeZeroPage(), AddressingMode.Relative) },

            { 0xf0, new OpCodeDefinition(OpCode.BEQ, (cpu, addr, value) => cpu.BEQ(addr, value), (cpu) => cpu.DecodeRelative(), AddressingMode.Relative) },
            { 0xf1, new OpCodeDefinition(OpCode.SBC, (cpu, addr, value) => cpu.SBC_CMOS(addr, value), (cpu) => cpu.DecodeIndirectYIndexed(), AddressingMode.IndirectYIndexed) },
            { 0xf2, new OpCodeDefinition(OpCode.SBC, (cpu, addr, value) => cpu.SBC_CMOS(addr, value), (cpu) => cpu.DecodeZeroPageIndirect(), AddressingMode.ZeroPageIndirect) },
            { 0xf3, new OpCodeDefinition(OpCode.Unknown, (cpu, addr, value) => cpu.IllegalInstruction(addr, value), (cpu) => cpu.DecodeUndefined(1,1), AddressingMode.Unknown) },
            { 0xf4, new OpCodeDefinition(OpCode.Unknown, (cpu, addr, value) => cpu.IllegalInstruction(addr, value), (cpu) => cpu.DecodeUndefined(2, 4), AddressingMode.Unknown) },
            { 0xf5, new OpCodeDefinition(OpCode.SBC, (cpu, addr, value) => cpu.SBC_CMOS(addr, value), (cpu) => cpu.DecodeZeroPageXIndexed(), AddressingMode.ZeroPageXIndexed) },
            { 0xf6, new OpCodeDefinition(OpCode.INC, (cpu, addr, value) => cpu.INC(addr, value), (cpu) => cpu.DecodeZeroPageXIndexed(), AddressingMode.ZeroPageXIndexed) },
            { 0xf7, new OpCodeDefinition(OpCode.SMB7, (cpu, addr, value) => cpu.SMB(addr, value, bit: 7), (cpu) => cpu.DecodeZeroPage(), AddressingMode.ZeroPage) },
            { 0xf8, new OpCodeDefinition(OpCode.SED, (cpu, addr, value) => cpu.SED(addr, value), (cpu) => cpu.DecodeImplicit(), AddressingMode.Implicit) },
            { 0xf9, new OpCodeDefinition(OpCode.SBC, (cpu, addr, value) => cpu.SBC_CMOS(addr, value), (cpu) => cpu.DecodeAbsoluteYIndexed(), AddressingMode.AbsoluteYIndexed) },
            { 0xfa, new OpCodeDefinition(OpCode.PLX, (cpu, addr, value) => cpu.PLX(addr, value), (cpu) => cpu.DecodeImplicit(), AddressingMode.Stack) },
            { 0xfb, new OpCodeDefinition(OpCode.Unknown, (cpu, addr, value) => cpu.IllegalInstruction(addr, value), (cpu) => cpu.DecodeUndefined(1, 1), AddressingMode.Unknown) },
            { 0xfc, new OpCodeDefinition(OpCode.Unknown, (cpu, addr, value) => cpu.IllegalInstruction(addr, value), (cpu) => cpu.DecodeUndefined(3, 4), AddressingMode.Unknown) },
            { 0xfd, new OpCodeDefinition(OpCode.SBC, (cpu, addr, value) => cpu.SBC_CMOS(addr, value), (cpu) => cpu.DecodeAbsoluteXIndexed(), AddressingMode.AbsoluteXIndexed) },
            { 0xfe, new OpCodeDefinition(OpCode.INC, (cpu, addr, value) => cpu.INC(addr, value), (cpu) => cpu.DecodeAbsoluteXIndexed(), AddressingMode.AbsoluteXIndexed) },
            { 0xff, new OpCodeDefinition(OpCode.BBS7, (cpu, addr, value) => cpu.BBS(addr, value, bit: 7), (cpu) => cpu.DecodeZeroPage(), AddressingMode.Relative) },
        };

        public static readonly Dictionary<byte, OpCodeDefinition> OpCode6502 = new()
        {
            { 0x00, new OpCodeDefinition(OpCode.BRK, (cpu, addr, value) => cpu.BRK(addr, value), (cpu) => cpu.DecodeStack(), AddressingMode.Stack) },
            { 0x01, new OpCodeDefinition(OpCode.ORA, (cpu, addr, value) => cpu.ORA(addr, value), (cpu) => cpu.DecodeXIndexedIndirect(), AddressingMode.XIndexedIndirect) },
            { 0x02, new OpCodeDefinition(OpCode.Unknown, (cpu, addr, value) => cpu.IllegalInstruction(addr, value), (cpu) => cpu.DecodeUndefined(0, 0), AddressingMode.Unknown) },
            { 0x03, new OpCodeDefinition(OpCode.Unknown, (cpu, addr, value) => cpu.IllegalInstruction(addr, value), (cpu) => cpu.DecodeUndefined(2, 8), AddressingMode.Unknown) },
            { 0x04, new OpCodeDefinition(OpCode.Unknown, (cpu, addr, value) => cpu.IllegalInstruction(addr, value), (cpu) => cpu.DecodeUndefined(2, 3), AddressingMode.Unknown) },
            { 0x05, new OpCodeDefinition(OpCode.ORA, (cpu, addr, value) => cpu.ORA(addr, value), (cpu) => cpu.DecodeZeroPage(), AddressingMode.ZeroPage) },
            { 0x06, new OpCodeDefinition(OpCode.ASL, (cpu, addr, value) => cpu.ASL(addr, value), (cpu) => cpu.DecodeZeroPage(), AddressingMode.ZeroPage) },
            { 0x07, new OpCodeDefinition(OpCode.Unknown, (cpu, addr, value) => cpu.IllegalInstruction(addr, value), (cpu) => cpu.DecodeUndefined(2, 5), AddressingMode.Unknown) },
            { 0x08, new OpCodeDefinition(OpCode.PHP, (cpu, addr, value) => cpu.PHP(addr, value), (cpu) => cpu.DecodeStack(), AddressingMode.Stack) },
            { 0x09, new OpCodeDefinition(OpCode.ORA, (cpu, addr, value) => cpu.ORA(addr, value), (cpu) => cpu.DecodeImmediate(), AddressingMode.Immediate) },
            { 0x0a, new OpCodeDefinition(OpCode.ASL_A, (cpu, addr, value) => cpu.ASL_A(addr, value), (cpu) => cpu.DecodeAccumulator(), AddressingMode.Accumulator) },
            { 0x0b, new OpCodeDefinition(OpCode.Unknown, (cpu, addr, value) => cpu.IllegalInstruction(addr, value), (cpu) => cpu.DecodeUndefined(2, 2), AddressingMode.Unknown) },
            { 0x0c, new OpCodeDefinition(OpCode.Unknown, (cpu, addr, value) => cpu.IllegalInstruction(addr, value), (cpu) => cpu.DecodeUndefined(3, 4), AddressingMode.Unknown) },
            { 0x0d, new OpCodeDefinition(OpCode.ORA, (cpu, addr, value) => cpu.ORA(addr, value), (cpu) => cpu.DecodeAbsolute(), AddressingMode.Absolute) },
            { 0x0e, new OpCodeDefinition(OpCode.ASL, (cpu, addr, value) => cpu.ASL(addr, value), (cpu) => cpu.DecodeAbsolute(), AddressingMode.Absolute) },
            { 0x0f, new OpCodeDefinition(OpCode.Unknown, (cpu, addr, value) => cpu.IllegalInstruction(addr, value), (cpu) => cpu.DecodeUndefined(3, 6), AddressingMode.Unknown) },

            { 0x10, new OpCodeDefinition(OpCode.BPL, (cpu, addr, value) => cpu.BPL(addr, value), (cpu) => cpu.DecodeRelative(), AddressingMode.Relative) },
            { 0x11, new OpCodeDefinition(OpCode.ORA, (cpu, addr, value) => cpu.ORA(addr, value), (cpu) => cpu.DecodeIndirectYIndexed(), AddressingMode.IndirectYIndexed) },
            { 0x12, new OpCodeDefinition(OpCode.Unknown, (cpu, addr, value) => cpu.IllegalInstruction(addr, value), (cpu) => cpu.DecodeUndefined(0, 0), AddressingMode.Unknown) },
            { 0x13, new OpCodeDefinition(OpCode.Unknown, (cpu, addr, value) => cpu.IllegalInstruction(addr, value), (cpu) => cpu.DecodeUndefined(2, 8), AddressingMode.Unknown) },
            { 0x14, new OpCodeDefinition(OpCode.Unknown, (cpu, addr, value) => cpu.IllegalInstruction(addr, value), (cpu) => cpu.DecodeUndefined(2, 4), AddressingMode.Unknown) },
            { 0x15, new OpCodeDefinition(OpCode.ORA, (cpu, addr, value) => cpu.ORA(addr, value), (cpu) => cpu.DecodeZeroPageXIndexed(), AddressingMode.ZeroPageXIndexed) },
            { 0x16, new OpCodeDefinition(OpCode.ASL, (cpu, addr, value) => cpu.ASL(addr, value), (cpu) => cpu.DecodeZeroPageXIndexed(), AddressingMode.ZeroPageXIndexed) },
            { 0x17, new OpCodeDefinition(OpCode.Unknown, (cpu, addr, value) => cpu.IllegalInstruction(addr, value), (cpu) => cpu.DecodeUndefined(2, 6), AddressingMode.Unknown) },
            { 0x18, new OpCodeDefinition(OpCode.CLC, (cpu, addr, value) => cpu.CLC(addr, value), (cpu) => cpu.DecodeImplicit(), AddressingMode.Implicit) },
            { 0x19, new OpCodeDefinition(OpCode.ORA, (cpu, addr, value) => cpu.ORA(addr, value), (cpu) => cpu.DecodeAbsoluteYIndexed(), AddressingMode.AbsoluteYIndexed) },
            { 0x1a, new OpCodeDefinition(OpCode.Unknown, (cpu, addr, value) => cpu.IllegalInstruction(addr, value), (cpu) => cpu.DecodeUndefined(1, 2), AddressingMode.Unknown) },
            { 0x1b, new OpCodeDefinition(OpCode.Unknown, (cpu, addr, value) => cpu.IllegalInstruction(addr, value), (cpu) => cpu.DecodeUndefined(3, 7), AddressingMode.Unknown) },
            { 0x1c, new OpCodeDefinition(OpCode.Unknown, (cpu, addr, value) => cpu.IllegalInstruction(addr, value), (cpu) => cpu.DecodeUndefined(3, 4), AddressingMode.Unknown) },
            { 0x1d, new OpCodeDefinition(OpCode.ORA, (cpu, addr, value) => cpu.ORA(addr, value), (cpu) => cpu.DecodeAbsoluteXIndexed(), AddressingMode.AbsoluteXIndexed) },
            { 0x1e, new OpCodeDefinition(OpCode.ASL, (cpu, addr, value) => cpu.ASL(addr, value), (cpu) => cpu.DecodeAbsoluteXIndexed(), AddressingMode.AbsoluteXIndexed) },
            { 0x1f, new OpCodeDefinition(OpCode.Unknown, (cpu, addr, value) => cpu.IllegalInstruction(addr, value), (cpu) => cpu.DecodeUndefined(3, 7), AddressingMode.Unknown) },

            { 0x20, new OpCodeDefinition(OpCode.JSR, (cpu, addr, value) => cpu.JSR(addr, value), (cpu) => cpu.DecodeAbsolute(), AddressingMode.Absolute) },
            { 0x21, new OpCodeDefinition(OpCode.AND, (cpu, addr, value) => cpu.AND(addr, value), (cpu) => cpu.DecodeXIndexedIndirect(), AddressingMode.XIndexedIndirect) },
            { 0x22, new OpCodeDefinition(OpCode.Unknown, (cpu, addr, value) => cpu.IllegalInstruction(addr, value), (cpu) => cpu.DecodeUndefined(0, 0), AddressingMode.Unknown) },
            { 0x23, new OpCodeDefinition(OpCode.Unknown, (cpu, addr, value) => cpu.IllegalInstruction(addr, value), (cpu) => cpu.DecodeUndefined(2, 8), AddressingMode.Unknown) },
            { 0x24, new OpCodeDefinition(OpCode.BIT, (cpu, addr, value) => cpu.BIT(addr, value, immediateMode: false), (cpu) => cpu.DecodeZeroPage(), AddressingMode.ZeroPage) },
            { 0x25, new OpCodeDefinition(OpCode.AND, (cpu, addr, value) => cpu.AND(addr, value), (cpu) => cpu.DecodeZeroPage(), AddressingMode.ZeroPage) },
            { 0x26, new OpCodeDefinition(OpCode.ROL, (cpu, addr, value) => cpu.ROL(addr, value), (cpu) => cpu.DecodeZeroPage(), AddressingMode.ZeroPage) },
            { 0x27, new OpCodeDefinition(OpCode.Unknown, (cpu, addr, value) => cpu.IllegalInstruction(addr, value), (cpu) => cpu.DecodeUndefined(2, 5), AddressingMode.Unknown) },
            { 0x28, new OpCodeDefinition(OpCode.PLP, (cpu, addr, value) => cpu.PLP(addr, value), (cpu) => cpu.DecodeStack(), AddressingMode.Stack) },
            { 0x29, new OpCodeDefinition(OpCode.AND, (cpu, addr, value) => cpu.AND(addr, value), (cpu) => cpu.DecodeImmediate(), AddressingMode.Immediate) },
            { 0x2a, new OpCodeDefinition(OpCode.ROL_A, (cpu, addr, value) => cpu.ROL_A(addr, value), (cpu) => cpu.DecodeAccumulator(), AddressingMode.Accumulator) },
            { 0x2b, new OpCodeDefinition(OpCode.Unknown, (cpu, addr, value) => cpu.IllegalInstruction(addr, value), (cpu) => cpu.DecodeUndefined(2, 2), AddressingMode.Unknown) },
            { 0x2c, new OpCodeDefinition(OpCode.BIT, (cpu, addr, value) => cpu.BIT(addr, value, immediateMode: false), (cpu) => cpu.DecodeAbsolute(), AddressingMode.Absolute) },
            { 0x2d, new OpCodeDefinition(OpCode.AND, (cpu, addr, value) => cpu.AND(addr, value), (cpu) => cpu.DecodeAbsolute(), AddressingMode.Absolute) },
            { 0x2e, new OpCodeDefinition(OpCode.ROL, (cpu, addr, value) => cpu.ROL(addr, value), (cpu) => cpu.DecodeAbsolute(), AddressingMode.Absolute) },
            { 0x2f, new OpCodeDefinition(OpCode.Unknown, (cpu, addr, value) => cpu.IllegalInstruction(addr, value), (cpu) => cpu.DecodeUndefined(3, 6), AddressingMode.Unknown) },

            { 0x30, new OpCodeDefinition(OpCode.BMI, (cpu, addr, value) => cpu.BMI(addr, value), (cpu) => cpu.DecodeRelative(), AddressingMode.Relative) },
            { 0x31, new OpCodeDefinition(OpCode.AND, (cpu, addr, value) => cpu.AND(addr, value), (cpu) => cpu.DecodeIndirectYIndexed(), AddressingMode.IndirectYIndexed) },
            { 0x32, new OpCodeDefinition(OpCode.Unknown, (cpu, addr, value) => cpu.IllegalInstruction(addr, value), (cpu) => cpu.DecodeUndefined(0, 0), AddressingMode.Unknown) },
            { 0x33, new OpCodeDefinition(OpCode.Unknown, (cpu, addr, value) => cpu.IllegalInstruction(addr, value), (cpu) => cpu.DecodeUndefined(2, 8), AddressingMode.Unknown) },
            { 0x34, new OpCodeDefinition(OpCode.Unknown, (cpu, addr, value) => cpu.IllegalInstruction(addr, value), (cpu) => cpu.DecodeUndefined(2, 4), AddressingMode.Unknown) },
            { 0x35, new OpCodeDefinition(OpCode.AND, (cpu, addr, value) => cpu.AND(addr, value), (cpu) => cpu.DecodeZeroPageXIndexed(), AddressingMode.ZeroPageXIndexed) },
            { 0x36, new OpCodeDefinition(OpCode.ROL, (cpu, addr, value) => cpu.ROL(addr, value), (cpu) => cpu.DecodeZeroPageXIndexed(), AddressingMode.ZeroPageXIndexed) },
            { 0x37, new OpCodeDefinition(OpCode.Unknown, (cpu, addr, value) => cpu.IllegalInstruction(addr, value), (cpu) => cpu.DecodeUndefined(2, 6), AddressingMode.Unknown) },
            { 0x38, new OpCodeDefinition(OpCode.SEC, (cpu, addr, value) => cpu.SEC(addr, value), (cpu) => cpu.DecodeImplicit(), AddressingMode.Implicit) },
            { 0x39, new OpCodeDefinition(OpCode.AND, (cpu, addr, value) => cpu.AND(addr, value), (cpu) => cpu.DecodeAbsoluteYIndexed(), AddressingMode.AbsoluteYIndexed) },
            { 0x3a, new OpCodeDefinition(OpCode.Unknown, (cpu, addr, value) => cpu.IllegalInstruction(addr, value), (cpu) => cpu.DecodeUndefined(1, 2), AddressingMode.Unknown) },
            { 0x3b, new OpCodeDefinition(OpCode.Unknown, (cpu, addr, value) => cpu.IllegalInstruction(addr, value), (cpu) => cpu.DecodeUndefined(3, 7), AddressingMode.Unknown) },
            { 0x3c, new OpCodeDefinition(OpCode.Unknown, (cpu, addr, value) => cpu.IllegalInstruction(addr, value), (cpu) => cpu.DecodeUndefined(3, 4), AddressingMode.Unknown) },
            { 0x3d, new OpCodeDefinition(OpCode.AND, (cpu, addr, value) => cpu.AND(addr, value), (cpu) => cpu.DecodeAbsoluteXIndexed(), AddressingMode.AbsoluteXIndexed) },
            { 0x3e, new OpCodeDefinition(OpCode.ROL, (cpu, addr, value) => cpu.ROL(addr, value), (cpu) => cpu.DecodeAbsoluteXIndexed(), AddressingMode.AbsoluteXIndexed) },
            { 0x3f, new OpCodeDefinition(OpCode.Unknown, (cpu, addr, value) => cpu.IllegalInstruction(addr, value), (cpu) => cpu.DecodeUndefined(3, 7), AddressingMode.Unknown) },

            { 0x40, new OpCodeDefinition(OpCode.RTI, (cpu, addr, value) => cpu.RTI(addr, value), (cpu) => cpu.DecodeStack(), AddressingMode.Stack) },
            { 0x41, new OpCodeDefinition(OpCode.EOR, (cpu, addr, value) => cpu.EOR(addr, value), (cpu) => cpu.DecodeXIndexedIndirect(), AddressingMode.XIndexedIndirect) },
            { 0x42, new OpCodeDefinition(OpCode.Unknown, (cpu, addr, value) => cpu.IllegalInstruction(addr, value), (cpu) => cpu.DecodeUndefined(0, 0), AddressingMode.Unknown) },
            { 0x43, new OpCodeDefinition(OpCode.Unknown, (cpu, addr, value) => cpu.IllegalInstruction(addr, value), (cpu) => cpu.DecodeUndefined(2, 8), AddressingMode.Unknown) },
            { 0x44, new OpCodeDefinition(OpCode.Unknown, (cpu, addr, value) => cpu.IllegalInstruction(addr, value), (cpu) => cpu.DecodeUndefined(2, 3), AddressingMode.Unknown) },
            { 0x45, new OpCodeDefinition(OpCode.EOR, (cpu, addr, value) => cpu.EOR(addr, value), (cpu) => cpu.DecodeZeroPage(), AddressingMode.ZeroPage) },
            { 0x46, new OpCodeDefinition(OpCode.LSR, (cpu, addr, value) => cpu.LSR(addr, value), (cpu) => cpu.DecodeZeroPage(), AddressingMode.ZeroPage) },
            { 0x47, new OpCodeDefinition(OpCode.Unknown, (cpu, addr, value) => cpu.IllegalInstruction(addr, value), (cpu) => cpu.DecodeUndefined(2, 5), AddressingMode.Unknown) },
            { 0x48, new OpCodeDefinition(OpCode.PHA, (cpu, addr, value) => cpu.PHA(addr, value), (cpu) => cpu.DecodeStack(), AddressingMode.Stack) },
            { 0x49, new OpCodeDefinition(OpCode.EOR, (cpu, addr, value) => cpu.EOR(addr, value), (cpu) => cpu.DecodeImmediate(), AddressingMode.Immediate) },
            { 0x4a, new OpCodeDefinition(OpCode.LSR_A, (cpu, addr, value) => cpu.LSR_A(addr, value), (cpu) => cpu.DecodeAccumulator(), AddressingMode.Accumulator) },
            { 0x4b, new OpCodeDefinition(OpCode.Unknown, (cpu, addr, value) => cpu.IllegalInstruction(addr, value), (cpu) => cpu.DecodeUndefined(2, 2), AddressingMode.Unknown) },
            { 0x4c, new OpCodeDefinition(OpCode.JMP, (cpu, addr, value) => cpu.JMP(addr, value), (cpu) => cpu.DecodeAbsolute(), AddressingMode.Absolute) },
            { 0x4d, new OpCodeDefinition(OpCode.EOR, (cpu, addr, value) => cpu.EOR(addr, value), (cpu) => cpu.DecodeAbsolute(), AddressingMode.Absolute) },
            { 0x4e, new OpCodeDefinition(OpCode.LSR, (cpu, addr, value) => cpu.LSR(addr, value), (cpu) => cpu.DecodeAbsolute(), AddressingMode.Absolute) },
            { 0x4f, new OpCodeDefinition(OpCode.Unknown, (cpu, addr, value) => cpu.IllegalInstruction(addr, value), (cpu) => cpu.DecodeUndefined(3, 6), AddressingMode.Unknown) },

            { 0x50, new OpCodeDefinition(OpCode.BVC, (cpu, addr, value) => cpu.BVC(addr, value), (cpu) => cpu.DecodeRelative(), AddressingMode.Relative) },
            { 0x51, new OpCodeDefinition(OpCode.EOR, (cpu, addr, value) => cpu.EOR(addr, value), (cpu) => cpu.DecodeIndirectYIndexed(), AddressingMode.IndirectYIndexed) },
            { 0x52, new OpCodeDefinition(OpCode.Unknown, (cpu, addr, value) => cpu.IllegalInstruction(addr, value), (cpu) => cpu.DecodeUndefined(0, 0), AddressingMode.Unknown) },
            { 0x53, new OpCodeDefinition(OpCode.Unknown, (cpu, addr, value) => cpu.IllegalInstruction(addr, value), (cpu) => cpu.DecodeUndefined(2, 8), AddressingMode.Unknown) },
            { 0x54, new OpCodeDefinition(OpCode.Unknown, (cpu, addr, value) => cpu.IllegalInstruction(addr, value), (cpu) => cpu.DecodeUndefined(2, 4), AddressingMode.Unknown) },
            { 0x55, new OpCodeDefinition(OpCode.EOR, (cpu, addr, value) => cpu.EOR(addr, value), (cpu) => cpu.DecodeZeroPageXIndexed(), AddressingMode.ZeroPageXIndexed) },
            { 0x56, new OpCodeDefinition(OpCode.LSR, (cpu, addr, value) => cpu.LSR(addr, value), (cpu) => cpu.DecodeZeroPageXIndexed(), AddressingMode.ZeroPageXIndexed) },
            { 0x57, new OpCodeDefinition(OpCode.Unknown, (cpu, addr, value) => cpu.IllegalInstruction(addr, value), (cpu) => cpu.DecodeUndefined(2, 6), AddressingMode.Unknown) },
            { 0x58, new OpCodeDefinition(OpCode.CLI, (cpu, addr, value) => cpu.CLI(addr, value), (cpu) => cpu.DecodeImplicit(), AddressingMode.Implicit) },
            { 0x59, new OpCodeDefinition(OpCode.EOR, (cpu, addr, value) => cpu.EOR(addr, value), (cpu) => cpu.DecodeAbsoluteYIndexed(), AddressingMode.AbsoluteYIndexed) },
            { 0x5a, new OpCodeDefinition(OpCode.Unknown, (cpu, addr, value) => cpu.IllegalInstruction(addr, value), (cpu) => cpu.DecodeUndefined(1, 2), AddressingMode.Unknown) },
            { 0x5b, new OpCodeDefinition(OpCode.Unknown, (cpu, addr, value) => cpu.IllegalInstruction(addr, value), (cpu) => cpu.DecodeUndefined(3, 7), AddressingMode.Unknown) },
            { 0x5c, new OpCodeDefinition(OpCode.Unknown, (cpu, addr, value) => cpu.IllegalInstruction(addr, value), (cpu) => cpu.DecodeUndefined(3, 4), AddressingMode.Unknown) },
            { 0x5d, new OpCodeDefinition(OpCode.EOR, (cpu, addr, value) => cpu.EOR(addr, value), (cpu) => cpu.DecodeAbsoluteXIndexed(), AddressingMode.AbsoluteXIndexed) },
            { 0x5e, new OpCodeDefinition(OpCode.LSR, (cpu, addr, value) => cpu.LSR(addr, value), (cpu) => cpu.DecodeAbsoluteXIndexed(), AddressingMode.AbsoluteXIndexed) },
            { 0x5f, new OpCodeDefinition(OpCode.Unknown, (cpu, addr, value) => cpu.IllegalInstruction(addr, value), (cpu) => cpu.DecodeUndefined(3, 7), AddressingMode.Unknown) },

            { 0x60, new OpCodeDefinition(OpCode.RTS, (cpu, addr, value) => cpu.RTS(addr, value), (cpu) => cpu.DecodeStack(), AddressingMode.Stack) },
            { 0x61, new OpCodeDefinition(OpCode.ADC, (cpu, addr, value) => cpu.ADC_NMOS(addr, value), (cpu) => cpu.DecodeXIndexedIndirect(), AddressingMode.XIndexedIndirect) },
            { 0x62, new OpCodeDefinition(OpCode.Unknown, (cpu, addr, value) => cpu.IllegalInstruction(addr, value), (cpu) => cpu.DecodeUndefined(0, 0), AddressingMode.Unknown) },
            { 0x63, new OpCodeDefinition(OpCode.Unknown, (cpu, addr, value) => cpu.IllegalInstruction(addr, value), (cpu) => cpu.DecodeUndefined(2, 8), AddressingMode.Unknown) },
            { 0x64, new OpCodeDefinition(OpCode.Unknown, (cpu, addr, value) => cpu.IllegalInstruction(addr, value), (cpu) => cpu.DecodeUndefined(2, 3), AddressingMode.Unknown) },
            { 0x65, new OpCodeDefinition(OpCode.ADC, (cpu, addr, value) => cpu.ADC_NMOS(addr, value), (cpu) => cpu.DecodeZeroPage(), AddressingMode.ZeroPage) },
            { 0x66, new OpCodeDefinition(OpCode.ROR, (cpu, addr, value) => cpu.ROR(addr, value), (cpu) => cpu.DecodeZeroPage(), AddressingMode.ZeroPage) },
            { 0x67, new OpCodeDefinition(OpCode.Unknown, (cpu, addr, value) => cpu.IllegalInstruction(addr, value), (cpu) => cpu.DecodeUndefined(2, 5), AddressingMode.Unknown) },
            { 0x68, new OpCodeDefinition(OpCode.PLA, (cpu, addr, value) => cpu.PLA(addr, value), (cpu) => cpu.DecodeStack(), AddressingMode.Stack) },
            { 0x69, new OpCodeDefinition(OpCode.ADC, (cpu, addr, value) => cpu.ADC_NMOS(addr, value), (cpu) => cpu.DecodeImmediate(), AddressingMode.Immediate) },
            { 0x6a, new OpCodeDefinition(OpCode.ROR_A, (cpu, addr, value) => cpu.ROR_A(addr, value), (cpu) => cpu.DecodeAccumulator(), AddressingMode.Accumulator) },
            { 0x6b, new OpCodeDefinition(OpCode.Unknown, (cpu, addr, value) => cpu.IllegalInstruction(addr, value), (cpu) => cpu.DecodeUndefined(2, 2), AddressingMode.Unknown) },
            { 0x6c, new OpCodeDefinition(OpCode.JMP, (cpu, addr, value) => cpu.JMP(addr, value), (cpu) => cpu.DecodeAbsoluteIndirect(), AddressingMode.AbsoluteIndirect) },
            { 0x6d, new OpCodeDefinition(OpCode.ADC, (cpu, addr, value) => cpu.ADC_NMOS(addr, value), (cpu) => cpu.DecodeAbsolute(), AddressingMode.Absolute) },
            { 0x6e, new OpCodeDefinition(OpCode.ROR, (cpu, addr, value) => cpu.ROR(addr, value), (cpu) => cpu.DecodeAbsolute(), AddressingMode.Absolute) },
            { 0x6f, new OpCodeDefinition(OpCode.Unknown, (cpu, addr, value) => cpu.IllegalInstruction(addr, value), (cpu) => cpu.DecodeUndefined(3, 6), AddressingMode.Unknown) },

            { 0x70, new OpCodeDefinition(OpCode.BVS, (cpu, addr, value) => cpu.BVS(addr, value), (cpu) => cpu.DecodeRelative(), AddressingMode.Relative) },
            { 0x71, new OpCodeDefinition(OpCode.ADC, (cpu, addr, value) => cpu.ADC_NMOS(addr, value), (cpu) => cpu.DecodeIndirectYIndexed(), AddressingMode.IndirectYIndexed) },
            { 0x72, new OpCodeDefinition(OpCode.Unknown, (cpu, addr, value) => cpu.IllegalInstruction(addr, value), (cpu) => cpu.DecodeUndefined(0, 0), AddressingMode.Unknown) },
            { 0x73, new OpCodeDefinition(OpCode.Unknown, (cpu, addr, value) => cpu.IllegalInstruction(addr, value), (cpu) => cpu.DecodeUndefined(2, 8), AddressingMode.Unknown) },
            { 0x74, new OpCodeDefinition(OpCode.Unknown, (cpu, addr, value) => cpu.IllegalInstruction(addr, value), (cpu) => cpu.DecodeUndefined(2, 4), AddressingMode.Unknown) },
            { 0x75, new OpCodeDefinition(OpCode.ADC, (cpu, addr, value) => cpu.ADC_NMOS(addr, value), (cpu) => cpu.DecodeZeroPageXIndexed(), AddressingMode.ZeroPageXIndexed) },
            { 0x76, new OpCodeDefinition(OpCode.ROR, (cpu, addr, value) => cpu.ROR(addr, value), (cpu) => cpu.DecodeZeroPageXIndexed(), AddressingMode.ZeroPageXIndexed) },
            { 0x77, new OpCodeDefinition(OpCode.Unknown, (cpu, addr, value) => cpu.IllegalInstruction(addr, value), (cpu) => cpu.DecodeUndefined(2, 6), AddressingMode.Unknown) },
            { 0x78, new OpCodeDefinition(OpCode.SEI, (cpu, addr, value) => cpu.SEI(addr, value), (cpu) => cpu.DecodeImplicit(), AddressingMode.Implicit) },
            { 0x79, new OpCodeDefinition(OpCode.ADC, (cpu, addr, value) => cpu.ADC_NMOS(addr, value), (cpu) => cpu.DecodeAbsoluteYIndexed(), AddressingMode.AbsoluteYIndexed) },
            { 0x7a, new OpCodeDefinition(OpCode.Unknown, (cpu, addr, value) => cpu.IllegalInstruction(addr, value), (cpu) => cpu.DecodeUndefined(1, 2), AddressingMode.Unknown) },
            { 0x7b, new OpCodeDefinition(OpCode.Unknown, (cpu, addr, value) => cpu.IllegalInstruction(addr, value), (cpu) => cpu.DecodeUndefined(3, 7), AddressingMode.Unknown) },
            { 0x7c, new OpCodeDefinition(OpCode.Unknown, (cpu, addr, value) => cpu.IllegalInstruction(addr, value), (cpu) => cpu.DecodeUndefined(3, 4), AddressingMode.Unknown) },
            { 0x7d, new OpCodeDefinition(OpCode.ADC, (cpu, addr, value) => cpu.ADC_NMOS(addr, value), (cpu) => cpu.DecodeAbsoluteXIndexed(), AddressingMode.AbsoluteXIndexed) },
            { 0x7e, new OpCodeDefinition(OpCode.ROR, (cpu, addr, value) => cpu.ROR(addr, value), (cpu) => cpu.DecodeAbsoluteXIndexed(), AddressingMode.AbsoluteXIndexed) },
            { 0x7f, new OpCodeDefinition(OpCode.Unknown, (cpu, addr, value) => cpu.IllegalInstruction(addr, value), (cpu) => cpu.DecodeUndefined(3, 7), AddressingMode.Unknown) },

            { 0x80, new OpCodeDefinition(OpCode.Unknown, (cpu, addr, value) => cpu.IllegalInstruction(addr, value), (cpu) => cpu.DecodeUndefined(2, 2), AddressingMode.Unknown) },
            { 0x81, new OpCodeDefinition(OpCode.STA, (cpu, addr, value) => cpu.STA(addr, value), (cpu) => cpu.DecodeXIndexedIndirect(), AddressingMode.XIndexedIndirect) },
            { 0x82, new OpCodeDefinition(OpCode.Unknown, (cpu, addr, value) => cpu.IllegalInstruction(addr, value), (cpu) => cpu.DecodeUndefined(2, 2), AddressingMode.Unknown) },
            { 0x83, new OpCodeDefinition(OpCode.Unknown, (cpu, addr, value) => cpu.IllegalInstruction(addr, value), (cpu) => cpu.DecodeUndefined(2, 6), AddressingMode.Unknown) },
            { 0x84, new OpCodeDefinition(OpCode.STY, (cpu, addr, value) => cpu.STY(addr, value), (cpu) => cpu.DecodeZeroPage(), AddressingMode.ZeroPage) },
            { 0x85, new OpCodeDefinition(OpCode.STA, (cpu, addr, value) => cpu.STA(addr, value), (cpu) => cpu.DecodeZeroPage(), AddressingMode.ZeroPage) },
            { 0x86, new OpCodeDefinition(OpCode.STX, (cpu, addr, value) => cpu.STX(addr, value), (cpu) => cpu.DecodeZeroPage(), AddressingMode.ZeroPage) },
            { 0x87, new OpCodeDefinition(OpCode.Unknown, (cpu, addr, value) => cpu.IllegalInstruction(addr, value), (cpu) => cpu.DecodeUndefined(2, 3), AddressingMode.Unknown) },
            { 0x88, new OpCodeDefinition(OpCode.DEY, (cpu, addr, value) => cpu.DEY(addr, value), (cpu) => cpu.DecodeImplicit(), AddressingMode.Implicit) },
            { 0x89, new OpCodeDefinition(OpCode.Unknown, (cpu, addr, value) => cpu.IllegalInstruction(addr, value), (cpu) => cpu.DecodeUndefined(2, 2), AddressingMode.Unknown) },
            { 0x8a, new OpCodeDefinition(OpCode.TXA, (cpu, addr, value) => cpu.TXA(addr, value), (cpu) => cpu.DecodeImplicit(), AddressingMode.Implicit) },
            { 0x8b, new OpCodeDefinition(OpCode.Unknown, (cpu, addr, value) => cpu.IllegalInstruction(addr, value), (cpu) => cpu.DecodeUndefined(2, 2), AddressingMode.Unknown) },
            { 0x8c, new OpCodeDefinition(OpCode.STY, (cpu, addr, value) => cpu.STY(addr, value), (cpu) => cpu.DecodeAbsolute(), AddressingMode.Absolute) },
            { 0x8d, new OpCodeDefinition(OpCode.STA, (cpu, addr, value) => cpu.STA(addr, value), (cpu) => cpu.DecodeAbsolute(), AddressingMode.Absolute) },
            { 0x8e, new OpCodeDefinition(OpCode.STX, (cpu, addr, value) => cpu.STX(addr, value), (cpu) => cpu.DecodeAbsolute(), AddressingMode.Absolute) },
            { 0x8f, new OpCodeDefinition(OpCode.Unknown, (cpu, addr, value) => cpu.IllegalInstruction(addr, value), (cpu) => cpu.DecodeUndefined(3, 4), AddressingMode.Unknown) },

            { 0x90, new OpCodeDefinition(OpCode.BCC, (cpu, addr, value) => cpu.BCC(addr, value), (cpu) => cpu.DecodeRelative(), AddressingMode.Relative) },
            { 0x91, new OpCodeDefinition(OpCode.STA, (cpu, addr, value) => cpu.STA(addr, value), (cpu) => cpu.DecodeIndirectYIndexed(), AddressingMode.IndirectYIndexed) },
            { 0x92, new OpCodeDefinition(OpCode.Unknown, (cpu, addr, value) => cpu.IllegalInstruction(addr, value), (cpu) => cpu.DecodeUndefined(0, 0), AddressingMode.Unknown) },
            { 0x93, new OpCodeDefinition(OpCode.Unknown, (cpu, addr, value) => cpu.IllegalInstruction(addr, value), (cpu) => cpu.DecodeUndefined(2, 6), AddressingMode.Unknown) },
            { 0x94, new OpCodeDefinition(OpCode.STY, (cpu, addr, value) => cpu.STY(addr, value), (cpu) => cpu.DecodeZeroPageXIndexed(), AddressingMode.ZeroPageXIndexed) },
            { 0x95, new OpCodeDefinition(OpCode.STA, (cpu, addr, value) => cpu.STA(addr, value), (cpu) => cpu.DecodeZeroPageXIndexed(), AddressingMode.ZeroPageXIndexed) },
            { 0x96, new OpCodeDefinition(OpCode.STX, (cpu, addr, value) => cpu.STX(addr, value), (cpu) => cpu.DecodeZeroPageYIndexed(), AddressingMode.ZeroPageYIndexed) },
            { 0x97, new OpCodeDefinition(OpCode.Unknown, (cpu, addr, value) => cpu.IllegalInstruction(addr, value), (cpu) => cpu.DecodeUndefined(2, 4), AddressingMode.Unknown) },
            { 0x98, new OpCodeDefinition(OpCode.TYA, (cpu, addr, value) => cpu.TYA(addr, value), (cpu) => cpu.DecodeImplicit(), AddressingMode.Implicit) },
            { 0x99, new OpCodeDefinition(OpCode.STA, (cpu, addr, value) => cpu.STA(addr, value), (cpu) => cpu.DecodeAbsoluteYIndexed(), AddressingMode.AbsoluteYIndexed) },
            { 0x9a, new OpCodeDefinition(OpCode.TXS, (cpu, addr, value) => cpu.TXS(addr, value), (cpu) => cpu.DecodeImplicit(), AddressingMode.Implicit) },
            { 0x9b, new OpCodeDefinition(OpCode.Unknown, (cpu, addr, value) => cpu.IllegalInstruction(addr, value), (cpu) => cpu.DecodeUndefined(3, 5), AddressingMode.Unknown) },
            { 0x9c, new OpCodeDefinition(OpCode.Unknown, (cpu, addr, value) => cpu.IllegalInstruction(addr, value), (cpu) => cpu.DecodeUndefined(3, 5), AddressingMode.Unknown) },
            { 0x9d, new OpCodeDefinition(OpCode.STA, (cpu, addr, value) => cpu.STA(addr, value), (cpu) => cpu.DecodeAbsoluteXIndexed(), AddressingMode.AbsoluteXIndexed) },
            { 0x9e, new OpCodeDefinition(OpCode.Unknown, (cpu, addr, value) => cpu.IllegalInstruction(addr, value), (cpu) => cpu.DecodeUndefined(3, 5), AddressingMode.Unknown) },
            { 0x9f, new OpCodeDefinition(OpCode.Unknown, (cpu, addr, value) => cpu.IllegalInstruction(addr, value), (cpu) => cpu.DecodeUndefined(3, 5), AddressingMode.Unknown) },

            { 0xa0, new OpCodeDefinition(OpCode.LDY, (cpu, addr, value) => cpu.LDY(addr, value), (cpu) => cpu.DecodeImmediate(), AddressingMode.Immediate) },
            { 0xa1, new OpCodeDefinition(OpCode.LDA, (cpu, addr, value) => cpu.LDA(addr, value), (cpu) => cpu.DecodeXIndexedIndirect(), AddressingMode.XIndexedIndirect) },
            { 0xa2, new OpCodeDefinition(OpCode.LDX, (cpu, addr, value) => cpu.LDX(addr, value), (cpu) => cpu.DecodeImmediate(), AddressingMode.Immediate) },
            { 0xa3, new OpCodeDefinition(OpCode.Unknown, (cpu, addr, value) => cpu.IllegalInstruction(addr, value), (cpu) => cpu.DecodeUndefined(2, 6), AddressingMode.Unknown) },
            { 0xa4, new OpCodeDefinition(OpCode.LDY, (cpu, addr, value) => cpu.LDY(addr, value), (cpu) => cpu.DecodeZeroPage(), AddressingMode.ZeroPage) },
            { 0xa5, new OpCodeDefinition(OpCode.LDA, (cpu, addr, value) => cpu.LDA(addr, value), (cpu) => cpu.DecodeZeroPage(), AddressingMode.ZeroPage) },
            { 0xa6, new OpCodeDefinition(OpCode.LDX, (cpu, addr, value) => cpu.LDX(addr, value), (cpu) => cpu.DecodeZeroPage(), AddressingMode.ZeroPage) },
            { 0xa7, new OpCodeDefinition(OpCode.Unknown, (cpu, addr, value) => cpu.IllegalInstruction(addr, value), (cpu) => cpu.DecodeUndefined(2, 3), AddressingMode.Unknown) },
            { 0xa8, new OpCodeDefinition(OpCode.TAY, (cpu, addr, value) => cpu.TAY(addr, value), (cpu) => cpu.DecodeImplicit(), AddressingMode.Implicit) },
            { 0xa9, new OpCodeDefinition(OpCode.LDA, (cpu, addr, value) => cpu.LDA(addr, value), (cpu) => cpu.DecodeImmediate(), AddressingMode.Immediate) },
            { 0xaa, new OpCodeDefinition(OpCode.TAX, (cpu, addr, value) => cpu.TAX(addr, value), (cpu) => cpu.DecodeImplicit(), AddressingMode.Implicit) },
            { 0xab, new OpCodeDefinition(OpCode.Unknown, (cpu, addr, value) => cpu.IllegalInstruction(addr, value), (cpu) => cpu.DecodeUndefined(2, 2), AddressingMode.Unknown) },
            { 0xac, new OpCodeDefinition(OpCode.LDY, (cpu, addr, value) => cpu.LDY(addr, value), (cpu) => cpu.DecodeAbsolute(), AddressingMode.Absolute) },
            { 0xad, new OpCodeDefinition(OpCode.LDA, (cpu, addr, value) => cpu.LDA(addr, value), (cpu) => cpu.DecodeAbsolute(), AddressingMode.Absolute) },
            { 0xae, new OpCodeDefinition(OpCode.LDX, (cpu, addr, value) => cpu.LDX(addr, value), (cpu) => cpu.DecodeAbsolute(), AddressingMode.Absolute) },
            { 0xaf, new OpCodeDefinition(OpCode.Unknown, (cpu, addr, value) => cpu.IllegalInstruction(addr, value), (cpu) => cpu.DecodeUndefined(3, 4), AddressingMode.Unknown) },

            { 0xb0, new OpCodeDefinition(OpCode.BCS, (cpu, addr, value) => cpu.BCS(addr, value), (cpu) => cpu.DecodeRelative(), AddressingMode.Relative) },
            { 0xb1, new OpCodeDefinition(OpCode.LDA, (cpu, addr, value) => cpu.LDA(addr, value), (cpu) => cpu.DecodeIndirectYIndexed(), AddressingMode.IndirectYIndexed) },
            { 0xb2, new OpCodeDefinition(OpCode.Unknown, (cpu, addr, value) => cpu.IllegalInstruction(addr, value), (cpu) => cpu.DecodeUndefined(0, 0), AddressingMode.Unknown) },
            { 0xb3, new OpCodeDefinition(OpCode.Unknown, (cpu, addr, value) => cpu.IllegalInstruction(addr, value), (cpu) => cpu.DecodeUndefined(2, 5), AddressingMode.Unknown) },
            { 0xb4, new OpCodeDefinition(OpCode.LDY, (cpu, addr, value) => cpu.LDY(addr, value), (cpu) => cpu.DecodeZeroPageXIndexed(), AddressingMode.ZeroPageXIndexed) },
            { 0xb5, new OpCodeDefinition(OpCode.LDA, (cpu, addr, value) => cpu.LDA(addr, value), (cpu) => cpu.DecodeZeroPageXIndexed(), AddressingMode.ZeroPageXIndexed) },
            { 0xb6, new OpCodeDefinition(OpCode.LDX, (cpu, addr, value) => cpu.LDX(addr, value), (cpu) => cpu.DecodeZeroPageYIndexed(), AddressingMode.ZeroPageYIndexed) },
            { 0xb7, new OpCodeDefinition(OpCode.Unknown, (cpu, addr, value) => cpu.IllegalInstruction(addr, value), (cpu) => cpu.DecodeUndefined(2, 4), AddressingMode.Unknown) },
            { 0xb8, new OpCodeDefinition(OpCode.CLV, (cpu, addr, value) => cpu.CLV(addr, value), (cpu) => cpu.DecodeImplicit(), AddressingMode.Implicit) },
            { 0xb9, new OpCodeDefinition(OpCode.LDA, (cpu, addr, value) => cpu.LDA(addr, value), (cpu) => cpu.DecodeAbsoluteYIndexed(), AddressingMode.AbsoluteYIndexed) },
            { 0xba, new OpCodeDefinition(OpCode.TSX, (cpu, addr, value) => cpu.TSX(addr, value), (cpu) => cpu.DecodeImplicit(), AddressingMode.Implicit) },
            { 0xbb, new OpCodeDefinition(OpCode.Unknown, (cpu, addr, value) => cpu.IllegalInstruction(addr, value), (cpu) => cpu.DecodeUndefined(3, 4), AddressingMode.Unknown) },
            { 0xbc, new OpCodeDefinition(OpCode.LDY, (cpu, addr, value) => cpu.LDY(addr, value), (cpu) => cpu.DecodeAbsoluteXIndexed(), AddressingMode.AbsoluteXIndexed) },
            { 0xbd, new OpCodeDefinition(OpCode.LDA, (cpu, addr, value) => cpu.LDA(addr, value), (cpu) => cpu.DecodeAbsoluteXIndexed(), AddressingMode.AbsoluteXIndexed) },
            { 0xbe, new OpCodeDefinition(OpCode.LDX, (cpu, addr, value) => cpu.LDX(addr, value), (cpu) => cpu.DecodeAbsoluteYIndexed(), AddressingMode.AbsoluteYIndexed) },
            { 0xbf, new OpCodeDefinition(OpCode.Unknown, (cpu, addr, value) => cpu.IllegalInstruction(addr, value), (cpu) => cpu.DecodeUndefined(3, 4), AddressingMode.Unknown) },

            { 0xc0, new OpCodeDefinition(OpCode.CPY, (cpu, addr, value) => cpu.CPY(addr, value), (cpu) => cpu.DecodeImmediate(), AddressingMode.Immediate) },
            { 0xc1, new OpCodeDefinition(OpCode.CMP, (cpu, addr, value) => cpu.CMP(addr, value), (cpu) => cpu.DecodeXIndexedIndirect(), AddressingMode.XIndexedIndirect) },
            { 0xc2, new OpCodeDefinition(OpCode.Unknown, (cpu, addr, value) => cpu.IllegalInstruction(addr, value), (cpu) => cpu.DecodeUndefined(2, 2), AddressingMode.Unknown) },
            { 0xc3, new OpCodeDefinition(OpCode.Unknown, (cpu, addr, value) => cpu.IllegalInstruction(addr, value), (cpu) => cpu.DecodeUndefined(2, 8), AddressingMode.Unknown) },
            { 0xc4, new OpCodeDefinition(OpCode.CPY, (cpu, addr, value) => cpu.CPY(addr, value), (cpu) => cpu.DecodeZeroPage(), AddressingMode.ZeroPage) },
            { 0xc5, new OpCodeDefinition(OpCode.CMP, (cpu, addr, value) => cpu.CMP(addr, value), (cpu) => cpu.DecodeZeroPage(), AddressingMode.ZeroPage) },
            { 0xc6, new OpCodeDefinition(OpCode.DEC, (cpu, addr, value) => cpu.DEC(addr, value), (cpu) => cpu.DecodeZeroPage(), AddressingMode.ZeroPage) },
            { 0xc7, new OpCodeDefinition(OpCode.Unknown, (cpu, addr, value) => cpu.IllegalInstruction(addr, value), (cpu) => cpu.DecodeUndefined(2, 5), AddressingMode.Unknown) },
            { 0xc8, new OpCodeDefinition(OpCode.INY, (cpu, addr, value) => cpu.INY(addr, value), (cpu) => cpu.DecodeImplicit(), AddressingMode.Implicit) },
            { 0xc9, new OpCodeDefinition(OpCode.CMP, (cpu, addr, value) => cpu.CMP(addr, value), (cpu) => cpu.DecodeImmediate(), AddressingMode.Immediate) },
            { 0xca, new OpCodeDefinition(OpCode.DEX, (cpu, addr, value) => cpu.DEX(addr, value), (cpu) => cpu.DecodeImplicit(), AddressingMode.Implicit) },
            { 0xcb, new OpCodeDefinition(OpCode.Unknown, (cpu, addr, value) => cpu.IllegalInstruction(addr, value), (cpu) => cpu.DecodeUndefined(2, 2), AddressingMode.Unknown) },
            { 0xcc, new OpCodeDefinition(OpCode.CPY, (cpu, addr, value) => cpu.CPY(addr, value), (cpu) => cpu.DecodeAbsolute(), AddressingMode.Absolute) },
            { 0xcd, new OpCodeDefinition(OpCode.CMP, (cpu, addr, value) => cpu.CMP(addr, value), (cpu) => cpu.DecodeAbsolute(), AddressingMode.Absolute) },
            { 0xce, new OpCodeDefinition(OpCode.DEC, (cpu, addr, value) => cpu.DEC(addr, value), (cpu) => cpu.DecodeAbsolute(), AddressingMode.Absolute) },
            { 0xcf, new OpCodeDefinition(OpCode.Unknown, (cpu, addr, value) => cpu.IllegalInstruction(addr, value), (cpu) => cpu.DecodeUndefined(3, 6), AddressingMode.Unknown) },

            { 0xd0, new OpCodeDefinition(OpCode.BNE, (cpu, addr, value) => cpu.BNE(addr, value), (cpu) => cpu.DecodeRelative(), AddressingMode.Relative) },
            { 0xd1, new OpCodeDefinition(OpCode.CMP, (cpu, addr, value) => cpu.CMP(addr, value), (cpu) => cpu.DecodeIndirectYIndexed(), AddressingMode.IndirectYIndexed) },
            { 0xd2, new OpCodeDefinition(OpCode.Unknown, (cpu, addr, value) => cpu.IllegalInstruction(addr, value), (cpu) => cpu.DecodeUndefined(0, 0), AddressingMode.Unknown) },
            { 0xd3, new OpCodeDefinition(OpCode.Unknown, (cpu, addr, value) => cpu.IllegalInstruction(addr, value), (cpu) => cpu.DecodeUndefined(2, 8), AddressingMode.Unknown) },
            { 0xd4, new OpCodeDefinition(OpCode.Unknown, (cpu, addr, value) => cpu.IllegalInstruction(addr, value), (cpu) => cpu.DecodeUndefined(2, 4), AddressingMode.Unknown) },
            { 0xd5, new OpCodeDefinition(OpCode.CMP, (cpu, addr, value) => cpu.CMP(addr, value), (cpu) => cpu.DecodeZeroPageXIndexed(), AddressingMode.ZeroPageXIndexed) },
            { 0xd6, new OpCodeDefinition(OpCode.DEC, (cpu, addr, value) => cpu.DEC(addr, value), (cpu) => cpu.DecodeZeroPageXIndexed(), AddressingMode.ZeroPageXIndexed) },
            { 0xd7, new OpCodeDefinition(OpCode.Unknown, (cpu, addr, value) => cpu.IllegalInstruction(addr, value), (cpu) => cpu.DecodeUndefined(2, 6), AddressingMode.Unknown) },
            { 0xd8, new OpCodeDefinition(OpCode.CLD, (cpu, addr, value) => cpu.CLD(addr, value), (cpu) => cpu.DecodeImplicit(), AddressingMode.Implicit) },
            { 0xd9, new OpCodeDefinition(OpCode.CMP, (cpu, addr, value) => cpu.CMP(addr, value), (cpu) => cpu.DecodeAbsoluteYIndexed(), AddressingMode.AbsoluteYIndexed) },
            { 0xda, new OpCodeDefinition(OpCode.Unknown, (cpu, addr, value) => cpu.IllegalInstruction(addr, value), (cpu) => cpu.DecodeUndefined(1, 2), AddressingMode.Unknown) },
            { 0xdb, new OpCodeDefinition(OpCode.Unknown, (cpu, addr, value) => cpu.IllegalInstruction(addr, value), (cpu) => cpu.DecodeUndefined(3, 7), AddressingMode.Unknown) },
            { 0xdc, new OpCodeDefinition(OpCode.Unknown, (cpu, addr, value) => cpu.IllegalInstruction(addr, value), (cpu) => cpu.DecodeUndefined(3, 4), AddressingMode.Unknown) },
            { 0xdd, new OpCodeDefinition(OpCode.CMP, (cpu, addr, value) => cpu.CMP(addr, value), (cpu) => cpu.DecodeAbsoluteXIndexed(), AddressingMode.AbsoluteXIndexed) },
            { 0xde, new OpCodeDefinition(OpCode.DEC, (cpu, addr, value) => cpu.DEC(addr, value), (cpu) => cpu.DecodeAbsoluteXIndexed(), AddressingMode.AbsoluteXIndexed) },
            { 0xdf, new OpCodeDefinition(OpCode.Unknown, (cpu, addr, value) => cpu.IllegalInstruction(addr, value), (cpu) => cpu.DecodeUndefined(3, 7), AddressingMode.Unknown) },

            { 0xe0, new OpCodeDefinition(OpCode.CPX, (cpu, addr, value) => cpu.CPX(addr, value), (cpu) => cpu.DecodeImmediate(), AddressingMode.Immediate) },
            { 0xe1, new OpCodeDefinition(OpCode.SBC, (cpu, addr, value) => cpu.SBC_NMOS(addr, value), (cpu) => cpu.DecodeXIndexedIndirect(), AddressingMode.XIndexedIndirect) },
            { 0xe2, new OpCodeDefinition(OpCode.Unknown, (cpu, addr, value) => cpu.IllegalInstruction(addr, value), (cpu) => cpu.DecodeUndefined(2, 2), AddressingMode.Unknown) },
            { 0xe3, new OpCodeDefinition(OpCode.Unknown, (cpu, addr, value) => cpu.IllegalInstruction(addr, value), (cpu) => cpu.DecodeUndefined(2, 8), AddressingMode.Unknown) },
            { 0xe4, new OpCodeDefinition(OpCode.CPX, (cpu, addr, value) => cpu.CPX(addr, value), (cpu) => cpu.DecodeZeroPage(), AddressingMode.ZeroPage) },
            { 0xe5, new OpCodeDefinition(OpCode.SBC, (cpu, addr, value) => cpu.SBC_NMOS(addr, value), (cpu) => cpu.DecodeZeroPage(), AddressingMode.ZeroPage) },
            { 0xe6, new OpCodeDefinition(OpCode.INC, (cpu, addr, value) => cpu.INC(addr, value), (cpu) => cpu.DecodeZeroPage(), AddressingMode.ZeroPage) },
            { 0xe7, new OpCodeDefinition(OpCode.Unknown, (cpu, addr, value) => cpu.IllegalInstruction(addr, value), (cpu) => cpu.DecodeUndefined(2, 5), AddressingMode.Unknown) },
            { 0xe8, new OpCodeDefinition(OpCode.INX, (cpu, addr, value) => cpu.INX(addr, value), (cpu) => cpu.DecodeImplicit(), AddressingMode.Implicit) },
            { 0xe9, new OpCodeDefinition(OpCode.SBC, (cpu, addr, value) => cpu.SBC_NMOS(addr, value), (cpu) => cpu.DecodeImmediate(), AddressingMode.Immediate) },
            { 0xea, new OpCodeDefinition(OpCode.NOP, (cpu, addr, value) => cpu.NOP(addr, value), (cpu) => cpu.DecodeImplicit(), AddressingMode.Implicit) },
            { 0xeb, new OpCodeDefinition(OpCode.Unknown, (cpu, addr, value) => cpu.IllegalInstruction(addr, value), (cpu) => cpu.DecodeUndefined(2, 2), AddressingMode.Unknown) },
            { 0xec, new OpCodeDefinition(OpCode.CPX, (cpu, addr, value) => cpu.CPX(addr, value), (cpu) => cpu.DecodeAbsolute(), AddressingMode.Absolute) },
            { 0xed, new OpCodeDefinition(OpCode.SBC, (cpu, addr, value) => cpu.SBC_NMOS(addr, value), (cpu) => cpu.DecodeAbsolute(), AddressingMode.Absolute) },
            { 0xee, new OpCodeDefinition(OpCode.INC, (cpu, addr, value) => cpu.INC(addr, value), (cpu) => cpu.DecodeAbsolute(), AddressingMode.Absolute) },
            { 0xef, new OpCodeDefinition(OpCode.Unknown, (cpu, addr, value) => cpu.IllegalInstruction(addr, value), (cpu) => cpu.DecodeUndefined(3, 6), AddressingMode.Unknown) },

            { 0xf0, new OpCodeDefinition(OpCode.BEQ, (cpu, addr, value) => cpu.BEQ(addr, value), (cpu) => cpu.DecodeRelative(), AddressingMode.Relative) },
            { 0xf1, new OpCodeDefinition(OpCode.SBC, (cpu, addr, value) => cpu.SBC_NMOS(addr, value), (cpu) => cpu.DecodeIndirectYIndexed(), AddressingMode.IndirectYIndexed) },
            { 0xf2, new OpCodeDefinition(OpCode.Unknown, (cpu, addr, value) => cpu.IllegalInstruction(addr, value), (cpu) => cpu.DecodeUndefined(0, 0), AddressingMode.Unknown) },
            { 0xf3, new OpCodeDefinition(OpCode.Unknown, (cpu, addr, value) => cpu.IllegalInstruction(addr, value), (cpu) => cpu.DecodeUndefined(2, 8), AddressingMode.Unknown) },
            { 0xf4, new OpCodeDefinition(OpCode.Unknown, (cpu, addr, value) => cpu.IllegalInstruction(addr, value), (cpu) => cpu.DecodeUndefined(2, 4), AddressingMode.Unknown) },
            { 0xf5, new OpCodeDefinition(OpCode.SBC, (cpu, addr, value) => cpu.SBC_NMOS(addr, value), (cpu) => cpu.DecodeZeroPageXIndexed(), AddressingMode.ZeroPageXIndexed) },
            { 0xf6, new OpCodeDefinition(OpCode.INC, (cpu, addr, value) => cpu.INC(addr, value), (cpu) => cpu.DecodeZeroPageXIndexed(), AddressingMode.ZeroPageXIndexed) },
            { 0xf7, new OpCodeDefinition(OpCode.Unknown, (cpu, addr, value) => cpu.IllegalInstruction(addr, value), (cpu) => cpu.DecodeUndefined(2, 6), AddressingMode.Unknown) },
            { 0xf8, new OpCodeDefinition(OpCode.SED, (cpu, addr, value) => cpu.SED(addr, value), (cpu) => cpu.DecodeImplicit(), AddressingMode.Implicit) },
            { 0xf9, new OpCodeDefinition(OpCode.SBC, (cpu, addr, value) => cpu.SBC_NMOS(addr, value), (cpu) => cpu.DecodeAbsoluteYIndexed(), AddressingMode.AbsoluteYIndexed) },
            { 0xfa, new OpCodeDefinition(OpCode.Unknown, (cpu, addr, value) => cpu.IllegalInstruction(addr, value), (cpu) => cpu.DecodeUndefined(1, 2), AddressingMode.Unknown) },
            { 0xfb, new OpCodeDefinition(OpCode.Unknown, (cpu, addr, value) => cpu.IllegalInstruction(addr, value), (cpu) => cpu.DecodeUndefined(3, 7), AddressingMode.Unknown) },
            { 0xfc, new OpCodeDefinition(OpCode.Unknown, (cpu, addr, value) => cpu.IllegalInstruction(addr, value), (cpu) => cpu.DecodeUndefined(3, 4), AddressingMode.Unknown) },
            { 0xfd, new OpCodeDefinition(OpCode.SBC, (cpu, addr, value) => cpu.SBC_NMOS(addr, value), (cpu) => cpu.DecodeAbsoluteXIndexed(), AddressingMode.AbsoluteXIndexed) },
            { 0xfe, new OpCodeDefinition(OpCode.INC, (cpu, addr, value) => cpu.INC(addr, value), (cpu) => cpu.DecodeAbsoluteXIndexed(), AddressingMode.AbsoluteXIndexed) },
            { 0xff, new OpCodeDefinition(OpCode.Unknown, (cpu, addr, value) => cpu.IllegalInstruction(addr, value), (cpu) => cpu.DecodeUndefined(3, 7), AddressingMode.Unknown) },
        };
    }
}
