using System.Collections.Generic;
using InnoWerks.Processors.Common;

namespace InnoWerks.Simulators
{
    public static class OpCodes
    {
        public static readonly Dictionary<byte, OpCodeDefinition> OpCode65C02 = new()
        {
            { 0x00, new OpCodeDefinition("BRK", (cpu, addr, value) => cpu.BRK(addr, value, 7), (cpu) => cpu.DecodeStack(), AddressingMode.Stack) },
            { 0x01, new OpCodeDefinition("ORA", (cpu, addr, value) => cpu.ORA(addr, value, 6), (cpu) => cpu.DecodeXIndexedIndirect(), AddressingMode.XIndexedIndirect) },
            { 0x02, new OpCodeDefinition(null, (cpu, addr, value) => cpu.IllegalInstruction(addr, value, 0), (cpu) => cpu.DecodeUndefined(), AddressingMode.Unknown) },
            { 0x03, new OpCodeDefinition(null, (cpu, addr, value) => cpu.IllegalInstruction(addr, value, 0), (cpu) => cpu.DecodeUndefined(), AddressingMode.Unknown) },
            { 0x04, new OpCodeDefinition("TSB", (cpu, addr, value) => cpu.TSB(addr, value, 5), (cpu) => cpu.DecodeZeroPage(), AddressingMode.ZeroPage) },
            { 0x05, new OpCodeDefinition("ORA", (cpu, addr, value) => cpu.ORA(addr, value, 3), (cpu) => cpu.DecodeZeroPage(), AddressingMode.ZeroPage) },
            { 0x06, new OpCodeDefinition("ASL", (cpu, addr, value) => cpu.ASL(addr, value, 5), (cpu) => cpu.DecodeZeroPage(), AddressingMode.ZeroPage) },
            { 0x07, new OpCodeDefinition("RMB", (cpu, addr, value) => cpu.RMB(addr, value, bit: 0, 5), (cpu) => cpu.DecodeZeroPage(), AddressingMode.ZeroPage) },
            { 0x08, new OpCodeDefinition("PHP", (cpu, addr, value) => cpu.PHP(addr, value, 3), (cpu) => cpu.DecodeStack(), AddressingMode.Stack) },
            { 0x09, new OpCodeDefinition("ORA", (cpu, addr, value) => cpu.ORA(addr, value, 2), (cpu) => cpu.DecodeImmediate(), AddressingMode.Immediate) },
            { 0x0a, new OpCodeDefinition("ASL", (cpu, addr, value) => cpu.ASL_A(addr, value, 2), (cpu) => cpu.DecodeAccumulator(), AddressingMode.Accumulator) },
            { 0x0b, new OpCodeDefinition(null, (cpu, addr, value) => cpu.IllegalInstruction(addr, value, 0), (cpu) => cpu.DecodeUndefined(), AddressingMode.Unknown) },
            { 0x0c, new OpCodeDefinition("TSB", (cpu, addr, value) => cpu.TSB(addr, value, 6), (cpu) => cpu.DecodeAbsolute(), AddressingMode.Absolute) },
            { 0x0d, new OpCodeDefinition("ORA", (cpu, addr, value) => cpu.ORA(addr, value, 4), (cpu) => cpu.DecodeAbsolute(), AddressingMode.Absolute) },
            { 0x0e, new OpCodeDefinition("ASL", (cpu, addr, value) => cpu.ASL(addr, value, 6), (cpu) => cpu.DecodeAbsolute(), AddressingMode.Absolute) },
            { 0x0f, new OpCodeDefinition("BBR", (cpu, addr, value) => cpu.BBR(addr, value, bit: 0, 5), (cpu) => cpu.DecodeRelative(), AddressingMode.Relative) },

            { 0x10, new OpCodeDefinition("BPL", (cpu, addr, value) => cpu.BPL(addr, value, 3, pageCrossPenalty: 1), (cpu) => cpu.DecodeRelative(), AddressingMode.Relative) },
            { 0x11, new OpCodeDefinition("ORA", (cpu, addr, value) => cpu.ORA(addr, value, 5), (cpu) => cpu.DecodeIndirectYIndexed(), AddressingMode.IndirectYIndexed) },
            { 0x12, new OpCodeDefinition("ORA", (cpu, addr, value) => cpu.ORA(addr, value, 5), (cpu) => cpu.DecodeZeroPageIndirect(), AddressingMode.ZeroPageIndirect) },
            { 0x13, new OpCodeDefinition(null, (cpu, addr, value) => cpu.IllegalInstruction(addr, value, 0), (cpu) => cpu.DecodeUndefined(), AddressingMode.Unknown) },
            { 0x14, new OpCodeDefinition("TRB", (cpu, addr, value) => cpu.TRB(addr, value, 5), (cpu) => cpu.DecodeZeroPage(), AddressingMode.ZeroPage) },
            { 0x15, new OpCodeDefinition("ORA", (cpu, addr, value) => cpu.ORA(addr, value, 4), (cpu) => cpu.DecodeZeroPageXIndexed(), AddressingMode.ZeroPageXIndexed) },
            { 0x16, new OpCodeDefinition("ASL", (cpu, addr, value) => cpu.ASL(addr, value, 6), (cpu) => cpu.DecodeZeroPageXIndexed(), AddressingMode.ZeroPageXIndexed) },
            { 0x17, new OpCodeDefinition("RMB", (cpu, addr, value) => cpu.RMB(addr, value, bit: 1, 5), (cpu) => cpu.DecodeZeroPage(), AddressingMode.ZeroPage) },
            { 0x18, new OpCodeDefinition("CLC", (cpu, addr, value) => cpu.CLC(addr, value, 2), (cpu) => cpu.DecodeImplied(), AddressingMode.Implied) },
            { 0x19, new OpCodeDefinition("ORA", (cpu, addr, value) => cpu.ORA(addr, value, 4, pageCrossPenalty: 1), (cpu) => cpu.DecodeAbsoluteYIndexed(), AddressingMode.AbsoluteYIndexed) },
            { 0x1a, new OpCodeDefinition("INC", (cpu, addr, value) => cpu.INA(addr, value, 2), (cpu) => cpu.DecodeAccumulator(), AddressingMode.Accumulator) },
            { 0x1b, new OpCodeDefinition(null, (cpu, addr, value) => cpu.IllegalInstruction(addr, value, 0), (cpu) => cpu.DecodeUndefined(), AddressingMode.Unknown) },
            { 0x1c, new OpCodeDefinition("TRB", (cpu, addr, value) => cpu.TRB(addr, value, 6), (cpu) => cpu.DecodeAbsolute(), AddressingMode.Absolute) },
            { 0x1d, new OpCodeDefinition("ORA", (cpu, addr, value) => cpu.ORA(addr, value, 4, pageCrossPenalty: 1), (cpu) => cpu.DecodeAbsoluteXIndexed(), AddressingMode.AbsoluteXIndexed) },
            { 0x1e, new OpCodeDefinition("ASL", (cpu, addr, value) => cpu.ASL(addr, value, 7), (cpu) => cpu.DecodeAbsoluteXIndexed(), AddressingMode.AbsoluteXIndexed) },
            { 0x1f, new OpCodeDefinition("BBR", (cpu, addr, value) => cpu.BBR(addr, value, bit: 1, 5), (cpu) => cpu.DecodeRelative(), AddressingMode.Relative) },

            { 0x20, new OpCodeDefinition("JSR", (cpu, addr, value) => cpu.JSR(addr, value, 6), (cpu) => cpu.DecodeAbsolute(), AddressingMode.Absolute) },
            { 0x21, new OpCodeDefinition("AND", (cpu, addr, value) => cpu.AND(addr, value, 6), (cpu) => cpu.DecodeXIndexedIndirect(), AddressingMode.XIndexedIndirect) },
            { 0x22, new OpCodeDefinition(null, (cpu, addr, value) => cpu.IllegalInstruction(addr, value, 0), (cpu) => cpu.DecodeUndefined(), AddressingMode.Unknown) },
            { 0x23, new OpCodeDefinition(null, (cpu, addr, value) => cpu.IllegalInstruction(addr, value, 0), (cpu) => cpu.DecodeUndefined(), AddressingMode.Unknown) },
            { 0x24, new OpCodeDefinition("BIT", (cpu, addr, value) => cpu.BIT(addr, value, 3, immediateMode: false), (cpu) => cpu.DecodeZeroPage(), AddressingMode.ZeroPage) },
            { 0x25, new OpCodeDefinition("AND", (cpu, addr, value) => cpu.AND(addr, value, 3), (cpu) => cpu.DecodeZeroPage(), AddressingMode.ZeroPage) },
            { 0x26, new OpCodeDefinition("ROL", (cpu, addr, value) => cpu.ROL(addr, value, 5), (cpu) => cpu.DecodeZeroPage(), AddressingMode.ZeroPage) },
            { 0x27, new OpCodeDefinition("RMB", (cpu, addr, value) => cpu.RMB(addr, value, bit: 2, 5), (cpu) => cpu.DecodeZeroPage(), AddressingMode.ZeroPage) },
            { 0x28, new OpCodeDefinition("PLP", (cpu, addr, value) => cpu.PLP(addr, value, 4), (cpu) => cpu.DecodeStack(), AddressingMode.Stack) },
            { 0x29, new OpCodeDefinition("AND", (cpu, addr, value) => cpu.AND(addr, value, 2), (cpu) => cpu.DecodeImmediate(), AddressingMode.Immediate) },
            { 0x2a, new OpCodeDefinition("ROL", (cpu, addr, value) => cpu.ROL_A(addr, value, 2), (cpu) => cpu.DecodeAccumulator(), AddressingMode.Accumulator) },
            { 0x2b, new OpCodeDefinition(null, (cpu, addr, value) => cpu.IllegalInstruction(addr, value, 0), (cpu) => cpu.DecodeUndefined(), AddressingMode.Unknown) },
            { 0x2c, new OpCodeDefinition("BIT", (cpu, addr, value) => cpu.BIT(addr, value, 4, immediateMode: false), (cpu) => cpu.DecodeAbsolute(), AddressingMode.Absolute) },
            { 0x2d, new OpCodeDefinition("AND", (cpu, addr, value) => cpu.AND(addr, value, 4), (cpu) => cpu.DecodeAbsolute(), AddressingMode.Absolute) },
            { 0x2e, new OpCodeDefinition("ROL", (cpu, addr, value) => cpu.ROL(addr, value, 6), (cpu) => cpu.DecodeAbsolute(), AddressingMode.Absolute) },
            { 0x2f, new OpCodeDefinition("BBR", (cpu, addr, value) => cpu.BBR(addr, value, bit: 2, 5), (cpu) => cpu.DecodeRelative(), AddressingMode.Relative) },

            { 0x30, new OpCodeDefinition("BMI", (cpu, addr, value) => cpu.BMI(addr, value, 3, pageCrossPenalty: 1), (cpu) => cpu.DecodeRelative(), AddressingMode.Relative) },
            { 0x31, new OpCodeDefinition("AND", (cpu, addr, value) => cpu.AND(addr, value, 5), (cpu) => cpu.DecodeIndirectYIndexed(), AddressingMode.IndirectYIndexed) },
            { 0x32, new OpCodeDefinition("AND", (cpu, addr, value) => cpu.AND(addr, value, 5), (cpu) => cpu.DecodeZeroPageIndirect(), AddressingMode.ZeroPageIndirect) },
            { 0x33, new OpCodeDefinition(null, (cpu, addr, value) => cpu.IllegalInstruction(addr, value, 0), (cpu) => cpu.DecodeUndefined(), AddressingMode.Unknown) },
            { 0x34, new OpCodeDefinition("BIT", (cpu, addr, value) => cpu.BIT(addr, value, 4, immediateMode: false), (cpu) => cpu.DecodeZeroPageXIndexed(), AddressingMode.ZeroPageXIndexed) },
            { 0x35, new OpCodeDefinition("AND", (cpu, addr, value) => cpu.AND(addr, value, 4), (cpu) => cpu.DecodeZeroPageXIndexed(), AddressingMode.ZeroPageXIndexed) },
            { 0x36, new OpCodeDefinition("ROL", (cpu, addr, value) => cpu.ROL(addr, value, 6), (cpu) => cpu.DecodeZeroPageXIndexed(), AddressingMode.ZeroPageXIndexed) },
            { 0x37, new OpCodeDefinition("RMB", (cpu, addr, value) => cpu.RMB(addr, value, bit: 3, 5), (cpu) => cpu.DecodeZeroPage(), AddressingMode.ZeroPage) },
            { 0x38, new OpCodeDefinition("SEC", (cpu, addr, value) => cpu.SEC(addr, value, 2), (cpu) => cpu.DecodeImplied(), AddressingMode.Implied) },
            { 0x39, new OpCodeDefinition("AND", (cpu, addr, value) => cpu.AND(addr, value, 4, pageCrossPenalty: 1), (cpu) => cpu.DecodeAbsoluteYIndexed(), AddressingMode.AbsoluteYIndexed) },
            { 0x3a, new OpCodeDefinition("DEC", (cpu, addr, value) => cpu.DEA(addr, value, 2), (cpu) => cpu.DecodeAccumulator(), AddressingMode.Accumulator) },
            { 0x3b, new OpCodeDefinition(null, (cpu, addr, value) => cpu.IllegalInstruction(addr, value, 0), (cpu) => cpu.DecodeUndefined(), AddressingMode.Unknown) },
            { 0x3c, new OpCodeDefinition("BIT", (cpu, addr, value) => cpu.BIT(addr, value, 4, immediateMode: false), (cpu) => cpu.DecodeAbsoluteXIndexed(), AddressingMode.AbsoluteXIndexed) },
            { 0x3d, new OpCodeDefinition("AND", (cpu, addr, value) => cpu.AND(addr, value, 4, pageCrossPenalty: 1), (cpu) => cpu.DecodeAbsoluteXIndexed(), AddressingMode.AbsoluteXIndexed) },
            { 0x3e, new OpCodeDefinition("ROL", (cpu, addr, value) => cpu.ROL(addr, value, 7), (cpu) => cpu.DecodeAbsoluteXIndexed(), AddressingMode.AbsoluteXIndexed) },
            { 0x3f, new OpCodeDefinition("BBR", (cpu, addr, value) => cpu.BBR(addr, value, bit: 3, 5), (cpu) => cpu.DecodeRelative(), AddressingMode.Relative) },

            { 0x40, new OpCodeDefinition("RTI", (cpu, addr, value) => cpu.RTI(addr, value, 6), (cpu) => cpu.DecodeStack(), AddressingMode.Stack) },
            { 0x41, new OpCodeDefinition("EOR", (cpu, addr, value) => cpu.EOR(addr, value, 6), (cpu) => cpu.DecodeXIndexedIndirect(), AddressingMode.XIndexedIndirect) },
            { 0x42, new OpCodeDefinition(null, (cpu, addr, value) => cpu.IllegalInstruction(addr, value, 0), (cpu) => cpu.DecodeUndefined(), AddressingMode.Unknown) },
            { 0x43, new OpCodeDefinition(null, (cpu, addr, value) => cpu.IllegalInstruction(addr, value, 0), (cpu) => cpu.DecodeUndefined(), AddressingMode.Unknown) },
            { 0x44, new OpCodeDefinition(null, (cpu, addr, value) => cpu.IllegalInstruction(addr, value, 0), (cpu) => cpu.DecodeUndefined(), AddressingMode.Unknown) },
            { 0x45, new OpCodeDefinition("EOR", (cpu, addr, value) => cpu.EOR(addr, value, 3), (cpu) => cpu.DecodeZeroPage(), AddressingMode.ZeroPage) },
            { 0x46, new OpCodeDefinition("LSR", (cpu, addr, value) => cpu.LSR(addr, value, 5), (cpu) => cpu.DecodeZeroPage(), AddressingMode.ZeroPage) },
            { 0x47, new OpCodeDefinition("RMB", (cpu, addr, value) => cpu.RMB(addr, value, bit: 4, 5), (cpu) => cpu.DecodeZeroPage(), AddressingMode.ZeroPage) },
            { 0x48, new OpCodeDefinition("PHA", (cpu, addr, value) => cpu.PHA(addr, value, 3), (cpu) => cpu.DecodeStack(), AddressingMode.Stack) },
            { 0x49, new OpCodeDefinition("EOR", (cpu, addr, value) => cpu.EOR(addr, value, 2), (cpu) => cpu.DecodeImmediate(), AddressingMode.Immediate) },
            { 0x4a, new OpCodeDefinition("LSR", (cpu, addr, value) => cpu.LSR_A(addr, value, 2), (cpu) => cpu.DecodeAccumulator(), AddressingMode.Accumulator) },
            { 0x4b, new OpCodeDefinition(null, (cpu, addr, value) => cpu.IllegalInstruction(addr, value, 0), (cpu) => cpu.DecodeUndefined(), AddressingMode.Unknown) },
            { 0x4c, new OpCodeDefinition("JMP", (cpu, addr, value) => cpu.JMP(addr, value, 3), (cpu) => cpu.DecodeAbsolute(), AddressingMode.Absolute) },
            { 0x4d, new OpCodeDefinition("EOR", (cpu, addr, value) => cpu.EOR(addr, value, 4), (cpu) => cpu.DecodeAbsolute(), AddressingMode.Absolute) },
            { 0x4e, new OpCodeDefinition("LSR", (cpu, addr, value) => cpu.LSR(addr, value, 6), (cpu) => cpu.DecodeAbsolute(), AddressingMode.Absolute) },
            { 0x4f, new OpCodeDefinition("BBR", (cpu, addr, value) => cpu.BBR(addr, value, bit: 4, 5), (cpu) => cpu.DecodeRelative(), AddressingMode.Relative) },

            { 0x50, new OpCodeDefinition("BVC", (cpu, addr, value) => cpu.BVC(addr, value, 3, pageCrossPenalty: 1), (cpu) => cpu.DecodeRelative(), AddressingMode.Relative) },
            { 0x51, new OpCodeDefinition("EOR", (cpu, addr, value) => cpu.EOR(addr, value, 5, pageCrossPenalty: 1), (cpu) => cpu.DecodeIndirectYIndexed(), AddressingMode.IndirectYIndexed) },
            { 0x52, new OpCodeDefinition("EOR", (cpu, addr, value) => cpu.EOR(addr, value, 5), (cpu) => cpu.DecodeZeroPageIndirect(), AddressingMode.ZeroPageIndirect) },
            { 0x53, new OpCodeDefinition(null, (cpu, addr, value) => cpu.IllegalInstruction(addr, value, 0), (cpu) => cpu.DecodeUndefined(), AddressingMode.Unknown) },
            { 0x54, new OpCodeDefinition(null, (cpu, addr, value) => cpu.IllegalInstruction(addr, value, 0), (cpu) => cpu.DecodeUndefined(), AddressingMode.Unknown) },
            { 0x55, new OpCodeDefinition("EOR", (cpu, addr, value) => cpu.EOR(addr, value, 4), (cpu) => cpu.DecodeZeroPageXIndexed(), AddressingMode.ZeroPageXIndexed) },
            { 0x56, new OpCodeDefinition("LSR", (cpu, addr, value) => cpu.LSR(addr, value, 6), (cpu) => cpu.DecodeZeroPageXIndexed(), AddressingMode.ZeroPageXIndexed) },
            { 0x57, new OpCodeDefinition("RMB", (cpu, addr, value) => cpu.RMB(addr, value, bit: 5, 5), (cpu) => cpu.DecodeZeroPage(), AddressingMode.ZeroPage) },
            { 0x58, new OpCodeDefinition("CLI", (cpu, addr, value) => cpu.CLI(addr, value, 2), (cpu) => cpu.DecodeImplied(), AddressingMode.Implied) },
            { 0x59, new OpCodeDefinition("EOR", (cpu, addr, value) => cpu.EOR(addr, value, 4, pageCrossPenalty: 1), (cpu) => cpu.DecodeAbsoluteYIndexed(), AddressingMode.AbsoluteYIndexed) },
            { 0x5a, new OpCodeDefinition("PHY", (cpu, addr, value) => cpu.PHY(addr, value, 3), (cpu) => cpu.DecodeStack(), AddressingMode.Stack) },
            { 0x5b, new OpCodeDefinition(null, (cpu, addr, value) => cpu.IllegalInstruction(addr, value, 0), (cpu) => cpu.DecodeUndefined(), AddressingMode.Unknown) },
            { 0x5c, new OpCodeDefinition(null, (cpu, addr, value) => cpu.IllegalInstruction(addr, value, 0), (cpu) => cpu.DecodeUndefined(), AddressingMode.Unknown) },
            { 0x5d, new OpCodeDefinition("EOR", (cpu, addr, value) => cpu.EOR(addr, value, 4, pageCrossPenalty: 1), (cpu) => cpu.DecodeAbsoluteXIndexed(), AddressingMode.AbsoluteXIndexed) },
            { 0x5e, new OpCodeDefinition("LSR", (cpu, addr, value) => cpu.LSR(addr, value, 7), (cpu) => cpu.DecodeAbsoluteXIndexed(), AddressingMode.AbsoluteXIndexed) },
            { 0x5f, new OpCodeDefinition("BBR", (cpu, addr, value) => cpu.BBR(addr, value, bit: 5, 5), (cpu) => cpu.DecodeRelative(), AddressingMode.Relative) },

            { 0x60, new OpCodeDefinition("RTS", (cpu, addr, value) => cpu.RTS(addr, value, 6), (cpu) => cpu.DecodeStack(), AddressingMode.Stack) },
            { 0x61, new OpCodeDefinition("ADC", (cpu, addr, value) => cpu.ADC_CMOS(addr, value, 6), (cpu) => cpu.DecodeXIndexedIndirect(), AddressingMode.XIndexedIndirect) },
            { 0x62, new OpCodeDefinition(null, (cpu, addr, value) => cpu.IllegalInstruction(addr, value, 0), (cpu) => cpu.DecodeUndefined(), AddressingMode.Unknown) },
            { 0x63, new OpCodeDefinition(null, (cpu, addr, value) => cpu.IllegalInstruction(addr, value, 0), (cpu) => cpu.DecodeUndefined(), AddressingMode.Unknown) },
            { 0x64, new OpCodeDefinition("STZ", (cpu, addr, value) => cpu.STZ(addr, value, 3), (cpu) => cpu.DecodeZeroPage(), AddressingMode.ZeroPage) },
            { 0x65, new OpCodeDefinition("ADC", (cpu, addr, value) => cpu.ADC_CMOS(addr, value, 3), (cpu) => cpu.DecodeZeroPage(), AddressingMode.ZeroPage) },
            { 0x66, new OpCodeDefinition("ROR", (cpu, addr, value) => cpu.ROR(addr, value, 5), (cpu) => cpu.DecodeZeroPage(), AddressingMode.ZeroPage) },
            { 0x67, new OpCodeDefinition("RMB", (cpu, addr, value) => cpu.RMB(addr, value, bit: 6, 5), (cpu) => cpu.DecodeZeroPage(), AddressingMode.ZeroPage) },
            { 0x68, new OpCodeDefinition("PLA", (cpu, addr, value) => cpu.PLA(addr, value, 4), (cpu) => cpu.DecodeStack(), AddressingMode.Stack) },
            { 0x69, new OpCodeDefinition("ADC", (cpu, addr, value) => cpu.ADC_CMOS(addr, value, 2), (cpu) => cpu.DecodeImmediate(), AddressingMode.Immediate) },
            { 0x6a, new OpCodeDefinition("ROR", (cpu, addr, value) => cpu.ROR_A(addr, value, 2), (cpu) => cpu.DecodeAccumulator(), AddressingMode.Accumulator) },
            { 0x6b, new OpCodeDefinition(null, (cpu, addr, value) => cpu.IllegalInstruction(addr, value, 0), (cpu) => cpu.DecodeUndefined(), AddressingMode.Unknown) },
            { 0x6c, new OpCodeDefinition("JMP", (cpu, addr, value) => cpu.JMP(addr, value, 6), (cpu) => cpu.DecodeAbsoluteIndirect(), AddressingMode.AbsoluteIndirect) },
            { 0x6d, new OpCodeDefinition("ADC", (cpu, addr, value) => cpu.ADC_CMOS(addr, value, 4), (cpu) => cpu.DecodeAbsolute(), AddressingMode.Absolute) },
            { 0x6e, new OpCodeDefinition("ROR", (cpu, addr, value) => cpu.ROR(addr, value, 6), (cpu) => cpu.DecodeAbsolute(), AddressingMode.Absolute) },
            { 0x6f, new OpCodeDefinition("BBR", (cpu, addr, value) => cpu.BBR(addr, value, bit: 6, 5), (cpu) => cpu.DecodeRelative(), AddressingMode.Relative) },

            { 0x70, new OpCodeDefinition("BVS", (cpu, addr, value) => cpu.BVS(addr, value, 3, pageCrossPenalty: 1), (cpu) => cpu.DecodeRelative(), AddressingMode.Relative) },
            { 0x71, new OpCodeDefinition("ADC", (cpu, addr, value) => cpu.ADC_CMOS(addr, value, 5, pageCrossPenalty: 1), (cpu) => cpu.DecodeIndirectYIndexed(), AddressingMode.IndirectYIndexed) },
            { 0x72, new OpCodeDefinition("ADC", (cpu, addr, value) => cpu.ADC_CMOS(addr, value, 5), (cpu) => cpu.DecodeZeroPageIndirect(), AddressingMode.ZeroPageIndirect) },
            { 0x73, new OpCodeDefinition(null, (cpu, addr, value) => cpu.IllegalInstruction(addr, value, 0), (cpu) => cpu.DecodeUndefined(), AddressingMode.Unknown) },
            { 0x74, new OpCodeDefinition("STZ", (cpu, addr, value) => cpu.STZ(addr, value, 4), (cpu) => cpu.DecodeZeroPageXIndexed(), AddressingMode.ZeroPageXIndexed) },
            { 0x75, new OpCodeDefinition("ADC", (cpu, addr, value) => cpu.ADC_CMOS(addr, value, 4), (cpu) => cpu.DecodeZeroPageXIndexed(), AddressingMode.ZeroPageXIndexed) },
            { 0x76, new OpCodeDefinition("ROR", (cpu, addr, value) => cpu.ROR(addr, value, 6), (cpu) => cpu.DecodeZeroPageXIndexed(), AddressingMode.ZeroPageXIndexed) },
            { 0x77, new OpCodeDefinition("RMB", (cpu, addr, value) => cpu.RMB(addr, value, bit: 7, 5), (cpu) => cpu.DecodeZeroPage(), AddressingMode.ZeroPage) },
            { 0x78, new OpCodeDefinition("SEI", (cpu, addr, value) => cpu.SEI(addr, value, 2), (cpu) => cpu.DecodeImplied(), AddressingMode.Implied) },
            { 0x79, new OpCodeDefinition("ADC", (cpu, addr, value) => cpu.ADC_CMOS(addr, value, 4, pageCrossPenalty: 1), (cpu) => cpu.DecodeAbsoluteYIndexed(), AddressingMode.AbsoluteYIndexed) },
            { 0x7a, new OpCodeDefinition("PLY", (cpu, addr, value) => cpu.PLY(addr, value, 4), (cpu) => cpu.DecodeStack(), AddressingMode.Stack) },
            { 0x7b, new OpCodeDefinition(null, (cpu, addr, value) => cpu.IllegalInstruction(addr, value, 0), (cpu) => cpu.DecodeUndefined(), AddressingMode.Unknown) },
            { 0x7c, new OpCodeDefinition("JMP", (cpu, addr, value) => cpu.JMP(addr, value, 6), (cpu) => cpu.DecodeAbsoluteIndexedIndirect(), AddressingMode.AbsoluteIndexedIndirect) },
            { 0x7d, new OpCodeDefinition("ADC", (cpu, addr, value) => cpu.ADC_CMOS(addr, value, 4, pageCrossPenalty: 1), (cpu) => cpu.DecodeAbsoluteXIndexed(), AddressingMode.AbsoluteXIndexed) },
            { 0x7e, new OpCodeDefinition("ROR", (cpu, addr, value) => cpu.ROR(addr, value, 7), (cpu) => cpu.DecodeAbsoluteXIndexed(), AddressingMode.AbsoluteXIndexed) },
            { 0x7f, new OpCodeDefinition("BBR", (cpu, addr, value) => cpu.BBR(addr, value, bit: 7, 5), (cpu) => cpu.DecodeRelative(), AddressingMode.Relative) },

            { 0x80, new OpCodeDefinition("BRA", (cpu, addr, value) => cpu.BRA(addr, value, 3), (cpu) => cpu.DecodeRelative(), AddressingMode.Relative) },
            { 0x81, new OpCodeDefinition("STA", (cpu, addr, value) => cpu.STA(addr, value, 6), (cpu) => cpu.DecodeXIndexedIndirect(), AddressingMode.XIndexedIndirect) },
            { 0x82, new OpCodeDefinition(null, (cpu, addr, value) => cpu.IllegalInstruction(addr, value, 0), (cpu) => cpu.DecodeUndefined(), AddressingMode.Unknown) },
            { 0x83, new OpCodeDefinition(null, (cpu, addr, value) => cpu.IllegalInstruction(addr, value, 0), (cpu) => cpu.DecodeUndefined(), AddressingMode.Unknown) },
            { 0x84, new OpCodeDefinition("STY", (cpu, addr, value) => cpu.STY(addr, value, 3), (cpu) => cpu.DecodeZeroPage(), AddressingMode.ZeroPage) },
            { 0x85, new OpCodeDefinition("STA", (cpu, addr, value) => cpu.STA(addr, value, 3), (cpu) => cpu.DecodeZeroPage(), AddressingMode.ZeroPage) },
            { 0x86, new OpCodeDefinition("STX", (cpu, addr, value) => cpu.STX(addr, value, 3), (cpu) => cpu.DecodeZeroPage(), AddressingMode.ZeroPage) },
            { 0x87, new OpCodeDefinition("SMB", (cpu, addr, value) => cpu.SMB(addr, value, bit: 0, 5), (cpu) => cpu.DecodeZeroPage(), AddressingMode.ZeroPage) },
            { 0x88, new OpCodeDefinition("DEY", (cpu, addr, value) => cpu.DEY(addr, value, 2), (cpu) => cpu.DecodeImplied(), AddressingMode.Implied) },
            { 0x89, new OpCodeDefinition("BIT", (cpu, addr, value) => cpu.BIT(addr, value, 2, immediateMode: true), (cpu) => cpu.DecodeImmediate(), AddressingMode.Immediate) },
            { 0x8a, new OpCodeDefinition("TXA", (cpu, addr, value) => cpu.TXA(addr, value, 2), (cpu) => cpu.DecodeImplied(), AddressingMode.Implied) },
            { 0x8b, new OpCodeDefinition(null, (cpu, addr, value) => cpu.IllegalInstruction(addr, value, 0), (cpu) => cpu.DecodeUndefined(), AddressingMode.Unknown) },
            { 0x8c, new OpCodeDefinition("STY", (cpu, addr, value) => cpu.STY(addr, value, 4), (cpu) => cpu.DecodeAbsolute(), AddressingMode.Absolute) },
            { 0x8d, new OpCodeDefinition("STA", (cpu, addr, value) => cpu.STA(addr, value, 4), (cpu) => cpu.DecodeAbsolute(), AddressingMode.Absolute) },
            { 0x8e, new OpCodeDefinition("STX", (cpu, addr, value) => cpu.STX(addr, value, 4), (cpu) => cpu.DecodeAbsolute(), AddressingMode.Absolute) },
            { 0x8f, new OpCodeDefinition("BBS", (cpu, addr, value) => cpu.BBS(addr, value, bit: 0, 5), (cpu) => cpu.DecodeRelative(), AddressingMode.Relative) },

            { 0x90, new OpCodeDefinition("BCC", (cpu, addr, value) => cpu.BCC(addr, value, 3, pageCrossPenalty: 1), (cpu) => cpu.DecodeRelative(), AddressingMode.Relative) },
            { 0x91, new OpCodeDefinition("STA", (cpu, addr, value) => cpu.STA(addr, value, 6), (cpu) => cpu.DecodeIndirectYIndexed(), AddressingMode.IndirectYIndexed) },
            { 0x92, new OpCodeDefinition("STA", (cpu, addr, value) => cpu.STA(addr, value, 5), (cpu) => cpu.DecodeZeroPageIndirect(), AddressingMode.ZeroPageIndirect) },
            { 0x93, new OpCodeDefinition(null, (cpu, addr, value) => cpu.IllegalInstruction(addr, value, 0), (cpu) => cpu.DecodeUndefined(), AddressingMode.Unknown) },
            { 0x94, new OpCodeDefinition("STY", (cpu, addr, value) => cpu.STY(addr, value, 4), (cpu) => cpu.DecodeZeroPageXIndexed(), AddressingMode.ZeroPageXIndexed) },
            { 0x95, new OpCodeDefinition("STA", (cpu, addr, value) => cpu.STA(addr, value, 4), (cpu) => cpu.DecodeZeroPageXIndexed(), AddressingMode.ZeroPageXIndexed) },
            { 0x96, new OpCodeDefinition("STX", (cpu, addr, value) => cpu.STX(addr, value, 4), (cpu) => cpu.DecodeZeroPageYIndexed(), AddressingMode.ZeroPageYIndexed) },
            { 0x97, new OpCodeDefinition("SMB", (cpu, addr, value) => cpu.SMB(addr, value, bit: 1, 5), (cpu) => cpu.DecodeZeroPage(), AddressingMode.ZeroPage) },
            { 0x98, new OpCodeDefinition("TYA", (cpu, addr, value) => cpu.TYA(addr, value, 2), (cpu) => cpu.DecodeImplied(), AddressingMode.Implied) },
            { 0x99, new OpCodeDefinition("STA", (cpu, addr, value) => cpu.STA(addr, value, 5), (cpu) => cpu.DecodeAbsoluteYIndexed(), AddressingMode.AbsoluteYIndexed) },
            { 0x9a, new OpCodeDefinition("TXS", (cpu, addr, value) => cpu.TXS(addr, value, 2), (cpu) => cpu.DecodeImplied(), AddressingMode.Implied) },
            { 0x9b, new OpCodeDefinition(null, (cpu, addr, value) => cpu.IllegalInstruction(addr, value, 0), (cpu) => cpu.DecodeUndefined(), AddressingMode.Unknown) },
            { 0x9c, new OpCodeDefinition("STZ", (cpu, addr, value) => cpu.STZ(addr, value, 4), (cpu) => cpu.DecodeAbsolute(), AddressingMode.Absolute) },
            { 0x9d, new OpCodeDefinition("STA", (cpu, addr, value) => cpu.STA(addr, value, 5), (cpu) => cpu.DecodeAbsoluteXIndexed(), AddressingMode.AbsoluteXIndexed) },
            { 0x9e, new OpCodeDefinition("STZ", (cpu, addr, value) => cpu.STZ(addr, value, 5), (cpu) => cpu.DecodeAbsoluteXIndexed(), AddressingMode.AbsoluteXIndexed) },
            { 0x9f, new OpCodeDefinition("BBS", (cpu, addr, value) => cpu.BBS(addr, value, bit: 1, 5), (cpu) => cpu.DecodeRelative(), AddressingMode.Relative) },

            { 0xa0, new OpCodeDefinition("LDY", (cpu, addr, value) => cpu.LDY(addr, value, 2), (cpu) => cpu.DecodeImmediate(), AddressingMode.Immediate) },
            { 0xa1, new OpCodeDefinition("LDA", (cpu, addr, value) => cpu.LDA(addr, value, 6), (cpu) => cpu.DecodeXIndexedIndirect(), AddressingMode.XIndexedIndirect) },
            { 0xa2, new OpCodeDefinition("LDX", (cpu, addr, value) => cpu.LDX(addr, value, 2), (cpu) => cpu.DecodeImmediate(), AddressingMode.Immediate) },
            { 0xa3, new OpCodeDefinition(null, (cpu, addr, value) => cpu.IllegalInstruction(addr, value, 0), (cpu) => cpu.DecodeUndefined(), AddressingMode.Unknown) },
            { 0xa4, new OpCodeDefinition("LDY", (cpu, addr, value) => cpu.LDY(addr, value, 3), (cpu) => cpu.DecodeZeroPage(), AddressingMode.ZeroPage) },
            { 0xa5, new OpCodeDefinition("LDA", (cpu, addr, value) => cpu.LDA(addr, value, 3), (cpu) => cpu.DecodeZeroPage(), AddressingMode.ZeroPage) },
            { 0xa6, new OpCodeDefinition("LDX", (cpu, addr, value) => cpu.LDX(addr, value, 3), (cpu) => cpu.DecodeZeroPage(), AddressingMode.ZeroPage) },
            { 0xa7, new OpCodeDefinition("SMB", (cpu, addr, value) => cpu.SMB(addr, value, bit: 2, 5), (cpu) => cpu.DecodeZeroPage(), AddressingMode.ZeroPage) },
            { 0xa8, new OpCodeDefinition("TAY", (cpu, addr, value) => cpu.TAY(addr, value, 2), (cpu) => cpu.DecodeImplied(), AddressingMode.Implied) },
            { 0xa9, new OpCodeDefinition("LDA", (cpu, addr, value) => cpu.LDA(addr, value, 2), (cpu) => cpu.DecodeImmediate(), AddressingMode.Immediate) },
            { 0xaa, new OpCodeDefinition("TAX", (cpu, addr, value) => cpu.TAX(addr, value, 2), (cpu) => cpu.DecodeImplied(), AddressingMode.Implied) },
            { 0xab, new OpCodeDefinition(null, (cpu, addr, value) => cpu.IllegalInstruction(addr, value, 0), (cpu) => cpu.DecodeUndefined(), AddressingMode.Unknown) },
            { 0xac, new OpCodeDefinition("LDY", (cpu, addr, value) => cpu.LDY(addr, value, 4), (cpu) => cpu.DecodeAbsolute(), AddressingMode.Absolute) },
            { 0xad, new OpCodeDefinition("LDA", (cpu, addr, value) => cpu.LDA(addr, value, 4), (cpu) => cpu.DecodeAbsolute(), AddressingMode.Absolute) },
            { 0xae, new OpCodeDefinition("LDX", (cpu, addr, value) => cpu.LDX(addr, value, 4), (cpu) => cpu.DecodeAbsolute(), AddressingMode.Absolute) },
            { 0xaf, new OpCodeDefinition("BBS", (cpu, addr, value) => cpu.BBS(addr, value, bit: 2, 5), (cpu) => cpu.DecodeRelative(), AddressingMode.Relative) },

            { 0xb0, new OpCodeDefinition("BCS", (cpu, addr, value) => cpu.BCS(addr, value, 3, pageCrossPenalty: 1), (cpu) => cpu.DecodeRelative(), AddressingMode.Relative) },
            { 0xb1, new OpCodeDefinition("LDA", (cpu, addr, value) => cpu.LDA(addr, value, 5, pageCrossPenalty: 1), (cpu) => cpu.DecodeIndirectYIndexed(), AddressingMode.IndirectYIndexed) },
            { 0xb2, new OpCodeDefinition("LDA", (cpu, addr, value) => cpu.LDA(addr, value, 5), (cpu) => cpu.DecodeZeroPageIndirect(), AddressingMode.ZeroPageIndirect) },
            { 0xb3, new OpCodeDefinition(null, (cpu, addr, value) => cpu.IllegalInstruction(addr, value, 0), (cpu) => cpu.DecodeUndefined(), AddressingMode.Unknown) },
            { 0xb4, new OpCodeDefinition("LDY", (cpu, addr, value) => cpu.LDY(addr, value, 4), (cpu) => cpu.DecodeZeroPageXIndexed(), AddressingMode.ZeroPageXIndexed) },
            { 0xb5, new OpCodeDefinition("LDA", (cpu, addr, value) => cpu.LDA(addr, value, 4), (cpu) => cpu.DecodeZeroPageXIndexed(), AddressingMode.ZeroPageXIndexed) },
            { 0xb6, new OpCodeDefinition("LDX", (cpu, addr, value) => cpu.LDX(addr, value, 4), (cpu) => cpu.DecodeZeroPageYIndexed(), AddressingMode.ZeroPageYIndexed) },
            { 0xb7, new OpCodeDefinition("SMB", (cpu, addr, value) => cpu.SMB(addr, value, bit: 3, 5), (cpu) => cpu.DecodeZeroPage(), AddressingMode.ZeroPage) },
            { 0xb8, new OpCodeDefinition("CLV", (cpu, addr, value) => cpu.CLV(addr, value, 2), (cpu) => cpu.DecodeImplied(), AddressingMode.Implied) },
            { 0xb9, new OpCodeDefinition("LDA", (cpu, addr, value) => cpu.LDA(addr, value, 4, pageCrossPenalty: 1), (cpu) => cpu.DecodeAbsoluteYIndexed(), AddressingMode.AbsoluteYIndexed) },
            { 0xba, new OpCodeDefinition("TSX", (cpu, addr, value) => cpu.TSX(addr, value, 2), (cpu) => cpu.DecodeImplied(), AddressingMode.Implied) },
            { 0xbb, new OpCodeDefinition(null, (cpu, addr, value) => cpu.IllegalInstruction(addr, value, 0), (cpu) => cpu.DecodeUndefined(), AddressingMode.Unknown) },
            { 0xbc, new OpCodeDefinition("LDY", (cpu, addr, value) => cpu.LDY(addr, value, 4, pageCrossPenalty: 1), (cpu) => cpu.DecodeAbsoluteXIndexed(), AddressingMode.AbsoluteXIndexed) },
            { 0xbd, new OpCodeDefinition("LDA", (cpu, addr, value) => cpu.LDA(addr, value, 4, pageCrossPenalty: 1), (cpu) => cpu.DecodeAbsoluteXIndexed(), AddressingMode.AbsoluteXIndexed) },
            { 0xbe, new OpCodeDefinition("LDX", (cpu, addr, value) => cpu.LDX(addr, value, 4, pageCrossPenalty: 1), (cpu) => cpu.DecodeAbsoluteYIndexed(), AddressingMode.AbsoluteYIndexed) },
            { 0xbf, new OpCodeDefinition("BBS", (cpu, addr, value) => cpu.BBS(addr, value, bit: 3, 5), (cpu) => cpu.DecodeRelative(), AddressingMode.Relative) },

            { 0xc0, new OpCodeDefinition("CPY", (cpu, addr, value) => cpu.CPY(addr, value, 2), (cpu) => cpu.DecodeImmediate(), AddressingMode.Immediate) },
            { 0xc1, new OpCodeDefinition("CMP", (cpu, addr, value) => cpu.CMP(addr, value, 6), (cpu) => cpu.DecodeXIndexedIndirect(), AddressingMode.XIndexedIndirect) },
            { 0xc2, new OpCodeDefinition(null, (cpu, addr, value) => cpu.IllegalInstruction(addr, value, 0), (cpu) => cpu.DecodeUndefined(), AddressingMode.Unknown) },
            { 0xc3, new OpCodeDefinition(null, (cpu, addr, value) => cpu.IllegalInstruction(addr, value, 0), (cpu) => cpu.DecodeUndefined(), AddressingMode.Unknown) },
            { 0xc4, new OpCodeDefinition("CPY", (cpu, addr, value) => cpu.CPY(addr, value, 3), (cpu) => cpu.DecodeZeroPage(), AddressingMode.ZeroPage) },
            { 0xc5, new OpCodeDefinition("CMP", (cpu, addr, value) => cpu.CMP(addr, value, 3), (cpu) => cpu.DecodeZeroPage(), AddressingMode.ZeroPage) },
            { 0xc6, new OpCodeDefinition("DEC", (cpu, addr, value) => cpu.DEC(addr, value, 5), (cpu) => cpu.DecodeZeroPage(), AddressingMode.ZeroPage) },
            { 0xc7, new OpCodeDefinition("SMB", (cpu, addr, value) => cpu.SMB(addr, value, bit: 4, 5), (cpu) => cpu.DecodeZeroPage(), AddressingMode.ZeroPage) },
            { 0xc8, new OpCodeDefinition("INY", (cpu, addr, value) => cpu.INY(addr, value, 2), (cpu) => cpu.DecodeImplied(), AddressingMode.Implied) },
            { 0xc9, new OpCodeDefinition("CMP", (cpu, addr, value) => cpu.CMP(addr, value, 2), (cpu) => cpu.DecodeImmediate(), AddressingMode.Immediate) },
            { 0xca, new OpCodeDefinition("DEX", (cpu, addr, value) => cpu.DEX(addr, value, 2), (cpu) => cpu.DecodeImplied(), AddressingMode.Implied) },
            { 0xcb, new OpCodeDefinition("WAI", (cpu, addr, value) => cpu.WAI(addr, value, 0), (cpu) => cpu.DecodeImplied(), AddressingMode.Implied) },
            { 0xcc, new OpCodeDefinition("CPY", (cpu, addr, value) => cpu.CPY(addr, value, 4), (cpu) => cpu.DecodeAbsolute(), AddressingMode.Absolute) },
            { 0xcd, new OpCodeDefinition("CMP", (cpu, addr, value) => cpu.CMP(addr, value, 4), (cpu) => cpu.DecodeAbsolute(), AddressingMode.Absolute) },
            { 0xce, new OpCodeDefinition("DEC", (cpu, addr, value) => cpu.DEC(addr, value, 6), (cpu) => cpu.DecodeAbsolute(), AddressingMode.Absolute) },
            { 0xcf, new OpCodeDefinition("BBS", (cpu, addr, value) => cpu.BBS(addr, value, bit: 4, 5), (cpu) => cpu.DecodeRelative(), AddressingMode.Relative) },

            { 0xd0, new OpCodeDefinition("BNE", (cpu, addr, value) => cpu.BNE(addr, value, 3, pageCrossPenalty: 1), (cpu) => cpu.DecodeRelative(), AddressingMode.Relative) },
            { 0xd1, new OpCodeDefinition("CMP", (cpu, addr, value) => cpu.CMP(addr, value, 5, pageCrossPenalty: 1), (cpu) => cpu.DecodeIndirectYIndexed(), AddressingMode.IndirectYIndexed) },
            { 0xd2, new OpCodeDefinition("CMP", (cpu, addr, value) => cpu.CMP(addr, value, 5), (cpu) => cpu.DecodeZeroPageIndirect(), AddressingMode.ZeroPageIndirect) },
            { 0xd3, new OpCodeDefinition(null, (cpu, addr, value) => cpu.IllegalInstruction(addr, value, 0), (cpu) => cpu.DecodeUndefined(), AddressingMode.Unknown) },
            { 0xd4, new OpCodeDefinition(null, (cpu, addr, value) => cpu.IllegalInstruction(addr, value, 0), (cpu) => cpu.DecodeUndefined(), AddressingMode.Unknown) },
            { 0xd5, new OpCodeDefinition("CMP", (cpu, addr, value) => cpu.CMP(addr, value, 4), (cpu) => cpu.DecodeZeroPageXIndexed(), AddressingMode.ZeroPageXIndexed) },
            { 0xd6, new OpCodeDefinition("DEC", (cpu, addr, value) => cpu.DEC(addr, value, 6), (cpu) => cpu.DecodeZeroPageXIndexed(), AddressingMode.ZeroPageXIndexed) },
            { 0xd7, new OpCodeDefinition("SMB", (cpu, addr, value) => cpu.SMB(addr, value, bit: 5, 5), (cpu) => cpu.DecodeZeroPage(), AddressingMode.ZeroPage) },
            { 0xd8, new OpCodeDefinition("CLD", (cpu, addr, value) => cpu.CLD(addr, value, 2), (cpu) => cpu.DecodeImplied(), AddressingMode.Implied) },
            { 0xd9, new OpCodeDefinition("CMP", (cpu, addr, value) => cpu.CMP(addr, value, 4, pageCrossPenalty: 1), (cpu) => cpu.DecodeAbsoluteYIndexed(), AddressingMode.AbsoluteYIndexed) },
            { 0xda, new OpCodeDefinition("PHX", (cpu, addr, value) => cpu.PHX(addr, value, 3), (cpu) => cpu.DecodeStack(), AddressingMode.Stack) },
            { 0xdb, new OpCodeDefinition("STP", (cpu, addr, value) => cpu.STP(addr, value, 0), (cpu) => cpu.DecodeImplied(), AddressingMode.Implied) },
            { 0xdc, new OpCodeDefinition(null, (cpu, addr, value) => cpu.IllegalInstruction(addr, value, 0), (cpu) => cpu.DecodeUndefined(), AddressingMode.Unknown) },
            { 0xdd, new OpCodeDefinition("CMP", (cpu, addr, value) => cpu.CMP(addr, value, 4, pageCrossPenalty: 1), (cpu) => cpu.DecodeAbsoluteXIndexed(), AddressingMode.AbsoluteXIndexed) },
            { 0xde, new OpCodeDefinition("DEC", (cpu, addr, value) => cpu.DEC(addr, value, 7), (cpu) => cpu.DecodeAbsoluteXIndexed(), AddressingMode.AbsoluteXIndexed) },
            { 0xdf, new OpCodeDefinition("BBS", (cpu, addr, value) => cpu.BBS(addr, value, bit: 5, 5), (cpu) => cpu.DecodeRelative(), AddressingMode.Relative) },

            { 0xe0, new OpCodeDefinition("CPX", (cpu, addr, value) => cpu.CPX(addr, value, 2), (cpu) => cpu.DecodeImmediate(), AddressingMode.Immediate) },
            { 0xe1, new OpCodeDefinition("SBC", (cpu, addr, value) => cpu.SBC_CMOS(addr, value, 6), (cpu) => cpu.DecodeXIndexedIndirect(), AddressingMode.XIndexedIndirect) },
            { 0xe2, new OpCodeDefinition(null, (cpu, addr, value) => cpu.IllegalInstruction(addr, value, 0), (cpu) => cpu.DecodeUndefined(), AddressingMode.Unknown) },
            { 0xe3, new OpCodeDefinition(null, (cpu, addr, value) => cpu.IllegalInstruction(addr, value, 0), (cpu) => cpu.DecodeUndefined(), AddressingMode.Unknown) },
            { 0xe4, new OpCodeDefinition("CPX", (cpu, addr, value) => cpu.CPX(addr, value, 3), (cpu) => cpu.DecodeZeroPage(), AddressingMode.ZeroPage) },
            { 0xe5, new OpCodeDefinition("SBC", (cpu, addr, value) => cpu.SBC_CMOS(addr, value, 3), (cpu) => cpu.DecodeZeroPage(), AddressingMode.ZeroPage) },
            { 0xe6, new OpCodeDefinition("INC", (cpu, addr, value) => cpu.INC(addr, value, 5), (cpu) => cpu.DecodeZeroPage(), AddressingMode.ZeroPage) },
            { 0xe7, new OpCodeDefinition("SMB", (cpu, addr, value) => cpu.SMB(addr, value, bit: 6, 5), (cpu) => cpu.DecodeZeroPage(), AddressingMode.ZeroPage) },
            { 0xe8, new OpCodeDefinition("INX", (cpu, addr, value) => cpu.INX(addr, value, 2), (cpu) => cpu.DecodeImplied(), AddressingMode.Implied) },
            { 0xe9, new OpCodeDefinition("SBC", (cpu, addr, value) => cpu.SBC_CMOS(addr, value, 2), (cpu) => cpu.DecodeImmediate(), AddressingMode.Immediate) },
            { 0xea, new OpCodeDefinition("NOP", (cpu, addr, value) => cpu.NOP(addr, value, 2), (cpu) => cpu.DecodeImplied(), AddressingMode.Implied) },
            { 0xeb, new OpCodeDefinition(null, (cpu, addr, value) => cpu.IllegalInstruction(addr, value, 0), (cpu) => cpu.DecodeUndefined(), AddressingMode.Unknown) },
            { 0xec, new OpCodeDefinition("CPX", (cpu, addr, value) => cpu.CPX(addr, value, 4), (cpu) => cpu.DecodeAbsolute(), AddressingMode.Absolute) },
            { 0xed, new OpCodeDefinition("SBC", (cpu, addr, value) => cpu.SBC_CMOS(addr, value, 4), (cpu) => cpu.DecodeAbsolute(), AddressingMode.Absolute) },
            { 0xee, new OpCodeDefinition("INC", (cpu, addr, value) => cpu.INC(addr, value, 6), (cpu) => cpu.DecodeAbsolute(), AddressingMode.Absolute) },
            { 0xef, new OpCodeDefinition("BBS", (cpu, addr, value) => cpu.BBS(addr, value, bit: 6, 5), (cpu) => cpu.DecodeRelative(), AddressingMode.Relative) },

            { 0xf0, new OpCodeDefinition("BEQ", (cpu, addr, value) => cpu.BEQ(addr, value, 3, pageCrossPenalty: 1), (cpu) => cpu.DecodeRelative(), AddressingMode.Relative) },
            { 0xf1, new OpCodeDefinition("SBC", (cpu, addr, value) => cpu.SBC_CMOS(addr, value, 5, pageCrossPenalty: 1), (cpu) => cpu.DecodeIndirectYIndexed(), AddressingMode.IndirectYIndexed) },
            { 0xf2, new OpCodeDefinition("SBC", (cpu, addr, value) => cpu.SBC_CMOS(addr, value, 5), (cpu) => cpu.DecodeZeroPageIndirect(), AddressingMode.ZeroPageIndirect) },
            { 0xf3, new OpCodeDefinition(null, (cpu, addr, value) => cpu.IllegalInstruction(addr, value, 0), (cpu) => cpu.DecodeUndefined(), AddressingMode.Unknown) },
            { 0xf4, new OpCodeDefinition(null, (cpu, addr, value) => cpu.IllegalInstruction(addr, value, 0), (cpu) => cpu.DecodeUndefined(), AddressingMode.Unknown) },
            { 0xf5, new OpCodeDefinition("SBC", (cpu, addr, value) => cpu.SBC_CMOS(addr, value, 4), (cpu) => cpu.DecodeZeroPageXIndexed(), AddressingMode.ZeroPageXIndexed) },
            { 0xf6, new OpCodeDefinition("INC", (cpu, addr, value) => cpu.INC(addr, value, 6), (cpu) => cpu.DecodeZeroPageXIndexed(), AddressingMode.ZeroPageXIndexed) },
            { 0xf7, new OpCodeDefinition("SMB", (cpu, addr, value) => cpu.SMB(addr, value, bit: 7, 5), (cpu) => cpu.DecodeZeroPage(), AddressingMode.ZeroPage) },
            { 0xf8, new OpCodeDefinition("SED", (cpu, addr, value) => cpu.SED(addr, value, 2), (cpu) => cpu.DecodeImplied(), AddressingMode.Implied) },
            { 0xf9, new OpCodeDefinition("SBC", (cpu, addr, value) => cpu.SBC_CMOS(addr, value, 4, pageCrossPenalty: 1), (cpu) => cpu.DecodeAbsoluteYIndexed(), AddressingMode.AbsoluteYIndexed) },
            { 0xfa, new OpCodeDefinition("PLX", (cpu, addr, value) => cpu.PLX(addr, value, 4), (cpu) => cpu.DecodeImplied(), AddressingMode.Implied) },
            { 0xfb, new OpCodeDefinition(null, (cpu, addr, value) => cpu.IllegalInstruction(addr, value, 0), (cpu) => cpu.DecodeUndefined(), AddressingMode.Unknown) },
            { 0xfc, new OpCodeDefinition(null, (cpu, addr, value) => cpu.IllegalInstruction(addr, value, 0), (cpu) => cpu.DecodeUndefined(), AddressingMode.Unknown) },
            { 0xfd, new OpCodeDefinition("SBC", (cpu, addr, value) => cpu.SBC_CMOS(addr, value, 4, pageCrossPenalty: 1), (cpu) => cpu.DecodeAbsoluteXIndexed(), AddressingMode.AbsoluteXIndexed) },
            { 0xfe, new OpCodeDefinition("INC", (cpu, addr, value) => cpu.INC(addr, value, 7), (cpu) => cpu.DecodeAbsoluteXIndexed(), AddressingMode.AbsoluteXIndexed) },
            { 0xff, new OpCodeDefinition("BBS", (cpu, addr, value) => cpu.BBS(addr, value, bit: 7, 5), (cpu) => cpu.DecodeRelative(), AddressingMode.Relative) },
        };

        public static readonly Dictionary<byte, OpCodeDefinition> OpCode6502 = new()
        {
            { 0x00, new OpCodeDefinition("BRK", (cpu, addr, value) => cpu.BRK(addr, value, 7), (cpu) => cpu.DecodeStack(), AddressingMode.Stack) },
            { 0x01, new OpCodeDefinition("ORA", (cpu, addr, value) => cpu.ORA(addr, value, 6), (cpu) => cpu.DecodeXIndexedIndirect(), AddressingMode.XIndexedIndirect) },
            { 0x02, new OpCodeDefinition(null, (cpu, addr, value) => cpu.IllegalInstruction(addr, value, 0), (cpu) => cpu.DecodeUndefined(), AddressingMode.Unknown) },
            { 0x03, new OpCodeDefinition(null, (cpu, addr, value) => cpu.IllegalInstruction(addr, value, 0), (cpu) => cpu.DecodeUndefined(), AddressingMode.Unknown) },
            { 0x04, new OpCodeDefinition(null, (cpu, addr, value) => cpu.IllegalInstruction(addr, value, 5), (cpu) => cpu.DecodeUndefined(), AddressingMode.Unknown) },
            { 0x05, new OpCodeDefinition("ORA", (cpu, addr, value) => cpu.ORA(addr, value, 3), (cpu) => cpu.DecodeZeroPage(), AddressingMode.ZeroPage) },
            { 0x06, new OpCodeDefinition("ASL", (cpu, addr, value) => cpu.ASL(addr, value, 5), (cpu) => cpu.DecodeZeroPage(), AddressingMode.ZeroPage) },
            { 0x07, new OpCodeDefinition(null, (cpu, addr, value) => cpu.IllegalInstruction(addr, value, 5), (cpu) => cpu.DecodeUndefined(), AddressingMode.Unknown) },
            { 0x08, new OpCodeDefinition("PHP", (cpu, addr, value) => cpu.PHP(addr, value, 3), (cpu) => cpu.DecodeStack(), AddressingMode.Stack) },
            { 0x09, new OpCodeDefinition("ORA", (cpu, addr, value) => cpu.ORA(addr, value, 2), (cpu) => cpu.DecodeImmediate(), AddressingMode.Immediate) },
            { 0x0a, new OpCodeDefinition("ASL", (cpu, addr, value) => cpu.ASL_A(addr, value, 2), (cpu) => cpu.DecodeAccumulator(), AddressingMode.Accumulator) },
            { 0x0b, new OpCodeDefinition(null, (cpu, addr, value) => cpu.IllegalInstruction(addr, value, 0), (cpu) => cpu.DecodeUndefined(), AddressingMode.Unknown) },
            { 0x0c, new OpCodeDefinition(null, (cpu, addr, value) => cpu.IllegalInstruction(addr, value, 6), (cpu) => cpu.DecodeUndefined(), AddressingMode.Unknown) },
            { 0x0d, new OpCodeDefinition("ORA", (cpu, addr, value) => cpu.ORA(addr, value, 4), (cpu) => cpu.DecodeAbsolute(), AddressingMode.Absolute) },
            { 0x0e, new OpCodeDefinition("ASL", (cpu, addr, value) => cpu.ASL(addr, value, 6), (cpu) => cpu.DecodeAbsolute(), AddressingMode.Absolute) },
            { 0x0f, new OpCodeDefinition(null, (cpu, addr, value) => cpu.IllegalInstruction(addr, value, 5), (cpu) => cpu.DecodeUndefined(), AddressingMode.Unknown) },

            { 0x10, new OpCodeDefinition("BPL", (cpu, addr, value) => cpu.BPL(addr, value, 3, pageCrossPenalty: 1), (cpu) => cpu.DecodeRelative(), AddressingMode.Relative) },
            { 0x11, new OpCodeDefinition("ORA", (cpu, addr, value) => cpu.ORA(addr, value, 5), (cpu) => cpu.DecodeIndirectYIndexed(), AddressingMode.IndirectYIndexed) },
            { 0x12, new OpCodeDefinition(null, (cpu, addr, value) => cpu.IllegalInstruction(addr, value, 5), (cpu) => cpu.DecodeUndefined(), AddressingMode.Unknown) },
            { 0x13, new OpCodeDefinition(null, (cpu, addr, value) => cpu.IllegalInstruction(addr, value, 0), (cpu) => cpu.DecodeUndefined(), AddressingMode.Unknown) },
            { 0x14, new OpCodeDefinition(null, (cpu, addr, value) => cpu.IllegalInstruction(addr, value, 5), (cpu) => cpu.DecodeUndefined(), AddressingMode.Unknown) },
            { 0x15, new OpCodeDefinition("ORA", (cpu, addr, value) => cpu.ORA(addr, value, 4), (cpu) => cpu.DecodeZeroPageXIndexed(), AddressingMode.ZeroPageXIndexed) },
            { 0x16, new OpCodeDefinition("ASL", (cpu, addr, value) => cpu.ASL(addr, value, 6), (cpu) => cpu.DecodeZeroPageXIndexed(), AddressingMode.ZeroPageXIndexed) },
            { 0x17, new OpCodeDefinition(null, (cpu, addr, value) => cpu.IllegalInstruction(addr, value, 5), (cpu) => cpu.DecodeUndefined(), AddressingMode.Unknown) },
            { 0x18, new OpCodeDefinition("CLC", (cpu, addr, value) => cpu.CLC(addr, value, 2), (cpu) => cpu.DecodeImplied(), AddressingMode.Implied) },
            { 0x19, new OpCodeDefinition("ORA", (cpu, addr, value) => cpu.ORA(addr, value, 4, pageCrossPenalty: 1), (cpu) => cpu.DecodeAbsoluteYIndexed(), AddressingMode.AbsoluteYIndexed) },
            { 0x1a, new OpCodeDefinition(null, (cpu, addr, value) => cpu.IllegalInstruction(addr, value, 2), (cpu) => cpu.DecodeUndefined(), AddressingMode.Unknown) },
            { 0x1b, new OpCodeDefinition(null, (cpu, addr, value) => cpu.IllegalInstruction(addr, value, 0), (cpu) => cpu.DecodeUndefined(), AddressingMode.Unknown) },
            { 0x1c, new OpCodeDefinition(null, (cpu, addr, value) => cpu.IllegalInstruction(addr, value, 6), (cpu) => cpu.DecodeUndefined(), AddressingMode.Unknown) },
            { 0x1d, new OpCodeDefinition("ORA", (cpu, addr, value) => cpu.ORA(addr, value, 4, pageCrossPenalty: 1), (cpu) => cpu.DecodeAbsoluteXIndexed(), AddressingMode.AbsoluteXIndexed) },
            { 0x1e, new OpCodeDefinition("ASL", (cpu, addr, value) => cpu.ASL(addr, value, 7), (cpu) => cpu.DecodeAbsoluteXIndexed(), AddressingMode.AbsoluteXIndexed) },
            { 0x1f, new OpCodeDefinition(null, (cpu, addr, value) => cpu.IllegalInstruction(addr, value, 5), (cpu) => cpu.DecodeUndefined(), AddressingMode.Unknown) },

            { 0x20, new OpCodeDefinition("JSR", (cpu, addr, value) => cpu.JSR(addr, value, 6), (cpu) => cpu.DecodeAbsolute(), AddressingMode.Absolute) },
            { 0x21, new OpCodeDefinition("AND", (cpu, addr, value) => cpu.AND(addr, value, 6), (cpu) => cpu.DecodeXIndexedIndirect(), AddressingMode.XIndexedIndirect) },
            { 0x22, new OpCodeDefinition(null, (cpu, addr, value) => cpu.IllegalInstruction(addr, value, 0), (cpu) => cpu.DecodeUndefined(), AddressingMode.Unknown) },
            { 0x23, new OpCodeDefinition(null, (cpu, addr, value) => cpu.IllegalInstruction(addr, value, 0), (cpu) => cpu.DecodeUndefined(), AddressingMode.Unknown) },
            { 0x24, new OpCodeDefinition("BIT", (cpu, addr, value) => cpu.BIT(addr, value, 3, immediateMode: false), (cpu) => cpu.DecodeZeroPage(), AddressingMode.ZeroPage) },
            { 0x25, new OpCodeDefinition("AND", (cpu, addr, value) => cpu.AND(addr, value, 3), (cpu) => cpu.DecodeZeroPage(), AddressingMode.ZeroPage) },
            { 0x26, new OpCodeDefinition("ROL", (cpu, addr, value) => cpu.ROL(addr, value, 5), (cpu) => cpu.DecodeZeroPage(), AddressingMode.ZeroPage) },
            { 0x27, new OpCodeDefinition(null, (cpu, addr, value) => cpu.IllegalInstruction(addr, value, 5), (cpu) => cpu.DecodeUndefined(), AddressingMode.Unknown) },
            { 0x28, new OpCodeDefinition("PLP", (cpu, addr, value) => cpu.PLP(addr, value, 4), (cpu) => cpu.DecodeStack(), AddressingMode.Stack) },
            { 0x29, new OpCodeDefinition("AND", (cpu, addr, value) => cpu.AND(addr, value, 2), (cpu) => cpu.DecodeImmediate(), AddressingMode.Immediate) },
            { 0x2a, new OpCodeDefinition("ROL", (cpu, addr, value) => cpu.ROL_A(addr, value, 2), (cpu) => cpu.DecodeAccumulator(), AddressingMode.Accumulator) },
            { 0x2b, new OpCodeDefinition(null, (cpu, addr, value) => cpu.IllegalInstruction(addr, value, 0), (cpu) => cpu.DecodeUndefined(), AddressingMode.Unknown) },
            { 0x2c, new OpCodeDefinition("BIT", (cpu, addr, value) => cpu.BIT(addr, value, 4, immediateMode: false), (cpu) => cpu.DecodeAbsolute(), AddressingMode.Absolute) },
            { 0x2d, new OpCodeDefinition("AND", (cpu, addr, value) => cpu.AND(addr, value, 4), (cpu) => cpu.DecodeAbsolute(), AddressingMode.Absolute) },
            { 0x2e, new OpCodeDefinition("ROL", (cpu, addr, value) => cpu.ROL(addr, value, 6), (cpu) => cpu.DecodeAbsolute(), AddressingMode.Absolute) },
            { 0x2f, new OpCodeDefinition(null, (cpu, addr, value) => cpu.IllegalInstruction(addr, value, 5), (cpu) => cpu.DecodeUndefined(), AddressingMode.Unknown) },

            { 0x30, new OpCodeDefinition("BMI", (cpu, addr, value) => cpu.BMI(addr, value, 3, pageCrossPenalty: 1), (cpu) => cpu.DecodeRelative(), AddressingMode.Relative) },
            { 0x31, new OpCodeDefinition("AND", (cpu, addr, value) => cpu.AND(addr, value, 5), (cpu) => cpu.DecodeIndirectYIndexed(), AddressingMode.IndirectYIndexed) },
            { 0x32, new OpCodeDefinition(null, (cpu, addr, value) => cpu.IllegalInstruction(addr, value, 5), (cpu) => cpu.DecodeUndefined(), AddressingMode.Unknown) },
            { 0x33, new OpCodeDefinition(null, (cpu, addr, value) => cpu.IllegalInstruction(addr, value, 0), (cpu) => cpu.DecodeUndefined(), AddressingMode.Unknown) },
            { 0x34, new OpCodeDefinition(null, (cpu, addr, value) => cpu.IllegalInstruction(addr, value, 4), (cpu) => cpu.DecodeUndefined(), AddressingMode.Unknown) },
            { 0x35, new OpCodeDefinition("AND", (cpu, addr, value) => cpu.AND(addr, value, 4), (cpu) => cpu.DecodeZeroPageXIndexed(), AddressingMode.ZeroPageXIndexed) },
            { 0x36, new OpCodeDefinition("ROL", (cpu, addr, value) => cpu.ROL(addr, value, 6), (cpu) => cpu.DecodeZeroPageXIndexed(), AddressingMode.ZeroPageXIndexed) },
            { 0x37, new OpCodeDefinition(null, (cpu, addr, value) => cpu.IllegalInstruction(addr, value, 5), (cpu) => cpu.DecodeUndefined(), AddressingMode.Unknown) },
            { 0x38, new OpCodeDefinition("SEC", (cpu, addr, value) => cpu.SEC(addr, value, 2), (cpu) => cpu.DecodeImplied(), AddressingMode.Implied) },
            { 0x39, new OpCodeDefinition("AND", (cpu, addr, value) => cpu.AND(addr, value, 4, pageCrossPenalty: 1), (cpu) => cpu.DecodeAbsoluteYIndexed(), AddressingMode.AbsoluteYIndexed) },
            { 0x3a, new OpCodeDefinition(null, (cpu, addr, value) => cpu.IllegalInstruction(addr, value, 2), (cpu) => cpu.DecodeUndefined(), AddressingMode.Unknown) },
            { 0x3b, new OpCodeDefinition(null, (cpu, addr, value) => cpu.IllegalInstruction(addr, value, 0), (cpu) => cpu.DecodeUndefined(), AddressingMode.Unknown) },
            { 0x3c, new OpCodeDefinition(null, (cpu, addr, value) => cpu.IllegalInstruction(addr, value, 4), (cpu) => cpu.DecodeUndefined(), AddressingMode.Unknown) },
            { 0x3d, new OpCodeDefinition("AND", (cpu, addr, value) => cpu.AND(addr, value, 4, pageCrossPenalty: 1), (cpu) => cpu.DecodeAbsoluteXIndexed(), AddressingMode.AbsoluteXIndexed) },
            { 0x3e, new OpCodeDefinition("ROL", (cpu, addr, value) => cpu.ROL(addr, value, 7), (cpu) => cpu.DecodeAbsoluteXIndexed(), AddressingMode.AbsoluteXIndexed) },
            { 0x3f, new OpCodeDefinition(null, (cpu, addr, value) => cpu.IllegalInstruction(addr, value, 5), (cpu) => cpu.DecodeUndefined(), AddressingMode.Unknown) },

            { 0x40, new OpCodeDefinition("RTI", (cpu, addr, value) => cpu.RTI(addr, value, 6), (cpu) => cpu.DecodeStack(), AddressingMode.Stack) },
            { 0x41, new OpCodeDefinition("EOR", (cpu, addr, value) => cpu.EOR(addr, value, 6), (cpu) => cpu.DecodeXIndexedIndirect(), AddressingMode.XIndexedIndirect) },
            { 0x42, new OpCodeDefinition(null, (cpu, addr, value) => cpu.IllegalInstruction(addr, value, 0), (cpu) => cpu.DecodeUndefined(), AddressingMode.Unknown) },
            { 0x43, new OpCodeDefinition(null, (cpu, addr, value) => cpu.IllegalInstruction(addr, value, 0), (cpu) => cpu.DecodeUndefined(), AddressingMode.Unknown) },
            { 0x44, new OpCodeDefinition(null, (cpu, addr, value) => cpu.IllegalInstruction(addr, value, 0), (cpu) => cpu.DecodeUndefined(), AddressingMode.Unknown) },
            { 0x45, new OpCodeDefinition("EOR", (cpu, addr, value) => cpu.EOR(addr, value, 3), (cpu) => cpu.DecodeZeroPage(), AddressingMode.ZeroPage) },
            { 0x46, new OpCodeDefinition("LSR", (cpu, addr, value) => cpu.LSR(addr, value, 5), (cpu) => cpu.DecodeZeroPage(), AddressingMode.ZeroPage) },
            { 0x47, new OpCodeDefinition(null, (cpu, addr, value) => cpu.IllegalInstruction(addr, value, 5), (cpu) => cpu.DecodeUndefined(), AddressingMode.Unknown) },
            { 0x48, new OpCodeDefinition("PHA", (cpu, addr, value) => cpu.PHA(addr, value, 3), (cpu) => cpu.DecodeStack(), AddressingMode.Stack) },
            { 0x49, new OpCodeDefinition("EOR", (cpu, addr, value) => cpu.EOR(addr, value, 2), (cpu) => cpu.DecodeImmediate(), AddressingMode.Immediate) },
            { 0x4a, new OpCodeDefinition("LSR", (cpu, addr, value) => cpu.LSR_A(addr, value, 2), (cpu) => cpu.DecodeAccumulator(), AddressingMode.Accumulator) },
            { 0x4b, new OpCodeDefinition(null, (cpu, addr, value) => cpu.IllegalInstruction(addr, value, 0), (cpu) => cpu.DecodeUndefined(), AddressingMode.Unknown) },
            { 0x4c, new OpCodeDefinition("JMP", (cpu, addr, value) => cpu.JMP(addr, value, 3), (cpu) => cpu.DecodeAbsolute(), AddressingMode.Absolute) },
            { 0x4d, new OpCodeDefinition("EOR", (cpu, addr, value) => cpu.EOR(addr, value, 4), (cpu) => cpu.DecodeAbsolute(), AddressingMode.Absolute) },
            { 0x4e, new OpCodeDefinition("LSR", (cpu, addr, value) => cpu.LSR(addr, value, 6), (cpu) => cpu.DecodeAbsolute(), AddressingMode.Absolute) },
            { 0x4f, new OpCodeDefinition(null, (cpu, addr, value) => cpu.IllegalInstruction(addr, value, 5), (cpu) => cpu.DecodeUndefined(), AddressingMode.Unknown) },

            { 0x50, new OpCodeDefinition("BVC", (cpu, addr, value) => cpu.BVC(addr, value, 3, pageCrossPenalty: 1), (cpu) => cpu.DecodeRelative(), AddressingMode.Relative) },
            { 0x51, new OpCodeDefinition("EOR", (cpu, addr, value) => cpu.EOR(addr, value, 5, pageCrossPenalty: 1), (cpu) => cpu.DecodeIndirectYIndexed(), AddressingMode.IndirectYIndexed) },
            { 0x52, new OpCodeDefinition(null, (cpu, addr, value) => cpu.IllegalInstruction(addr, value, 5), (cpu) => cpu.DecodeUndefined(), AddressingMode.Unknown) },
            { 0x53, new OpCodeDefinition(null, (cpu, addr, value) => cpu.IllegalInstruction(addr, value, 0), (cpu) => cpu.DecodeUndefined(), AddressingMode.Unknown) },
            { 0x54, new OpCodeDefinition(null, (cpu, addr, value) => cpu.IllegalInstruction(addr, value, 0), (cpu) => cpu.DecodeUndefined(), AddressingMode.Unknown) },
            { 0x55, new OpCodeDefinition("EOR", (cpu, addr, value) => cpu.EOR(addr, value, 4), (cpu) => cpu.DecodeZeroPageXIndexed(), AddressingMode.ZeroPageXIndexed) },
            { 0x56, new OpCodeDefinition("LSR", (cpu, addr, value) => cpu.LSR(addr, value, 6), (cpu) => cpu.DecodeZeroPageXIndexed(), AddressingMode.ZeroPageXIndexed) },
            { 0x57, new OpCodeDefinition(null, (cpu, addr, value) => cpu.IllegalInstruction(addr, value, 5), (cpu) => cpu.DecodeUndefined(), AddressingMode.Unknown) },
            { 0x58, new OpCodeDefinition("CLI", (cpu, addr, value) => cpu.CLI(addr, value, 2), (cpu) => cpu.DecodeImplied(), AddressingMode.Implied) },
            { 0x59, new OpCodeDefinition("EOR", (cpu, addr, value) => cpu.EOR(addr, value, 4, pageCrossPenalty: 1), (cpu) => cpu.DecodeAbsoluteYIndexed(), AddressingMode.AbsoluteYIndexed) },
            { 0x5a, new OpCodeDefinition(null, (cpu, addr, value) => cpu.IllegalInstruction(addr, value, 3), (cpu) => cpu.DecodeUndefined(), AddressingMode.Unknown) },
            { 0x5b, new OpCodeDefinition(null, (cpu, addr, value) => cpu.IllegalInstruction(addr, value, 0), (cpu) => cpu.DecodeUndefined(), AddressingMode.Unknown) },
            { 0x5c, new OpCodeDefinition(null, (cpu, addr, value) => cpu.IllegalInstruction(addr, value, 0), (cpu) => cpu.DecodeUndefined(), AddressingMode.Unknown) },
            { 0x5d, new OpCodeDefinition("EOR", (cpu, addr, value) => cpu.EOR(addr, value, 4, pageCrossPenalty: 1), (cpu) => cpu.DecodeAbsoluteXIndexed(), AddressingMode.AbsoluteXIndexed) },
            { 0x5e, new OpCodeDefinition("LSR", (cpu, addr, value) => cpu.LSR(addr, value, 7), (cpu) => cpu.DecodeAbsoluteXIndexed(), AddressingMode.AbsoluteXIndexed) },
            { 0x5f, new OpCodeDefinition(null, (cpu, addr, value) => cpu.IllegalInstruction(addr, value, 5), (cpu) => cpu.DecodeUndefined(), AddressingMode.Unknown) },

            { 0x60, new OpCodeDefinition("RTS", (cpu, addr, value) => cpu.RTS(addr, value, 6), (cpu) => cpu.DecodeStack(), AddressingMode.Stack) },
            { 0x61, new OpCodeDefinition("ADC", (cpu, addr, value) => cpu.ADC_NMOS(addr, value, 6), (cpu) => cpu.DecodeXIndexedIndirect(), AddressingMode.XIndexedIndirect) },
            { 0x62, new OpCodeDefinition(null, (cpu, addr, value) => cpu.IllegalInstruction(addr, value, 0), (cpu) => cpu.DecodeUndefined(), AddressingMode.Unknown) },
            { 0x63, new OpCodeDefinition(null, (cpu, addr, value) => cpu.IllegalInstruction(addr, value, 0), (cpu) => cpu.DecodeUndefined(), AddressingMode.Unknown) },
            { 0x64, new OpCodeDefinition(null, (cpu, addr, value) => cpu.IllegalInstruction(addr, value, 3), (cpu) => cpu.DecodeUndefined(), AddressingMode.Unknown) },
            { 0x65, new OpCodeDefinition("ADC", (cpu, addr, value) => cpu.ADC_NMOS(addr, value, 3), (cpu) => cpu.DecodeZeroPage(), AddressingMode.ZeroPage) },
            { 0x66, new OpCodeDefinition("ROR", (cpu, addr, value) => cpu.ROR(addr, value, 5), (cpu) => cpu.DecodeZeroPage(), AddressingMode.ZeroPage) },
            { 0x67, new OpCodeDefinition(null, (cpu, addr, value) => cpu.IllegalInstruction(addr, value, 5), (cpu) => cpu.DecodeUndefined(), AddressingMode.Unknown) },
            { 0x68, new OpCodeDefinition("PLA", (cpu, addr, value) => cpu.PLA(addr, value, 4), (cpu) => cpu.DecodeStack(), AddressingMode.Stack) },
            { 0x69, new OpCodeDefinition("ADC", (cpu, addr, value) => cpu.ADC_NMOS(addr, value, 2), (cpu) => cpu.DecodeImmediate(), AddressingMode.Immediate) },
            { 0x6a, new OpCodeDefinition("ROR", (cpu, addr, value) => cpu.ROR_A(addr, value, 2), (cpu) => cpu.DecodeAccumulator(), AddressingMode.Accumulator) },
            { 0x6b, new OpCodeDefinition(null, (cpu, addr, value) => cpu.IllegalInstruction(addr, value, 0), (cpu) => cpu.DecodeUndefined(), AddressingMode.Unknown) },
            { 0x6c, new OpCodeDefinition("JMP", (cpu, addr, value) => cpu.JMP(addr, value, 6), (cpu) => cpu.DecodeAbsoluteIndirect(), AddressingMode.AbsoluteIndirect) },
            { 0x6d, new OpCodeDefinition("ADC", (cpu, addr, value) => cpu.ADC_NMOS(addr, value, 4), (cpu) => cpu.DecodeAbsolute(), AddressingMode.Absolute) },
            { 0x6e, new OpCodeDefinition("ROR", (cpu, addr, value) => cpu.ROR(addr, value, 6), (cpu) => cpu.DecodeAbsolute(), AddressingMode.Absolute) },
            { 0x6f, new OpCodeDefinition(null, (cpu, addr, value) => cpu.IllegalInstruction(addr, value, 5), (cpu) => cpu.DecodeUndefined(), AddressingMode.Unknown) },

            { 0x70, new OpCodeDefinition("BVS", (cpu, addr, value) => cpu.BVS(addr, value, 3, pageCrossPenalty: 1), (cpu) => cpu.DecodeRelative(), AddressingMode.Relative) },
            { 0x71, new OpCodeDefinition("ADC", (cpu, addr, value) => cpu.ADC_NMOS(addr, value, 5, pageCrossPenalty: 1), (cpu) => cpu.DecodeIndirectYIndexed(), AddressingMode.IndirectYIndexed) },
            { 0x72, new OpCodeDefinition(null, (cpu, addr, value) => cpu.IllegalInstruction(addr, value, 5), (cpu) => cpu.DecodeUndefined(), AddressingMode.Unknown) },
            { 0x73, new OpCodeDefinition(null, (cpu, addr, value) => cpu.IllegalInstruction(addr, value, 0), (cpu) => cpu.DecodeUndefined(), AddressingMode.Unknown) },
            { 0x74, new OpCodeDefinition(null, (cpu, addr, value) => cpu.IllegalInstruction(addr, value, 4), (cpu) => cpu.DecodeUndefined(), AddressingMode.Unknown) },
            { 0x75, new OpCodeDefinition("ADC", (cpu, addr, value) => cpu.ADC_NMOS(addr, value, 4), (cpu) => cpu.DecodeZeroPageXIndexed(), AddressingMode.ZeroPageXIndexed) },
            { 0x76, new OpCodeDefinition("ROR", (cpu, addr, value) => cpu.ROR(addr, value, 6), (cpu) => cpu.DecodeZeroPageXIndexed(), AddressingMode.ZeroPageXIndexed) },
            { 0x77, new OpCodeDefinition(null, (cpu, addr, value) => cpu.IllegalInstruction(addr, value, 5), (cpu) => cpu.DecodeUndefined(), AddressingMode.Unknown) },
            { 0x78, new OpCodeDefinition("SEI", (cpu, addr, value) => cpu.SEI(addr, value, 2), (cpu) => cpu.DecodeImplied(), AddressingMode.Implied) },
            { 0x79, new OpCodeDefinition("ADC", (cpu, addr, value) => cpu.ADC_NMOS(addr, value, 4, pageCrossPenalty: 1), (cpu) => cpu.DecodeAbsoluteYIndexed(), AddressingMode.AbsoluteYIndexed) },
            { 0x7a, new OpCodeDefinition(null, (cpu, addr, value) => cpu.IllegalInstruction(addr, value, 4), (cpu) => cpu.DecodeUndefined(), AddressingMode.Unknown) },
            { 0x7b, new OpCodeDefinition(null, (cpu, addr, value) => cpu.IllegalInstruction(addr, value, 0), (cpu) => cpu.DecodeUndefined(), AddressingMode.Unknown) },
            { 0x7c, new OpCodeDefinition(null, (cpu, addr, value) => cpu.IllegalInstruction(addr, value, 6), (cpu) => cpu.DecodeUndefined(), AddressingMode.Unknown) },
            { 0x7d, new OpCodeDefinition("ADC", (cpu, addr, value) => cpu.ADC_NMOS(addr, value, 4, pageCrossPenalty: 1), (cpu) => cpu.DecodeAbsoluteXIndexed(), AddressingMode.AbsoluteXIndexed) },
            { 0x7e, new OpCodeDefinition("ROR", (cpu, addr, value) => cpu.ROR(addr, value, 7), (cpu) => cpu.DecodeAbsoluteXIndexed(), AddressingMode.AbsoluteXIndexed) },
            { 0x7f, new OpCodeDefinition(null, (cpu, addr, value) => cpu.IllegalInstruction(addr, value, 5), (cpu) => cpu.DecodeUndefined(), AddressingMode.Unknown) },

            { 0x80, new OpCodeDefinition(null, (cpu, addr, value) => cpu.IllegalInstruction(addr, value, 3), (cpu) => cpu.DecodeUndefined(), AddressingMode.Unknown) },
            { 0x81, new OpCodeDefinition("STA", (cpu, addr, value) => cpu.STA(addr, value, 6), (cpu) => cpu.DecodeXIndexedIndirect(), AddressingMode.XIndexedIndirect) },
            { 0x82, new OpCodeDefinition(null, (cpu, addr, value) => cpu.IllegalInstruction(addr, value, 0), (cpu) => cpu.DecodeUndefined(), AddressingMode.Unknown) },
            { 0x83, new OpCodeDefinition(null, (cpu, addr, value) => cpu.IllegalInstruction(addr, value, 0), (cpu) => cpu.DecodeUndefined(), AddressingMode.Unknown) },
            { 0x84, new OpCodeDefinition("STY", (cpu, addr, value) => cpu.STY(addr, value, 3), (cpu) => cpu.DecodeZeroPage(), AddressingMode.ZeroPage) },
            { 0x85, new OpCodeDefinition("STA", (cpu, addr, value) => cpu.STA(addr, value, 3), (cpu) => cpu.DecodeZeroPage(), AddressingMode.ZeroPage) },
            { 0x86, new OpCodeDefinition("STX", (cpu, addr, value) => cpu.STX(addr, value, 3), (cpu) => cpu.DecodeZeroPage(), AddressingMode.ZeroPage) },
            { 0x87, new OpCodeDefinition("SMB", (cpu, addr, value) => cpu.SMB(addr, value, bit: 0, 5), (cpu) => cpu.DecodeZeroPage(), AddressingMode.ZeroPage) },
            { 0x88, new OpCodeDefinition("DEY", (cpu, addr, value) => cpu.DEY(addr, value, 2), (cpu) => cpu.DecodeImplied(), AddressingMode.Implied) },
            { 0x89, new OpCodeDefinition(null, (cpu, addr, value) => cpu.IllegalInstruction(addr, value, 2), (cpu) => cpu.DecodeUndefined(), AddressingMode.Unknown) },
            { 0x8a, new OpCodeDefinition("TXA", (cpu, addr, value) => cpu.TXA(addr, value, 2), (cpu) => cpu.DecodeImplied(), AddressingMode.Implied) },
            { 0x8b, new OpCodeDefinition(null, (cpu, addr, value) => cpu.IllegalInstruction(addr, value, 0), (cpu) => cpu.DecodeUndefined(), AddressingMode.Unknown) },
            { 0x8c, new OpCodeDefinition("STY", (cpu, addr, value) => cpu.STY(addr, value, 4), (cpu) => cpu.DecodeAbsolute(), AddressingMode.Absolute) },
            { 0x8d, new OpCodeDefinition("STA", (cpu, addr, value) => cpu.STA(addr, value, 4), (cpu) => cpu.DecodeAbsolute(), AddressingMode.Absolute) },
            { 0x8e, new OpCodeDefinition("STX", (cpu, addr, value) => cpu.STX(addr, value, 4), (cpu) => cpu.DecodeAbsolute(), AddressingMode.Absolute) },
            { 0x8f, new OpCodeDefinition("BBS", (cpu, addr, value) => cpu.BBS(addr, value, bit: 0, 5), (cpu) => cpu.DecodeRelative(), AddressingMode.Relative) },

            { 0x90, new OpCodeDefinition("BCC", (cpu, addr, value) => cpu.BCC(addr, value, 3, pageCrossPenalty: 1), (cpu) => cpu.DecodeRelative(), AddressingMode.Relative) },
            { 0x91, new OpCodeDefinition("STA", (cpu, addr, value) => cpu.STA(addr, value, 6), (cpu) => cpu.DecodeIndirectYIndexed(), AddressingMode.IndirectYIndexed) },
            { 0x92, new OpCodeDefinition(null, (cpu, addr, value) => cpu.IllegalInstruction(addr, value, 5), (cpu) => cpu.DecodeUndefined(), AddressingMode.Unknown) },
            { 0x93, new OpCodeDefinition(null, (cpu, addr, value) => cpu.IllegalInstruction(addr, value, 0), (cpu) => cpu.DecodeUndefined(), AddressingMode.Unknown) },
            { 0x94, new OpCodeDefinition("STY", (cpu, addr, value) => cpu.STY(addr, value, 4), (cpu) => cpu.DecodeZeroPageXIndexed(), AddressingMode.ZeroPageXIndexed) },
            { 0x95, new OpCodeDefinition("STA", (cpu, addr, value) => cpu.STA(addr, value, 4), (cpu) => cpu.DecodeZeroPageXIndexed(), AddressingMode.ZeroPageXIndexed) },
            { 0x96, new OpCodeDefinition("STX", (cpu, addr, value) => cpu.STX(addr, value, 4), (cpu) => cpu.DecodeZeroPageYIndexed(), AddressingMode.ZeroPageYIndexed) },
            { 0x97, new OpCodeDefinition("SMB", (cpu, addr, value) => cpu.SMB(addr, value, bit: 1, 5), (cpu) => cpu.DecodeZeroPage(), AddressingMode.ZeroPage) },
            { 0x98, new OpCodeDefinition("TYA", (cpu, addr, value) => cpu.TYA(addr, value, 2), (cpu) => cpu.DecodeImplied(), AddressingMode.Implied) },
            { 0x99, new OpCodeDefinition("STA", (cpu, addr, value) => cpu.STA(addr, value, 5), (cpu) => cpu.DecodeAbsoluteYIndexed(), AddressingMode.AbsoluteYIndexed) },
            { 0x9a, new OpCodeDefinition("TXS", (cpu, addr, value) => cpu.TXS(addr, value, 2), (cpu) => cpu.DecodeImplied(), AddressingMode.Implied) },
            { 0x9b, new OpCodeDefinition(null, (cpu, addr, value) => cpu.IllegalInstruction(addr, value, 0), (cpu) => cpu.DecodeUndefined(), AddressingMode.Unknown) },
            { 0x9c, new OpCodeDefinition(null, (cpu, addr, value) => cpu.IllegalInstruction(addr, value, 4), (cpu) => cpu.DecodeUndefined(), AddressingMode.Unknown) },
            { 0x9d, new OpCodeDefinition("STA", (cpu, addr, value) => cpu.STA(addr, value, 5), (cpu) => cpu.DecodeAbsoluteXIndexed(), AddressingMode.AbsoluteXIndexed) },
            { 0x9e, new OpCodeDefinition(null, (cpu, addr, value) => cpu.IllegalInstruction(addr, value, 5), (cpu) => cpu.DecodeUndefined(), AddressingMode.Unknown) },
            { 0x9f, new OpCodeDefinition("BBS", (cpu, addr, value) => cpu.BBS(addr, value, bit: 1, 5), (cpu) => cpu.DecodeRelative(), AddressingMode.Relative) },

            { 0xa0, new OpCodeDefinition("LDY", (cpu, addr, value) => cpu.LDY(addr, value, 2), (cpu) => cpu.DecodeImmediate(), AddressingMode.Immediate) },
            { 0xa1, new OpCodeDefinition("LDA", (cpu, addr, value) => cpu.LDA(addr, value, 6), (cpu) => cpu.DecodeXIndexedIndirect(), AddressingMode.XIndexedIndirect) },
            { 0xa2, new OpCodeDefinition("LDX", (cpu, addr, value) => cpu.LDX(addr, value, 2), (cpu) => cpu.DecodeImmediate(), AddressingMode.Immediate) },
            { 0xa3, new OpCodeDefinition(null, (cpu, addr, value) => cpu.IllegalInstruction(addr, value, 0), (cpu) => cpu.DecodeUndefined(), AddressingMode.Unknown) },
            { 0xa4, new OpCodeDefinition("LDY", (cpu, addr, value) => cpu.LDY(addr, value, 3), (cpu) => cpu.DecodeZeroPage(), AddressingMode.ZeroPage) },
            { 0xa5, new OpCodeDefinition("LDA", (cpu, addr, value) => cpu.LDA(addr, value, 3), (cpu) => cpu.DecodeZeroPage(), AddressingMode.ZeroPage) },
            { 0xa6, new OpCodeDefinition("LDX", (cpu, addr, value) => cpu.LDX(addr, value, 3), (cpu) => cpu.DecodeZeroPage(), AddressingMode.ZeroPage) },
            { 0xa7, new OpCodeDefinition("SMB", (cpu, addr, value) => cpu.SMB(addr, value, bit: 2, 5), (cpu) => cpu.DecodeZeroPage(), AddressingMode.ZeroPage) },
            { 0xa8, new OpCodeDefinition("TAY", (cpu, addr, value) => cpu.TAY(addr, value, 2), (cpu) => cpu.DecodeImplied(), AddressingMode.Implied) },
            { 0xa9, new OpCodeDefinition("LDA", (cpu, addr, value) => cpu.LDA(addr, value, 2), (cpu) => cpu.DecodeImmediate(), AddressingMode.Immediate) },
            { 0xaa, new OpCodeDefinition("TAX", (cpu, addr, value) => cpu.TAX(addr, value, 2), (cpu) => cpu.DecodeImplied(), AddressingMode.Implied) },
            { 0xab, new OpCodeDefinition(null, (cpu, addr, value) => cpu.IllegalInstruction(addr, value, 0), (cpu) => cpu.DecodeUndefined(), AddressingMode.Unknown) },
            { 0xac, new OpCodeDefinition("LDY", (cpu, addr, value) => cpu.LDY(addr, value, 4), (cpu) => cpu.DecodeAbsolute(), AddressingMode.Absolute) },
            { 0xad, new OpCodeDefinition("LDA", (cpu, addr, value) => cpu.LDA(addr, value, 4), (cpu) => cpu.DecodeAbsolute(), AddressingMode.Absolute) },
            { 0xae, new OpCodeDefinition("LDX", (cpu, addr, value) => cpu.LDX(addr, value, 4), (cpu) => cpu.DecodeAbsolute(), AddressingMode.Absolute) },
            { 0xaf, new OpCodeDefinition("BBS", (cpu, addr, value) => cpu.BBS(addr, value, bit: 2, 5), (cpu) => cpu.DecodeRelative(), AddressingMode.Relative) },

            { 0xb0, new OpCodeDefinition("BCS", (cpu, addr, value) => cpu.BCS(addr, value, 3, pageCrossPenalty: 1), (cpu) => cpu.DecodeRelative(), AddressingMode.Relative) },
            { 0xb1, new OpCodeDefinition("LDA", (cpu, addr, value) => cpu.LDA(addr, value, 5, pageCrossPenalty: 1), (cpu) => cpu.DecodeIndirectYIndexed(), AddressingMode.IndirectYIndexed) },
            { 0xb2, new OpCodeDefinition(null, (cpu, addr, value) => cpu.IllegalInstruction(addr, value, 5), (cpu) => cpu.DecodeUndefined(), AddressingMode.Unknown) },
            { 0xb3, new OpCodeDefinition(null, (cpu, addr, value) => cpu.IllegalInstruction(addr, value, 0), (cpu) => cpu.DecodeUndefined(), AddressingMode.Unknown) },
            { 0xb4, new OpCodeDefinition("LDY", (cpu, addr, value) => cpu.LDY(addr, value, 4), (cpu) => cpu.DecodeZeroPageXIndexed(), AddressingMode.ZeroPageXIndexed) },
            { 0xb5, new OpCodeDefinition("LDA", (cpu, addr, value) => cpu.LDA(addr, value, 4), (cpu) => cpu.DecodeZeroPageXIndexed(), AddressingMode.ZeroPageXIndexed) },
            { 0xb6, new OpCodeDefinition("LDX", (cpu, addr, value) => cpu.LDX(addr, value, 4), (cpu) => cpu.DecodeZeroPageYIndexed(), AddressingMode.ZeroPageYIndexed) },
            { 0xb7, new OpCodeDefinition("SMB", (cpu, addr, value) => cpu.SMB(addr, value, bit: 3, 5), (cpu) => cpu.DecodeZeroPage(), AddressingMode.ZeroPage) },
            { 0xb8, new OpCodeDefinition("CLV", (cpu, addr, value) => cpu.CLV(addr, value, 2), (cpu) => cpu.DecodeImplied(), AddressingMode.Implied) },
            { 0xb9, new OpCodeDefinition("LDA", (cpu, addr, value) => cpu.LDA(addr, value, 4, pageCrossPenalty: 1), (cpu) => cpu.DecodeAbsoluteYIndexed(), AddressingMode.AbsoluteYIndexed) },
            { 0xba, new OpCodeDefinition("TSX", (cpu, addr, value) => cpu.TSX(addr, value, 2), (cpu) => cpu.DecodeImplied(), AddressingMode.Implied) },
            { 0xbb, new OpCodeDefinition(null, (cpu, addr, value) => cpu.IllegalInstruction(addr, value, 0), (cpu) => cpu.DecodeUndefined(), AddressingMode.Unknown) },
            { 0xbc, new OpCodeDefinition("LDY", (cpu, addr, value) => cpu.LDY(addr, value, 4, pageCrossPenalty: 1), (cpu) => cpu.DecodeAbsoluteXIndexed(), AddressingMode.AbsoluteXIndexed) },
            { 0xbd, new OpCodeDefinition("LDA", (cpu, addr, value) => cpu.LDA(addr, value, 4, pageCrossPenalty: 1), (cpu) => cpu.DecodeAbsoluteXIndexed(), AddressingMode.AbsoluteXIndexed) },
            { 0xbe, new OpCodeDefinition("LDX", (cpu, addr, value) => cpu.LDX(addr, value, 4, pageCrossPenalty: 1), (cpu) => cpu.DecodeAbsoluteYIndexed(), AddressingMode.AbsoluteYIndexed) },
            { 0xbf, new OpCodeDefinition("BBS", (cpu, addr, value) => cpu.BBS(addr, value, bit: 3, 5), (cpu) => cpu.DecodeRelative(), AddressingMode.Relative) },

            { 0xc0, new OpCodeDefinition("CPY", (cpu, addr, value) => cpu.CPY(addr, value, 2), (cpu) => cpu.DecodeImmediate(), AddressingMode.Immediate) },
            { 0xc1, new OpCodeDefinition("CMP", (cpu, addr, value) => cpu.CMP(addr, value, 6), (cpu) => cpu.DecodeXIndexedIndirect(), AddressingMode.XIndexedIndirect) },
            { 0xc2, new OpCodeDefinition(null, (cpu, addr, value) => cpu.IllegalInstruction(addr, value, 0), (cpu) => cpu.DecodeUndefined(), AddressingMode.Unknown) },
            { 0xc3, new OpCodeDefinition(null, (cpu, addr, value) => cpu.IllegalInstruction(addr, value, 0), (cpu) => cpu.DecodeUndefined(), AddressingMode.Unknown) },
            { 0xc4, new OpCodeDefinition("CPY", (cpu, addr, value) => cpu.CPY(addr, value, 3), (cpu) => cpu.DecodeZeroPage(), AddressingMode.ZeroPage) },
            { 0xc5, new OpCodeDefinition("CMP", (cpu, addr, value) => cpu.CMP(addr, value, 3), (cpu) => cpu.DecodeZeroPage(), AddressingMode.ZeroPage) },
            { 0xc6, new OpCodeDefinition("DEC", (cpu, addr, value) => cpu.DEC(addr, value, 5), (cpu) => cpu.DecodeZeroPage(), AddressingMode.ZeroPage) },
            { 0xc7, new OpCodeDefinition("SMB", (cpu, addr, value) => cpu.SMB(addr, value, bit: 4, 5), (cpu) => cpu.DecodeZeroPage(), AddressingMode.ZeroPage) },
            { 0xc8, new OpCodeDefinition("INY", (cpu, addr, value) => cpu.INY(addr, value, 2), (cpu) => cpu.DecodeImplied(), AddressingMode.Implied) },
            { 0xc9, new OpCodeDefinition("CMP", (cpu, addr, value) => cpu.CMP(addr, value, 2), (cpu) => cpu.DecodeImmediate(), AddressingMode.Immediate) },
            { 0xca, new OpCodeDefinition("DEX", (cpu, addr, value) => cpu.DEX(addr, value, 2), (cpu) => cpu.DecodeImplied(), AddressingMode.Implied) },
            { 0xcb, new OpCodeDefinition(null, (cpu, addr, value) => cpu.IllegalInstruction(addr, value, 0), (cpu) => cpu.DecodeUndefined(), AddressingMode.Unknown) },
            { 0xcc, new OpCodeDefinition("CPY", (cpu, addr, value) => cpu.CPY(addr, value, 4), (cpu) => cpu.DecodeAbsolute(), AddressingMode.Absolute) },
            { 0xcd, new OpCodeDefinition("CMP", (cpu, addr, value) => cpu.CMP(addr, value, 4), (cpu) => cpu.DecodeAbsolute(), AddressingMode.Absolute) },
            { 0xce, new OpCodeDefinition("DEC", (cpu, addr, value) => cpu.DEC(addr, value, 6), (cpu) => cpu.DecodeAbsolute(), AddressingMode.Absolute) },
            { 0xcf, new OpCodeDefinition("BBS", (cpu, addr, value) => cpu.BBS(addr, value, bit: 4, 5), (cpu) => cpu.DecodeRelative(), AddressingMode.Relative) },

            { 0xd0, new OpCodeDefinition("BNE", (cpu, addr, value) => cpu.BNE(addr, value, 3, pageCrossPenalty: 1), (cpu) => cpu.DecodeRelative(), AddressingMode.Relative) },
            { 0xd1, new OpCodeDefinition("CMP", (cpu, addr, value) => cpu.CMP(addr, value, 5, pageCrossPenalty: 1), (cpu) => cpu.DecodeIndirectYIndexed(), AddressingMode.IndirectYIndexed) },
            { 0xd2, new OpCodeDefinition(null, (cpu, addr, value) => cpu.IllegalInstruction(addr, value, 5), (cpu) => cpu.DecodeUndefined(), AddressingMode.Unknown) },
            { 0xd3, new OpCodeDefinition(null, (cpu, addr, value) => cpu.IllegalInstruction(addr, value, 0), (cpu) => cpu.DecodeUndefined(), AddressingMode.Unknown) },
            { 0xd4, new OpCodeDefinition(null, (cpu, addr, value) => cpu.IllegalInstruction(addr, value, 0), (cpu) => cpu.DecodeUndefined(), AddressingMode.Unknown) },
            { 0xd5, new OpCodeDefinition("CMP", (cpu, addr, value) => cpu.CMP(addr, value, 4), (cpu) => cpu.DecodeZeroPageXIndexed(), AddressingMode.ZeroPageXIndexed) },
            { 0xd6, new OpCodeDefinition("DEC", (cpu, addr, value) => cpu.DEC(addr, value, 6), (cpu) => cpu.DecodeZeroPageXIndexed(), AddressingMode.ZeroPageXIndexed) },
            { 0xd7, new OpCodeDefinition("SMB", (cpu, addr, value) => cpu.SMB(addr, value, bit: 5, 5), (cpu) => cpu.DecodeZeroPage(), AddressingMode.ZeroPage) },
            { 0xd8, new OpCodeDefinition("CLD", (cpu, addr, value) => cpu.CLD(addr, value, 2), (cpu) => cpu.DecodeImplied(), AddressingMode.Implied) },
            { 0xd9, new OpCodeDefinition("CMP", (cpu, addr, value) => cpu.CMP(addr, value, 4, pageCrossPenalty: 1), (cpu) => cpu.DecodeAbsoluteYIndexed(), AddressingMode.AbsoluteYIndexed) },
            { 0xda, new OpCodeDefinition(null, (cpu, addr, value) => cpu.IllegalInstruction(addr, value, 3), (cpu) => cpu.DecodeUndefined(), AddressingMode.Unknown) },
            { 0xdb, new OpCodeDefinition(null, (cpu, addr, value) => cpu.IllegalInstruction(addr, value, 0), (cpu) => cpu.DecodeUndefined(), AddressingMode.Unknown) },
            { 0xdc, new OpCodeDefinition(null, (cpu, addr, value) => cpu.IllegalInstruction(addr, value, 0), (cpu) => cpu.DecodeUndefined(), AddressingMode.Unknown) },
            { 0xdd, new OpCodeDefinition("CMP", (cpu, addr, value) => cpu.CMP(addr, value, 4, pageCrossPenalty: 1), (cpu) => cpu.DecodeAbsoluteXIndexed(), AddressingMode.AbsoluteXIndexed) },
            { 0xde, new OpCodeDefinition("DEC", (cpu, addr, value) => cpu.DEC(addr, value, 7), (cpu) => cpu.DecodeAbsoluteXIndexed(), AddressingMode.AbsoluteXIndexed) },
            { 0xdf, new OpCodeDefinition("BBS", (cpu, addr, value) => cpu.BBS(addr, value, bit: 5, 5), (cpu) => cpu.DecodeRelative(), AddressingMode.Relative) },

            { 0xe0, new OpCodeDefinition("CPX", (cpu, addr, value) => cpu.CPX(addr, value, 2), (cpu) => cpu.DecodeImmediate(), AddressingMode.Immediate) },
            { 0xe1, new OpCodeDefinition("SBC", (cpu, addr, value) => cpu.SBC_NMOS(addr, value, 6), (cpu) => cpu.DecodeXIndexedIndirect(), AddressingMode.XIndexedIndirect) },
            { 0xe2, new OpCodeDefinition(null, (cpu, addr, value) => cpu.IllegalInstruction(addr, value, 0), (cpu) => cpu.DecodeUndefined(), AddressingMode.Unknown) },
            { 0xe3, new OpCodeDefinition(null, (cpu, addr, value) => cpu.IllegalInstruction(addr, value, 0), (cpu) => cpu.DecodeUndefined(), AddressingMode.Unknown) },
            { 0xe4, new OpCodeDefinition("CPX", (cpu, addr, value) => cpu.CPX(addr, value, 3), (cpu) => cpu.DecodeZeroPage(), AddressingMode.ZeroPage) },
            { 0xe5, new OpCodeDefinition("SBC", (cpu, addr, value) => cpu.SBC_NMOS(addr, value, 3), (cpu) => cpu.DecodeZeroPage(), AddressingMode.ZeroPage) },
            { 0xe6, new OpCodeDefinition("INC", (cpu, addr, value) => cpu.INC(addr, value, 5), (cpu) => cpu.DecodeZeroPage(), AddressingMode.ZeroPage) },
            { 0xe7, new OpCodeDefinition("SMB", (cpu, addr, value) => cpu.SMB(addr, value, bit: 6, 5), (cpu) => cpu.DecodeZeroPage(), AddressingMode.ZeroPage) },
            { 0xe8, new OpCodeDefinition("INX", (cpu, addr, value) => cpu.INX(addr, value, 2), (cpu) => cpu.DecodeImplied(), AddressingMode.Implied) },
            { 0xe9, new OpCodeDefinition("SBC", (cpu, addr, value) => cpu.SBC_NMOS(addr, value, 2), (cpu) => cpu.DecodeImmediate(), AddressingMode.Immediate) },
            { 0xea, new OpCodeDefinition("NOP", (cpu, addr, value) => cpu.NOP(addr, value, 2), (cpu) => cpu.DecodeImplied(), AddressingMode.Implied) },
            { 0xeb, new OpCodeDefinition(null, (cpu, addr, value) => cpu.IllegalInstruction(addr, value, 0), (cpu) => cpu.DecodeUndefined(), AddressingMode.Unknown) },
            { 0xec, new OpCodeDefinition("CPX", (cpu, addr, value) => cpu.CPX(addr, value, 4), (cpu) => cpu.DecodeAbsolute(), AddressingMode.Absolute) },
            { 0xed, new OpCodeDefinition("SBC", (cpu, addr, value) => cpu.SBC_NMOS(addr, value, 4), (cpu) => cpu.DecodeAbsolute(), AddressingMode.Absolute) },
            { 0xee, new OpCodeDefinition("INC", (cpu, addr, value) => cpu.INC(addr, value, 6), (cpu) => cpu.DecodeAbsolute(), AddressingMode.Absolute) },
            { 0xef, new OpCodeDefinition("BBS", (cpu, addr, value) => cpu.BBS(addr, value, bit: 6, 5), (cpu) => cpu.DecodeRelative(), AddressingMode.Relative) },

            { 0xf0, new OpCodeDefinition("BEQ", (cpu, addr, value) => cpu.BEQ(addr, value, 3, pageCrossPenalty: 1), (cpu) => cpu.DecodeRelative(), AddressingMode.Relative) },
            { 0xf1, new OpCodeDefinition("SBC", (cpu, addr, value) => cpu.SBC_NMOS(addr, value, 5, pageCrossPenalty: 1), (cpu) => cpu.DecodeIndirectYIndexed(), AddressingMode.IndirectYIndexed) },
            { 0xf2, new OpCodeDefinition(null, (cpu, addr, value) => cpu.IllegalInstruction(addr, value, 5), (cpu) => cpu.DecodeUndefined(), AddressingMode.Unknown) },
            { 0xf3, new OpCodeDefinition(null, (cpu, addr, value) => cpu.IllegalInstruction(addr, value, 0), (cpu) => cpu.DecodeUndefined(), AddressingMode.Unknown) },
            { 0xf4, new OpCodeDefinition(null, (cpu, addr, value) => cpu.IllegalInstruction(addr, value, 0), (cpu) => cpu.DecodeUndefined(), AddressingMode.Unknown) },
            { 0xf5, new OpCodeDefinition("SBC", (cpu, addr, value) => cpu.SBC_NMOS(addr, value, 4), (cpu) => cpu.DecodeZeroPageXIndexed(), AddressingMode.ZeroPageXIndexed) },
            { 0xf6, new OpCodeDefinition("INC", (cpu, addr, value) => cpu.INC(addr, value, 6), (cpu) => cpu.DecodeZeroPageXIndexed(), AddressingMode.ZeroPageXIndexed) },
            { 0xf7, new OpCodeDefinition("SMB", (cpu, addr, value) => cpu.SMB(addr, value, bit: 7, 5), (cpu) => cpu.DecodeZeroPage(), AddressingMode.ZeroPage) },
            { 0xf8, new OpCodeDefinition("SED", (cpu, addr, value) => cpu.SED(addr, value, 2), (cpu) => cpu.DecodeImplied(), AddressingMode.Implied) },
            { 0xf9, new OpCodeDefinition("SBC", (cpu, addr, value) => cpu.SBC_NMOS(addr, value, 4, pageCrossPenalty: 1), (cpu) => cpu.DecodeAbsoluteYIndexed(), AddressingMode.AbsoluteYIndexed) },
            { 0xfa, new OpCodeDefinition(null, (cpu, addr, value) => cpu.IllegalInstruction(addr, value, 4), (cpu) => cpu.DecodeUndefined(), AddressingMode.Unknown) },
            { 0xfb, new OpCodeDefinition(null, (cpu, addr, value) => cpu.IllegalInstruction(addr, value, 0), (cpu) => cpu.DecodeUndefined(), AddressingMode.Unknown) },
            { 0xfc, new OpCodeDefinition(null, (cpu, addr, value) => cpu.IllegalInstruction(addr, value, 0), (cpu) => cpu.DecodeUndefined(), AddressingMode.Unknown) },
            { 0xfd, new OpCodeDefinition("SBC", (cpu, addr, value) => cpu.SBC_NMOS(addr, value, 4, pageCrossPenalty: 1), (cpu) => cpu.DecodeAbsoluteXIndexed(), AddressingMode.AbsoluteXIndexed) },
            { 0xfe, new OpCodeDefinition("INC", (cpu, addr, value) => cpu.INC(addr, value, 7), (cpu) => cpu.DecodeAbsoluteXIndexed(), AddressingMode.AbsoluteXIndexed) },
            { 0xff, new OpCodeDefinition("BBS", (cpu, addr, value) => cpu.BBS(addr, value, bit: 7, 5), (cpu) => cpu.DecodeRelative(), AddressingMode.Relative) },
        };
    }
}
